### DISCUSSION TITLE
"test" won't skip the non-test sections of my config

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1029] [Q&A]
Hello,

I'm starting PMM like `docker exec -it pmm python plex_meta_manager.py --run -c config/config_mm.yml -nm -rt --cache-libraries
`
because I want PMM to only complete the _test_ sections in my config.

I have no idea, why PMM is trying to build Trakt Liked Lists and TmDb Collection regardless:

```
....
....
|========================================================================================================================================================================================================|
|                                                                        Loading Metadata File: config/mm-dynamic_collections.yml                                                                        |
|========================================================================================================================================================================================================|
|                                                                                                                                                                                                        |
|============================================================================ Building Trakt Liked Lists Dynamic Collections ============================================================================|
|
....
....
|============================================================================ Building TMDb Collections Dynamic Collections =============================================================================|
|                                                                                                                                                                                                        |
| Loading All Movies from Library: Filme                                                                                                                                                                 |
|========================================================================================================================================================================================================|
....
....
```

I just want PMM to go through the _test_ sections and (for my old eyes it seems) I have not enabled `test: true` for dynamic collections. So I expected PMM to skip the dynamic collections section.

I must have something wrong in my configs, but no clue what is wrong?

Building those lists takes precious time ;-D

Any thoughts?


my mm-dynamic_collections.yml
```
dynamic_collections:
  Trakt Liked Lists:
#    test: true
    type: trakt_liked_lists
    data: me
    remove_suffix: Collection, Collections, Filmreihe, Filmreihen
    remove_prefix: The, Die
  TMDb Collections:
#    test: true
    type: tmdb_collection
    remove_suffix: Collection, Collections, Filmreihe, Filmreihen
    remove_prefix: The, Die
```

my config_mm.yml
```
libraries:
  Filme:
    library_name: Filme
    metadata_path:
    - file: config/mm-Filme.yml
    - file: config/mm-dynamic_collections.yml
    - file: config/mm-watchlist-only-Filme.yml
    - file: config/mm-MovieCharts.yml
    operations:
      delete_collections_with_less: 2
      mass_collection_mode: hide
  Serien:
    library_name: Serien
    metadata_path:
    - file: config/mm-Serien.yml
    - file: config/mm-dynamic_collections.yml
    - file: config/mm-watchlist-only-Serien.yml
    operations:
      delete_collections_with_less: 2
      mass_collection_mode: hide
settings:                       
....
```
