### DISCUSSION TITLE
How to NOT delete collections with <n items ?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1074] [Q&A]
Hello,
in general, I'd like to remove collections with less than 2 items in it, 
BUT I have a single collection, which I don't want to be deleted if it contains no item.

How would I set this up?

This is my config so far:
```
libraries:
  Filme:
    library_name: Filme
    metadata_path:
    - file: config/mm-Filme-test.yml
    operations:
      delete_collections_with_less: 2
      mass_collection_mode: hide

...
settings:                                       # Can be individually specified per library as well
  minimum_items: 2
...
  delete_below_minimum: true
...
```
and this collecton should not be deleted by pmm
but I have no clue, how to set it up correctly.
This is what I tried:
```
############Admin Stuff
settings:
  delete_below_minimum: false
  minimum_items: 0

collections:
  '*Trash':
    test: true
    sort_title: 蔡_Trash
    smart_filter:
      all:
        trash: true
      validate: false
      sort_by: title.desc

```

I alway get " Minimum 2 Not Met " and that collections is removed.

Any hints?

Thank you!

**Comment by meisnate12** [comment]
you can use this but it wont stop the operation from deleting your collection 
```yaml
collections:
  '*Trash':
    delete_below_minimum: false
    minimum_items: 0
    test: true
    sort_title: 蔡_Trash
    smart_filter:
      all:
        trash: true
      validate: false
      sort_by: title.desc
```
