### DISCUSSION TITLE
How to filter for audio_language.not: "german" ?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1075] [Q&A]
Hello,

I need to filter out every movie which contains an audio_language called "german". 

It is important, that this is not "German" with capital G or "de" for the language code, it must be "german", like here in plex, which is working great:

<img width="789" alt="lang" src="https://user-images.githubusercontent.com/96403800/193664266-6d5274d4-b877-41ef-94b8-347050ae4235.png">

Is this possible in PMM, if yes, how?

**Comment by chazlarson** [comment]
I would imagine something like:
```
collections:
  contain_german:
    plex_search:
      all:
        audio_language.regex: german

  collection_without_german:
    plex_search:
      all:
        collection.not: contain_german  
```
What have you tried, and what have the results been?
