### DISCUSSION TITLE
: movie_camera : instead of 🎥

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1101] [Q&A]
Hello,

I have a liked trakt list titled: 🎥[ Film - SEQUELS, PREQUELS & REMAKES](https://trakt.tv/users/angel1online/lists/movie_camera-film-sequels-prequels-remakes)

The list, after PMM added it as a dynamic collection with my config,
```
templates:
  my-template4TraktLikedLists:
    trakt_list_details: <<value>>
    sort_title: +++06_1_<<collection_name>>
    collection_order: custom
dynamic_collections:
  Trakt Liked Lists:
    # test: true
    template: my-template4TraktLikedLists
    type: trakt_liked_lists
    data: me
    remove_suffix: Collection, Collections, Filmreihe, Filmreihen, Collezione
    remove_prefix: The, Die
```
is titled: `:movie_camera: Film - SEQUELS, PREQUELS & REMAKES`

so the 🎥 is missing, which plex can display as you can see in my manually renamed collection:

<img width="1139" alt="screen" src="https://user-images.githubusercontent.com/96403800/194708125-324c4d31-4ada-4642-9fae-e203a98791bd.png">

I wonder, if i is possible to _not_ have that `:movie_camera:` and instead the camera character or just nothing, like:

`🎥 Film - SEQUELS, PREQUELS & REMAKES`
or 
`Film - SEQUELS, PREQUELS & REMAKES`

Thank you

**Comment by chazlarson** [comment]
This is not currently possible, but could be added.

Feature request created; add comments if I missed something:
https://features.metamanager.wiki/features/p/emojize-incoming-list-titles

**Comment by meisnate12** [comment]
I'll see about emojis but scanning all text for the few that may have emojis probably isnt the best resource wise. You can always just name that collection manually using `title_override`

```yaml
templates:
  my-template4TraktLikedLists:
    trakt_list_details: <<value>>
    sort_title: +++06_1_<<collection_name>>
    collection_order: custom
dynamic_collections:
  Trakt Liked Lists:
    # test: true
    template: my-template4TraktLikedLists
    type: trakt_liked_lists
    data: me
    remove_suffix: Collection, Collections, Filmreihe, Filmreihen, Collezione
    remove_prefix: The, Die
    title_override:
      https://trakt.tv/users/angel1online/lists/movie_camera-film-sequels-prequels-remakes: "🎥🎥🎥 Film - SEQUELS, PREQUELS & REMAKES 🎥🎥🎥"
```
