### DISCUSSION TITLE
Movie and TV ymls?

### DISCUSSION THREAD

**Discussion by vitadome** [meisnate12/Plex-Meta-Manager#114] [Q&A] [answered]
Do I need separate ymls for Movies and Shows?
If yes, how does the config.yml know which yml to pick?
If no, are there any samples out there on how to incorporate Movie/Show together?

**Comment by meisnate12** [comment, marked as answer]
yes you have to have separate ones. By default it will look for a yml file named the same as your library. so say you have a `Movies` library and a `TV Shows` library and your config looked like this:
```yaml
libraries:
  Movies:
    library_type: movie
  TV Shows:
    library_type: show
```
the script would look for a `Movies.yml` file and a `TV Shows.yml` file in the same directory as your `config.yml`

Alternatively, You can specify exactly what you want the metadata file by using `metadata_path` under the specific library.
```yaml
libraries:
  Movies:
    library_type: movie
    metadata_path: /path/to/file/MyMovieConfig.yml
  TV Shows:
    library_type: show
```
