### DISCUSSION TITLE
Is it possible to have a conditional "IF" for my overlays?

### DISCUSSION THREAD

**Discussion by fmr-iv** [meisnate12/Plex-Meta-Manager#1162] [Q&A]
I'm using an overlay for IMDB rating that pulls from (audience_rating). I want to set it up so that if there isn't any (audience_rating) available for a movie then it uses (critic_rating) for the text overlay. Is this possible?

Here's my current ratingsoverlay.yml setup:
```
templates:
  ov:
    overlay:
      name: <<overlay_name>>
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/overlays/<<overlay_name>>.png
      group: <<g>>
      weight: <<w>>
      horizontal_offset: <<x>>
      vertical_offset: <<y>>
overlays:
# backdrop gradient to make overlays consistantly readable
  Gradient:
    template: { name: ov, g: gradient, w: 100, x: 0, y: 0 }
    plex_all: true
  IMDB_rating:
    plex_all: true
    template: { name: ov, g: charts, w: 1, x: 679, y: 1370 }
  critic_rating:
    plex_all: true
    overlay:
      name: text(audience_rating)
      horizontal_offset: 747
      vertical_offset: 1398
      font: fonts/Inter-SemiBold.ttf
      font_size: 52
      font_color: "#FFFFFF"
```
