### DISCUSSION TITLE
Is the reapply_overlay false respected?

### DISCUSSION THREAD

**Discussion by G4Zz0L1** [meisnate12/Plex-Meta-Manager#1177] [Q&A]
I've noticed that my runs are very long (almost 2 days each), but I've got a lot of thing in plex, so I thought it was normal.
Then I've noticed that each run all overlays get reapplied, no matter the value of the `reapply_overlay` variable.
Right now I've got the following:
```
overlay_path:
    - remove_overlays: false
    - reapply_overlay: false
    #- reset_overlays: plex
```
But the last run every movie and shows/season/episode (I've manually checked on the logs) has the overlay reapplied, even if the setting is false.
What am I doing wrong?
Why is it doing that?
