### DISCUSSION TITLE
How to delete all collections which are unmanaged *and* all collections with <2 items ?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1262] [Q&A] [answered]
Hi,

Coming from [here](https://github.com/meisnate12/Plex-Meta-Manager/discussions/1198).

How would I delete ALL collections with less than 2 items AND all collections which are not managed?
I can't understand the [wiki](https://metamanager.wiki/en/latest/config/operations.html#delete-collections) to do this.

I tried this, but got horrible errors because of duplucate keys.

```
libraries:
  Filme:
    library_name: Filme
    metadata_path:
    - file: config/mm-Filme-watchlist-only.yml
    operations:
      mass_collection_mode: hide
      delete_collections:
        managed: false
      delete_collections:
        less: 2
```

I tried this before, but it did not delete anything at all
```
libraries:
  Filme:
    library_name: Filme
    metadata_path:
    - file: config/mm-Filme-watchlist-only.yml
    operations:
      mass_collection_mode: hide
      delete_collections:
        managed: false
        less: 2
```

I'm stuck... 

Thank you

**Comment by meisnate12** [comment, marked as answer]
theres not currently a way in a single library run to delete collections that are managed or have less then 2 items you can only do both in a single run 
you can create a second PMM Library pointing to the same plex library and run only the other operation 

```yaml
libraries:
  Filme:
    metadata_path:
    - file: config/mm-Filme-watchlist-only.yml
    operations:
      mass_collection_mode: hide
      delete_collections:
        less: 2
  Filme (delete):
    library_name: Filme
    operations:
      delete_collections:
        managed: false
```
