### DISCUSSION TITLE
Special Characters cause asset search to fail

### DISCUSSION THREAD

**Discussion by JNR8** [meisnate12/Plex-Meta-Manager#1280] [Q&A]
### Version Number

1.18.3

### What branch are you on?

master

### Describe the Bug

When placing a poster in the assets folder for TMDB Collections to grab during processing the script fails back to using the URL poster instead of the file poster.  It seems that the Collection folder cannot be found because Collection Name (and therefore the collection folder in the Asset folder) contains a special character.  

For example: 
  Mission: Impossible Collection
  Family Guy Trilogy Collection: Laugh It Up, Fuzzball!

This problem does not present itself for Collections that do not contain special characters.  

### Relevant Collection/Overlay/Playlist Definition

```yml
dynamic_collections:
  TMDb Collections:          # This name is the mapping name
    type: tmdb_collection
```

### Logs

https://gist.github.com/jennec/501566a515eb8c0799cd6abcc891c389

**Comment by meisnate12** [comment]
So this is what the `name_mapping` Detail is for 

![image](https://user-images.githubusercontent.com/1631064/213722930-b193915a-c0d4-4a42-aee9-fd8706250781.png)

to do this in a dynamic collection you need to edit the template and pass in the proper name_mappings

See the [Franchise](https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/movie/franchise.yml) PMM Default for a complicated example of how it works but basically you need something like this

```yaml
templates:
  collection:
    optional:
      - name_mapping
    tmdb_collection_details: <<value>>
    minimum_items: 2
    name_mapping: <<name_mapping>>
dynamic_collections:
  TMDb Collections:
    type: tmdb_collection
    template: collection
    template_variables:
      name_mapping:
        1565: 28 Days-Weeks Later
        508334: Angels in the
        115838: Escape From
        386534: Has Fallen
        87359: Mission Impossible
        133352: Resident Evil Biohazard
        115575: Star Trek Alternate Reality
        115570: Star Trek The Next Generation
        151: Star Trek The Original Series
        10: Star Wars Skywalker Saga
```

**Comment by JNR8** [comment]
I have tried what you suggested, but in doing so the script now does not match any collection directories except for those listed in the name_mapping statement and reverts all of them back to the URL instead.  I was trying to avoid having to write out name mappings for every single collection dynamically created when items are added to the library.

**Reply by meisnate12** [reply]
my bad you need to make `name_mapping` optional or else the others not specified will literally look for `<<name_mapping>>`

```yaml
templates:
  collection:
    optional:
      - name_mapping
    tmdb_collection_details: <<value>>
    minimum_items: 2
    name_mapping: <<name_mapping>>
dynamic_collections:
  TMDb Collections:
    type: tmdb_collection
    template: collection
    template_variables:
      name_mapping:
        1565: 28 Days-Weeks Later
        508334: Angels in the
        115838: Escape From
        386534: Has Fallen
        87359: Mission Impossible
        133352: Resident Evil Biohazard
        115575: Star Trek Alternate Reality
        115570: Star Trek The Next Generation
        151: Star Trek The Original Series
        10: Star Wars Skywalker Saga
```
