### DISCUSSION TITLE
Combine duplicate collections, do not SKIP them (trakt liked lists)

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1293] [Ideas]
Hi,

so I have those 2 lists from different users with the same name:
https://trakt.tv/users/bogboy1978/lists/exploitation (Exploitation)  
https://trakt.tv/users/superpimp2g/lists/exploitation (Exploitation) 

and the log says 
`[2023-01-28 20:25:47,974] [meta.py:998]               [WARNING]  | Config Warning: Skipping duplicate collection: Exploitation                                                                                                                                            |
`

which is one way to deal with,

but I'd prefer a more user-supporting way ;-D

just combine those to lists to a collection named "Exploitation" (or whichever names the name-doublettes have)

I think that might be more useful than just skipping one of the list.

I have no idea how to do that, but it might be with an optional parameter given at the config
like this theoretical example:

```
templates:
  my-template4TraktLikedLists:
    trakt_list_details: <<value>>
    sort_title: +++06_1_<<collection_name>>
    collection_order: custom

dynamic_collections:
  Trakt Liked Lists:
    test: true
    what_to_do_with_those_name-doublettes: combine 
#   what_to_do_with_those_name-doublettes: skip 
#   skip would be the default, so no changes for all users which don't change this manually
    template: my-template4TraktLikedLists
    type: trakt_liked_lists
    data: me

```

Is this something, other users might find usefull too?

 I hope so, because 
 `title_override`  might be useful here too, but its cumbersome when you like many lists over a year or so and have to look at the log why some titles are missing in your collection (because of the skip). Then you have to go to the config again, create a title_overwrite and when you someday unlike the list, it will stay in the config forever, because you can't remember all your liked lists and which might have name-doublettes... ;-D

**Comment by YozoraXCII** [comment]
it is already possible to combine lists, see this example:

```
collections:
  Christmas:
    trakt_list:
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza
    sync_mode: sync
    ```
    
    https://metamanager.wiki/en/nightly/metadata/builders/trakt.html#trakt-list
