### DISCUSSION TITLE
IMDb Top 250 | Unknown Error: HTTPConnectionPool(redacted): Read timed out. (read timeout=60)

### DISCUSSION THREAD

**Discussion by Alex-Lee-Myers** [meisnate12/Plex-Meta-Manager#1313] [Q&A] [answered]
My IMDb Top 250 keeps erroring out continually, and it's my only error I'm running into _(aside from not having configured Trakt yet)_. Below is a log of that section that ends up erroring out. 

[imdbtop250log.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/10743683/imdbtop250log.txt)

**Comment by chazlarson** [comment, marked as answer]
First thing to try would be to extend the plex timeout in `config.yml`.  There's not much PMM can do about a timeout other than waiting longer.

```yaml
plex:
  url: http://192.168.1.12:32400
  token: ####################
  timeout: 60     #  <<< change this to a larger number
  clean_bundles: true
  empty_trash: true
  optimize: false
```
