### DISCUSSION TITLE
Content_rating not working

### DISCUSSION THREAD

**Discussion by jameshoyt** [meisnate12/Plex-Meta-Manager#132] [Q&A] [answered]
Hello, thank you for all the work on this project. I am setting up the template and I keep having issues with the content_rating value.

I'm thinking it may be related to the PlexAPI issue, but I wanted to make sure I wasn't just being dumb.

Here is the template I have setup: 
```
  Rating:
    plex_all: true
    filters:
      content_rating: <<content>>
    sort_title: 2222_<<collection_name>>
    file_poster: <<poster>>
    collection_order: alpha
    collection_mode: hide
```

Then here is where I call the template:
```
  G Rated Movies Collection:
    template: {name: Rating, content: G, poster: /mnt/file_path/g rated.jpg}
    summary: A collection of G rated Movies
```

When the script runs, it scans through all the movies but then pulls nothing in to the collection.

Thank you again for your help.

**Comment by meisnate12** [comment, marked as answer]
ok i think I've fixed this in develop if you wanna test

**Reply by jameshoyt** [reply]
I pulled the develop branch and it is pulling in the content_rating correctly now. 

I have 2 other questions if you don't mind.

 - How would I go about including multiple ratings? For instance, the below doesn't work for me.
 `  G Rated Movies Collection:
    template: {name: Rating, content: **G, TV-G** poster: /mnt/file_path/g rated.jpg}
    summary: A collection of G rated Movies`

 - Also, just out of curiosity how long does your template file take to run? Some of the lists take awhile to parse and I was wondering how long other's template files were taking.

Thank you again.

**Reply by meisnate12** [reply]
do 
```yaml
  G Rated Movies Collection: 
    template: {name: Rating, content: "G, TV-G", poster: /mnt/file_path/g rated.jpg}
    summary: A collection of G rated Movies
```
or 
```yaml
  G Rated Movies Collection: 
    template: {name: Rating, content: ["G", "TV-G"], poster: /mnt/file_path/g rated.jpg}
    summary: A collection of G rated Movies
```

and my run for just Movies take about 4-5 hours
