### DISCUSSION TITLE
Special Attributes: validate ? What does it do, what is is good for ?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1475] [Q&A] [answered]
<img width="709" alt="v" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/96403800/066f0339-9952-431c-8225-e739d03dd60b">

Searching the wiki for [validate](https://metamanager.wiki/en/latest/search.html?q=validate&check_keywords=yes&area=default) throws 2 hits, unfortunately without examples or usecase or anything I would understand what that attribute is good for.

Anyone here who can tell the exact purpose?

Thank you ;-)

**Comment by chazlarson** [comment]
This collection:

```
collections:
  validate-test:
    plex_search:
      all:
        any:
          genre: 
            - Family
            - Children
          any: 
            - content_rating: [U, PG]    
```
Fails when PMM attempts to validate it, and the collection doesn't get created.
```
|=============================== Validating validate-test Attributes ================================|
|                                                                                                    |
| Validating Method: smart_label                                                                     |
| Value: originally_available.desc                                                                   |
|                                                                                                    |
| Validating Method: plex_search                                                                     |
| Value: {'all': {'any': {'genre': ['Family', 'Children'], 'any': [{'content_rating': ['U', 'PG']}]}}} |
...
| modules.util.Failed: Plex Error: genre: Children not found                                         |
|                                                                                                    |
| Plex Error: genre: Children not found                                                              |
```
later in log:
```
|        Title         |   +   |   =   |   -   | Run Time | Status                                   |
|======================|=======|=======|=======|==========|==========================================|
| validate-test        |     0 |     0 |     0 |  0:00:00 | PMM Failure                              |
| Plex Error: genre: Children not found                                                              |
```

If, however, you set `validate: false`
```
collections:
  validate-test:
    plex_search:
      validate: false
      all:
        any:
          genre: 
            - Family
            - Children
          any: 
            - content_rating: [U, PG]    
```
Then PMM proceeds past that validation failure and creates the collection:
```
|=============================== Validating validate-test Attributes ================================|
|                                                                                                    |
| Looking for: validate-test                                                                         |
|                                                                                                    |
| Validating Method: smart_label                                                                     |
| Value: originally_available.desc                                                                   |
|                                                                                                    |
| Validating Method: plex_search                                                                     |
| Value: {'validate': False, 'all': {'any': {'genre': ['Family', 'Children'], 'any': [{'content_rating': ['U', 'PG']}]}}} |
| Plex Error: genre: Children not found                                                              |
| Plex Error: content_rating: U not found                                                            |
|                                                                                                    |
| Validating Method: url_poster                                                                      |
| Value: https://theposterdb.com/api/assets/168695                                                   |
|                                                                                                    |
| Validation Successful                                                                              |
```
later in log:
```
|        Title         |   +   |   =   |   -   | Run Time | Status                                   |
|======================|=======|=======|=======|==========|==========================================|
| validate-test        |     5 |     0 |     0 |  0:00:01 | Created and Updated Metadata, Image      |
```

**Reply by gitttt54** [reply, marked as answer]
Now THAT is an understandable and elaborately example, which I definately got in my mind! 

I wish, more of the examples in the wiki were at that great length.

Thank you very much !!

**Comment by gitttt54** [comment]
Just for others to know, here is an example to use:

I build smart collections for Record Labels for my music library.

Before knowing about the `validate` attribute, I had 3 different templates, like:

```
templates:
  Record_Label_1x:
    builder_level: album
    smart_filter:
      type: album
      sort_by: title.desc
      any:
        album_record_label.is: 
          - <<RL1>>
  Record_Label_2x:
    builder_level: album
    smart_filter:
      type: album
      sort_by: title.desc
      any:
        album_record_label.is: 
          - <<RL1>>
          - <<RL2>>
  Record_Label_4x:
    builder_level: album
    smart_filter:
      type: album
      sort_by: title.desc
      any:
        album_record_label.is: 
          - <<RL1>>
          - <<RL2>>
          - <<RL3>>
          - <<RL4>>
```
Each of them had a different amount of statements for the smart filter (_RL1_, _RL2_, _RL3_ and _RL4_):

Those templates were filled, each, with: 
```
collections:
  "New Identity Recordings":
    template: {name: "Record_Label_1x", RL1: "New Identity Recordings"}
  "Strictly Rhythm":
    template: {name: "Record_Label_2x", RL1: "Strictly Rhythm", RL2: "Strictly Rhythm UK"}
  "Bonzai":
    template: {name: "Record_Label_4x", RL1: "Bonzai", RL2: "Bonzai Records", RL3: "Bonzai Jumps", RL4: "Bonzai Trance Progressive UK"}
```
So I had 3 templates (_Record_Label_1x_, _Record_Label_2x_ and _Record_Label_4x_) which needed to be filled serperately.
Dependend of the Record Label needed to be build from 1, 2 or 4 different Recordlabels.

Now, with the fine help of `validate` (and @chazlarson) , I only need one single template, which can take all Recordlabes at once and therefore I only need to call that single template, not 3 different templates to get the same result.

```
templates:
  Record_Label:
    builder_level: album
    smart_filter:
      type: album
      sort_by: title.desc
      any:
        album_record_label.is: 
          - <<RL1>>
          - <<RL2>>
          - <<RL3>>
          - <<RL4>>
          - <<RL5>>
      validate: false

collections:
  "New Identity Recordings":
    template: {name: "Record_Label", RL1: "New Identity Recordings"}
  "Strictly Rhythm":
    template: {name: "Record_Label", RL1: "Strictly Rhythm", RL2: "Strictly Rhythm UK"}
  "Bonzai":
    template: {name: "Record_Label", RL1: "Bonzai", RL2: "Bonzai Records", RL3: "Bonzai Jumps", RL4: "Bonzai Trance Progressive UK"}
```

If I ever need 5 Record Labels, I just add them to the template (as in the example above) and to the call of the template.

Thats easy.
Thank you!  ;-D
