### DISCUSSION TITLE
Does PMM skip scheduled tasks if a prior task takes a long time?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1476] [Q&A]
Hi,

PMM runs in a docker container with
`PMM_TIME: 00:00,01:00,02:00,03:00,04:00,05:00,06:00,07:00,08:00,09:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,19:00,20:00,21:00,22:00,23:00`

Say, PMM starts at 05:00 and the first task takes 5 hours to complete,

are the tasks for 06:00,07:00,08:00,09:00,10:00 being skipped/suspended/append to the scheduling?

To me it seems that they are just skipped and if the 5 hour task is completed, PMM continutes with the tasks 11:00,12:00,13:00...

Anybody can tell me whats the case?

**Comment by chazlarson** [comment]
Skipped.  If a run takes longer than an hour there's no reason to tell PMM to run every hour.

**Comment by gitttt54** [comment]
>Skipped

Thank you.

>If a run takes longer than an hour there's no reason to tell PMM to run every hour.

I'm not sure, the way you see it is the only way which makes sense, but I'm glad to learn from your experience!

My PMM configuration is something like: 

-run every hour and do some minor tasks, such as watchist updates for all users.

-schedule some longer taking tasks (such as 1-10 minutes, but sometimes >1-2 hours) to run in the morning hours, so the PMS will not that much penetrated.

-schedule really long taking tasks (>4-20 hours) to run every week or month, because they're not needed up2date every day.

So I configured the docker conrainer to run every hour to be free to schedule every of these tasks (and new ones too) at any time I think it will be pleasant for the PMS and the users.

Don't know, if there is a "better" way to do...

**Comment by chazlarson** [comment]
If you are scheduling it to run once an hour, but some of those runs take longer than an hour, I'm not sure what you expect to happen.  If it stacked them up then PMM would probably never stop running.  I can't see how that makes any sense or what problem you're trying to solve by wanting it to stack up runs.

If you are using internal schedules to control what happens at various times of the day, then probably this doesn't work even if they got queued.

For example, if you have things set internally to run `hourly(6)` intending them to be part of the 06:00 run, then if you queued the 06:00 run and started it at 10 after the 5-hour 0500 run completed, those things won't happen anyway since `hourly(6)` no longer applies.

If those "missed" runs were queued, then those "4-20 hours" runs would stack up dozens of deferred runs.

**Comment by chazlarson** [comment]
```
are the tasks for 06:00,07:00,08:00,09:00,10:00 being skipped/suspended/append to the scheduling?
```
What are these "tasks" and how are they scheduled for those times?

**Comment by gitttt54** [comment]
>If you are scheduling it to run once an hour, but some of those runs take longer than an hour, I'm not sure what you expect to happen. 

I'm not really expecting, I'm asking to understand how PMM works to adept that to my configs.

Actually, sometimes, when I take a look at a running log, I see "Starting 06:00 Run" but the actual time is, say 11 o'clock. Thats why I was confused and asked. There is always a good chance, I did'nt understand something quite well, so I can't tell if its me, the config, or PMM ;-D The wiki is great, but sometimes its too much or too less information.

Anyways, thank you for the explanations!
It makes sense to me and I guess, I have to re-think my scheduling...

> ```
> are the tasks for 06:00,07:00,08:00,09:00,10:00 being skipped/suspended/append to the scheduling?
> ```
> 
> What are these "tasks" and how are they scheduled for those times?

At this time the short watchlist tasks should run.
```
libraries:
  Filme:
    library_name: Filme
    metadata_path:
    - file: config/mm-Filme-watchlist-only.yml   # takes <5 minutes
    - file: config/mm-Filme-admin.yml.           # takes 1-10 minutes, sometimes more
    - file: config/mm-Filme-flixpatrol.yml       # havent measured yet, I guess its <5 minutes each 
      schedule: hourly(4)
    - file: config/mm-Filme.yml                  # between 10 minutes and 1-2 hours
      schedule: hourly(5)
    - file: config/mm-Filme-dynamic_collections.yml # takes veeeeery looong, so I change that to weekly()
      schedule: hourly(5)
```
