### DISCUSSION TITLE
How to change Artist sort_title, when there are more that 1 Artist with same name?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#1479] [Q&A]
Hi,
from the [Music Library Metadata Wiki](https://metamanager.wiki/en/latest/metadata/metadata/music.html) I found, that I can alter metadata for artists, like sort title and artist art.

This is what I'd like to do for artist(s) "Cyrus" and some other artists, wich have the same name but are different people or bands. Plex unfortunately mixes up the images and bio for artists with same name in some cases.

Plex Music Library has several Artists with that name, like:
<img width="310" alt="Bildschirmfoto 2023-06-25 um 07 11 43" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/96403800/ac44bcca-06e1-4257-87eb-89436eb036ee">

How would I select one of them via PMM?

How would I select all of them and point out the correct one ?

I guess I have to create a new library for artists?  because my other library has type album set up.

I could need some examples and guide how to accomplish this.

Thank you.

```
libraries:
  Musik_Artists:
    library_name: Musik
    -type: artist 
    metadata_path:
    - file: config/mm-Musik-admin.yml
    metadata:
      "Cyrus":
        # https://www.discogs.com/artist/579-Cyrus
        alt_title: "Cyrus Basic Channel"
        sort_title: "!Cyrus Basic Channel"
        url_poster: "https://i.discogs.com/CL6-Di88P9Q606mMfc8Ie4QEN2WX6_qeEcvVMR9VDT8/rs:fit/g:sm/q:90/h:205/w:270/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTU3OS0x/NTEzNjY3MTMwLTQ4/MzcuanBlZw.jpeg"
    
      "Cyrus":
        # https://www.discogs.com/artist/669685-Cyrus-9
        alt_title: "Cyrus (Random Trio)"
        sort_title: "!Cyrus (Random Trio)"
        url_poster: "https://i.discogs.com/qRe3qc9e2G9gZJOovs5WW8zxE8V4cLieWYWqfncbQsM/rs:fit/g:sm/q:90/h:366/w:352/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTY2OTY4/NS0xNTgxNjE5OTI5/LTU4MjUucG5n.jpeg"
    
      "Cyrus":
        # https://www.discogs.com/artist/488651-Cyrus-8
        alt_title: "Cyrus Scott"
        sort_title: "!Cyrus Scott"
        url_poster: "https://i.discogs.com/k9lpbq3m3IvleUI44s-rf1CKRSdo4VQU8l11MiI4yEM/rs:fit/g:sm/q:90/h:536/w:464/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9BLTQ4ODY1/MS0xNjAzMjYzMjM4/LTg5NjEuanBlZw.jpeg"
    

```
