### DISCUSSION TITLE
Any way to create overlay templates for libraries?

### DISCUSSION THREAD

**Discussion by ChristianStrawn** [meisnate12/Plex-Meta-Manager#1487] [Q&A] [answered]
I thought I could do something like this since I have a ton of libraries:
```
libraries:

  Movies:
    metadata_path:
      - file: config/assets/Metadata/Videos/Movies.yml
    radarr:
      root_folder_path: /media/media/media/Videos/Movies
    overlay_path:
      - file: config/ov_basic.yml
      - file: config/ov_lang_audio.yml
```

ov_basic.yml:
```
overlay_path:
  - pmm: resolution
    template_variables:
      use_edition: false
      use_1080p: false
      use_720p: false

  - pmm: flixpatrol

  - pmm: commonsense
    template_variables:
      - use_nr: false

  - pmm: language_count

  - pmm: episode_info

  - pmm: streaming

  - pmm: ratings
    template_variables:
      rating1: critic
      rating2: audience
      rating3: user
      rating1_image: imdb
      rating2_image: rt_popcorn
      rating3_image: tmdb

    operations:
      mass_content_rating_update: mdb_commonsense
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
```
