### DISCUSSION TITLE
Add multiple flixpatrol_url

### DISCUSSION THREAD

**Discussion by stevezau** [meisnate12/Plex-Meta-Manager#1620] [General]
Hi,

I want to pull the top 10 from Flixpatrol for a couple of networks in AU and USA. 

I want them all in the same "Top TV Today" collection.

I.e. I want to do something like the following.

```
collections:
  Top Movies Today:
    flixpatrol_top:
      - platform: netflix
         location: united_states
         time_window: this_month
         limit: 20
      - platform: netflix
         location: australia
         time_window: this_month
         limit: 20
```

But it appears the config does not support multiple "flixpatrol_top". Any suggestions on how I can achieve the above?
