### DISCUSSION TITLE
Override/Extend IMDB Lists for Seasonal Collections

### DISCUSSION THREAD

**Discussion by webdes03** [meisnate12/Plex-Meta-Manager#1714] [General]
I've tried using the `append_data` option to the seasonal collections and I can't get this to work. Basically, I want to add my own IMDB lists to the existing ones, something like this:

```
metadata_path:
  - pmm: seasonal
    use_separator: false
    template_variables:
      emoji: ""
      visible_home: true
      visible_shared: true
      delete_not_scheduled: true
      exclude:
        - aapi
        - disabilities
        - latinx
      append_data:
        thanksgiving:
          imdb_list:
            - https://www.imdb.com/list/ls086366598/
            - https://www.imdb.com/list/ls086453555/
            - https://www.imdb.com/list/ls566513280/
            - https://www.imdb.com/list/ls082083511/
```

Is something like this possible without having to just completely replace the default files?

**Comment by webdes03** [comment]
And of course, I figured it out right after I posted, so for anyone who finds this later...

```
metadata_path:
  - pmm: seasonal
    use_separator: false
    template_variables:
      emoji: ""
      visible_home: true
      visible_shared: true
      delete_not_scheduled: true
      exclude:
        - aapi
        - disabilities
        - latinx
      imdb_list_thanksgiving:
        - https://www.imdb.com/list/ls000835734/
        - https://www.imdb.com/list/ls091597850/
        - https://www.imdb.com/list/ls086366598/
        - https://www.imdb.com/list/ls086453555/
        - https://www.imdb.com/list/ls566513280/
        - https://www.imdb.com/list/ls082083511/
```
