### DISCUSSION TITLE
overlay_path template_varibles and report_path for missing

### DISCUSSION THREAD

**Discussion by DaydreamHero** [meisnate12/Plex-Meta-Manager#1752] [Q&A] [answered]
I must be missing something, but I can't figure out what. I have two issues, and I can't seem to find anything in the Q&A of other people having the issues, so I don't know. I have the following my config.yml:

```
libraries:                                                               
  Movies:                                                                
    report_path: config/missing/movies.yml                               
    metadata_path:                                                       
    - file: config/movies.yml                                            
    - pmm: basic                                                         
    - pmm: imdb                                                          
    overlay_path:                                                        
    - remove_overlays: false                                             
    - pmm: ratings                                                       
        template_variables:                                             
          rating1: user                                                 
          rating1_image: rt_tomato                                      
          rating1_font: config/custom_fonts/adlib.ttf                   
          rating1_font_size: 63                                         
                                                                        
          rating2: critic                                               
          rating2_image: imdb                                           
          rating2_font: config/custom_fonts/impact.ttf                  
          rating2_font_size: 70                                         
                                                                        
          rating3: audience                                             
          rating3_image: tmdb                                           
          rating3_font: config/custom_fonts/metropolis-bold.otf         
          rating3_font_size: 70                                         
                                                                        
          horizontal_position: right                                    
    - pmm: ribbon                                                        
    operations:                                                          
      mass_user_rating_update: mdb_tomatoes                              
      mass_critic_rating_update: imdb                                    
      mass_audience_rating_update: tmdb                                  
```
When the overlay_path information is in there I receive the following error:
`YAML Error: mapping values are not allowed here in "//config/config.yml", line 8, column 27`
I can't figure out what it wants from me? I had to comment out the template_variables to keep PMM running, but how do I get them to work? [I feel like what I have basically matches the sample from https://metamanager.wiki/en/latest/defaults/overlays.html (aside from the third font.]

The other issue, has to do with line 3 from the config. Am I supposed to create that YAML file, and if so can someone point me to what it should look like? I added this line at the same time as the template_variable stuff and obviously am not having the best of luck. Thanks in advance.

**Comment by chazlarson** [comment, marked as answer]
The error you have there typically indicates indentation problems in the `config.yml`.

If I paste what you have there into yamllint.com, it guides me to this change:
```yaml
libraries:                                                               
  Movies:                                                                
    report_path: config/missing/movies.yml                               
    metadata_path:                                                       
    - file: config/movies.yml                                            
    - pmm: basic                                                         
    - pmm: imdb                                                          
    overlay_path:                                                        
    - remove_overlays: false                                             
    - pmm: ratings                                                       
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/custom_fonts/adlib.ttf
        rating1_font_size: 63

        rating2: critic
        rating2_image: imdb
        rating2_font: config/custom_fonts/impact.ttf
        rating2_font_size: 70

        rating3: audience
        rating3_image: tmdb
        rating3_font: config/custom_fonts/metropolis-bold.otf
        rating3_font_size: 70

        horizontal_position: right
    - pmm: ribbon
    operations:
      mass_user_rating_update: mdb_tomatoes
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
```
Note the indentation change on the template_variables section.

similarly, VS Code, which is YAML-aware, points to the error:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/f1c68769-b40c-4d64-9d4f-2c2674a9cd57)

And is happy when I outdent that section:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/92bfbace-73b8-48d1-be23-bc8605cede08)
