### DISCUSSION TITLE
Ignore specific folders/items when creating overlays

### DISCUSSION THREAD

**Discussion by jfinelt** [meisnate12/Plex-Meta-Manager#1766] [Q&A]
Hello, 
I have some fan edits of TV shows with custom posters that are not matched to any existing shows. These files exist in the same plex library as files I would like pmm to scan, and I would like to either have pmm ignore them entirely or put a custom poster in instead of generating a new (incorrect) one. I am currently implementing overlays only at the season level and would like to continue that.  I wasn't able to access the discord so any help is greatly appreciated!

Example of current folder structure:
``` 
media                         
   TV				#plex library points to this
      FanEdit			#fan edit, if possible ignore everything in this folder
         Season01		#don't create new overlay poster (or use the "season01.png" file)
            s01e01.mkv
            s01e02.mkv
            season01.png	#custom poster to keep      
         Season02		#don't create new overlay poster (or use the "season02.png" file)
            s02e01.mkv
            s02e02.mkv
            season02.png	#custom poster to keep   
         show.png		#poster for entire show, no overlay
      Regular TV Show		#popular TV show with match
         Season01		#pmm to create overlay poster
            s01e01.mkv
            s02e02.mkv
         Season02		#pmm to create overlay poster
            s02e01.mkv
            s02e02.mkv
```

My current PMM Settings section in config.yml
```
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: false
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: false
  create_asset_folders: false
  collection_minimum: 1
  delete_below_minimum: false
  tvdb_language: default
  show_missing_assets: true
  asset_depth: 0
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  default_collection_order:
  item_refresh_delay: 0
  delete_not_scheduled: false
  only_filter_missing: false
  show_unconfigured: true
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: true
  custom_repo:
  check_nightly: false
```

Thanks

**Comment by jfinelt** [comment]
It seems like "assets" may be a solution, but I can't figure out how to properly implement and am looking for some guidance.

1. How do I properly point to an asset directory, is it literally: 
```
settings:
   asset_directory:
      - path/to/assets
   asset_folders: true
```
with a file structure similar to this? [https://metamanager.wiki/en/latest/home/guides/assets.html#asset-folders-asset-folders-true](url)

2. to enable assets, i just add this under each library I want it to apply to like this? or would that go under the `settings` section?
```
libraries:
  Movies Test:
    operations:
        assets_for_all: true
    metadata_path:
      -file:config/movies.yml
    overlay_path:
      - remove_overlays: false
      - reapply_overlay: false
      - pmm: resolution                                                      # 1, 4
      - pmm: audio_codec                                                     # 2
````
