### DISCUSSION TITLE
Multiple "imdb_search" in nightly branch

### DISCUSSION THREAD

**Discussion by ghost** [meisnate12/Plex-Meta-Manager#1769] [Q&A]
With the new addition of "imdb_search" in the nightly branch, I am querying if there is a method to have multiple searches, just as how there can be multiple lists for a collection. The attempts that I have done, show an error with duplicate key or overrides the main search.

This is the configuration used:

```
## 0_debug.yml

templates:
  sub_genre:
    optional:
      - imdb_extra_1
      - imdb_extra_2
      - imdb_extra_3
      - imdb_extra_4
      - imdb_extra_5
      - letterboxd_extra_1
      - letterboxd_extra_2
      - letterboxd_extra_3
      - letterboxd_extra_4
      - letterboxd_extra_5
    sort_title: "+7 Rated: <<collection_name>>"
    limit: 200
    sync_mode: sync
    collection_order: critic_rating.desc
    collection_mode: hide
    visible_home: false
    visible_shared: false
    visible_library: false
    delete_not_scheduled: false
    cache_builders: 6
    imdb_search:
      type: <<type>>
      genre: <<genre>>      
      keyword: <<keyword>>
      sort_by: rating.desc
      rating.gte: <<rating.gte>>
      votes.gte: <<votes.gte>>
      language: <<language>>
      limit: 10
    letterboxd_list:
      - https://letterboxd.com/ediblehedgehog/list/<<letterboxd_list>>/
      - <<letterboxd_extra_1>>
      - <<letterboxd_extra_2>>
      - <<letterboxd_extra_3>>
      - <<letterboxd_extra_4>>
      - <<letterboxd_extra_5>>

collections:
  "_DEBUG":
    summary: "_DEBUG"
    url_poster: 
    template: {
                    name: sub_genre,
                    keyword: "boxing",
                    genre: "",
                    type: "movie,tv_movie",
                    rating.gte: 2,
                    votes.gte: 100,
                    languages: "en",
                    letterboxd_list: "theme-boxing",
                    letterboxd_extra_1: "https://letterboxd.com/akookieforyou/list/chick-flicks/",
                    letterboxd_extra_2: "https://letterboxd.com/marialuisacctc/list/women-have-superior-taste-that-is-why-these/",
                    }
    imdb_list:
      url: https://www.imdb.com/list/ls066069214
      limit: 10
    imdb_search:
      type: "movie,tv_movie"
      keyword: "boxing-champion"
      sort_by: rating.desc
      rating.gte: 2
      votes.gte: 100
      language: en
      limit: 10
    imdb_search:
      type: "movie,tv_movie"
      keyword: "cars"
      sort_by: rating.desc
      rating.gte: 2
      votes.gte: 100
      language: en
      limit: 10

```

**Comment by chazlarson** [comment]
Seems like this is what `keyword.any` is for.

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/5a7ffcec-9bef-4462-ab2b-3c3ca5a3dabe)

```
imdb_search:
      type: "movie,tv_movie"
      keyword.any: "boxing-champion, cars"
      sort_by: rating.desc
      rating.gte: 2
      votes.gte: 100
      language: en
      limit: 10
```

**Reply by ghost** [reply]
Yes, that would work if only keywords were the variables as in the configuration.

In other instances, there are multiple variables that necessitate independent searches. I am interested in doing this.

**Reply by chazlarson** [reply]
Many of the variables in the search seem to allow multiple values.  If there are specific ones that don't which you feel should, perhaps a feature request?

I suppose there's no allowance for multiple exclusive values, so perhaps a feature request for that, if the desire is to do this sort of thing:
```
  imdb_search:
    - type: "movie,tv_movie"
      keyword: "boxing-champion"
      rating.gte: 2
      votes.gte: 100
      language: en
      limit: 10
    - type: "tv_movie"
      keyword: "cars"
      rating.gte: 8
      votes.gte: 792
      language: de
      limit: 100
```
