### DISCUSSION TITLE
PMM stuck at "Loading All Movies from Library"

### DISCUSSION THREAD

**Discussion by DANW999** [meisnate12/Plex-Meta-Manager#1775] [General]
When starting PMM, it seems to get stuck at "Loading All Movies from Library" for the Films library on the one I have labelled Movies_on_Main_Plex and never get past it. My config file below connects to two plex instances. I am not sure if I have done anything wrong at all?

```
######### API Config #########
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: URL
  token: TOKEN
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                            # REQUIRED for the script to run
  apikey: APIKEY
  language: en

######### Config Locations #########
libraries:                       # This is called out once within the config.yml file
  Films:                        # These are names of libraries in your Plex
    metadata_path:
      - folder: /config/Movies
      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_path:
      - remove_overlays: false   # Set this to true to remove all overlays
  TV shows:
    metadata_path:
      - folder: /config/TVShows
#      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_path:
      - remove_overlays: false   # Set this to true to remove all overlays
#      # see the wiki for how to use local files, folders, URLs, or files from git
#playlist_files:
#  - folder: /config/Playlists
#    template_variables:
#      libraries: Movies, TV Shows   # list of libraries that you want the PMM Defaults playlists to look at
#  # see the wiki for how to use local files, folders, URLs, or files from git
  Movies_on_Main_Plex:
    library_name: Films
    metadata_path:
      - folder: config/Movies
    plex:
      url: URL
      token: TOKEN
    timeout: 60
    db_cache:
    clean_bundles: false
    empty_trash: false
    optimize: false
  TVShows_on_Main_Plex:
    library_name: TV shows
    metadata_path:
      - folder: config/TVShows
    plex:
      url: URL
      token: TOKEN
    timeout: 60
    db_cache:
    clean_bundles: false
    empty_trash: false
    optimize: false

######### Settings #########
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
```
