### DISCUSSION TITLE
How do you specify config overrides per library?

### DISCUSSION THREAD

**Discussion by tehniemer** [meisnate12/Plex-Meta-Manager#178] [Q&A] [answered]
I see many `# Can be individually specified per library as well` entries in the example config, but I can't find anything in the Wiki explaining exactly how to do this. I'd like to override the sonarr `root_folder_path` in my show libraries, but can't figure it out.

**Comment by meisnate12** [comment, marked as answer]
You can set it up just like the alternate `plex` attribute is set up in the second example on this [page](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Libraries-Attributes)
```yaml
libraries:
  TV Shows:
    library_type: show
  4K TV Shows:
    library_type: show
    sonarr:
      url: http://192.168.1.12:1598
      token: ####################
      # Other Sonarr settings...
  TV Shows:
    library_type: show
  Anime:
    library_type: show
sonarr:
  url: http://192.168.1.12:1597
  token: ####################
  # Other Sonarr settings...
```

it will use the global value unless the value is specified per library
