### DISCUSSION TITLE
PLex Error: studio: Marvel Enterprise not found.  Script aborts?

### DISCUSSION THREAD

**Discussion by douginoz** [meisnate12/Plex-Meta-Manager#180] [Q&A] [answered]
My Movies.yml includes:

```
templates:
    Studio:
        plex_search:
          studio: <<studio>>
        url_poster: <<poster>>
        sort_title: +++++_<<collection_name>>
        collection_order: alpha
collections:
  Marvel Cinematic Universe:
    template: {name: Studio, studio: "Marvel Enterprise, Marvel Entertainment, Marvel Studios", poster: https://theposterdb.com/api/assets/5912}
    summary: blah
```
But when run:

`python3 plex_meta_manager.py --config config/config.yml --run --collections "Marvel Cinematic Universe"`

terminates with:
```
|====================================================================================================|
|                                Marvel Cinematic Universe Collection                                |
|====================================================================================================|
|                                                                                                    |
| Scanning Marvel Cinematic Universe Collection                                                      |
| Plex Error: studio: Marvel Enterprise not found                                                    |
|                                                                                                    |
|====================================================================================================|
|                                      Finished Collections Run                                      |
|                                         Run Time: 0:00:43                                          |
|====================================================================================================|
```

I can work out that this means that Plex doesn't have any movies with a studio value of "Marvel Enterprise" _currently_, but should this cause the script to just stop?  I have all the current Marvel movies in Plex and all the other collections are created except the MCU one, which I assume is because of this error.
Is there a way to tell it to continue despite it not finding that value?
