### DISCUSSION TITLE
Collection and Metadata files

### DISCUSSION THREAD

**Discussion by braydin72** [meisnate12/Plex-Meta-Manager#1811] [Q&A] [answered]
What if my current setup has both collection and metadata entries in a single file. Do I need to split them (YUCK) or add them twice or will it just run them.

**Comment by YozoraXCII** [comment, marked as answer]
If a YAML file contains both, then place it within both:

```yml
libraries:
  Movies:
    collection_files:
      - file: config/myfile.yml
    metadata_files:
      - file: config/myfile.yml
```

You can split it if you'd like, but seems you don't want to do that :)
