### DISCUSSION TITLE
Only add movies to a collection after <date>?

### DISCUSSION THREAD

**Discussion by douginoz** [meisnate12/Plex-Meta-Manager#183] [Q&A] [answered]
Not sure how to phrase this.  I'm using someone's Movies.yml and modifying to suit.  Currently, there is a "Studio" template for Pixar, or Ghibli, etc.   By default, all movies for these are flagged. I'm in the process of modifying it so that I can decide if a particular studio will get flagged for download:

```
Template:
    Studio:
        plex_search:
          studio: <<studio>>
        url_poster: <<poster>>
        sort_title: +++_<<collection_name>>
        collection_order: release
        radarr_add: radarr
Collection:
  Studio Ghibli:
    template: {name: Studio, studio: "Studio Ghibli", poster: https://theposterdb.com/api/assets/32223, radarr: false}

```
(I haven't tested the above yet so it may not yet be correct).
My problem is that either I allow it to flag/download everything or nothing.  For Pixar for example, there are >100 small movies that simply don't exist "out there" and I don't want to fill up my Radarr config with these, and have Radarr constantly looking for them because they're not likely to ever appear.  Same with Ghibli.

However, if I set 'radarr: false' (or however I disable flagging/downloading), then >nothing< will ever get added to this collection in the future.  So this/next year's blockbuster Pixar movie won't get added.

Is there a way to have my cake and eat it, too?  To not bother trying to add all these old/missing/unwanted movies to Radarr, but still have it do so for anything in the future?

**Comment by meisnate12** [comment, marked as answer]
so to start for `radarr: false` to work in the template you need to add `<<` and `>>` around the variable so this `radarr_add: radarr` becomes this `radarr_add: <<radarr>>`

you can limit your results by using the `tmdb_vote_count.gte` filter like this
you could add a filter like this 
```yaml
Collection:
  Studio Ghibli:
    template: {name: Studio, studio: "Studio Ghibli", poster: https://theposterdb.com/api/assets/32223, radarr: false}
    filters:
      tmdb_vote_count.gte: 100   # this will filter the results to only those that have 100 or more votes on tmdb
```
you can add the filters to the template or to each collection individually.

adjust the value of `tmdb_vote_count.gte` to be more or less restrictive

`tmdb_vote_count.gte` is the only filter that will also filter radarr results

I could add a date filter that will also filter radarr movies but it filters the whole collection so if you have older movies you want in the collection but you don't want to send any new older ones to radarr then that solution wouldn't work
