### DISCUSSION TITLE
If parameter isn't provided to a template, is it ignored?

### DISCUSSION THREAD

**Discussion by douginoz** [meisnate12/Plex-Meta-Manager#186] [Q&A] [answered]
```
templates:
    Studio:
        plex_search:
          studio: <<studio>>
        url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: release
collections:
 Aardman:
    template: {name: Studio, studio: "Aardman Animations"}
```
If url_poster isn't included in the line 
`
template: {name: Studio, studio: "Aardman Animations"}`

Q1: Will the existing poster for the Aardman collection get overwritten/removed?
Q2: If I use the assets folder (config/assets/Aardman/poster.jpg), will this file automatically get added/set to active in Plex for this collection, even if something else is currently active?

Background:  I was having problems with including the poster url in the template line:

    template: {name: Studio, studio: "Aardman Animations", poster: https://blah/file.png}

What seemed to be happening is that nothing woud get returned/set in Plex until I manually viewed the poster in my web browser, and then only some of these seemed to appear.   I couldn't spend time debugging it as I have a couple of dozen that needed fixing so I'm hoping to use the workaround of keeping poster files in the config/assets folder.  I just need to know if they are always used and always checked each time PMM is run.

**Comment by meisnate12** [comment, marked as answer]
the assets folder is checked with each run.
you can have optional variables and they can have defaults as well.
The `optional` attribute and `default` attribute are about half way down this [page](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Template-Attributes).
Let me know if your still having trouble

**Comment by douginoz** [comment]
Awesome.  That fixed it:
```
templates:
    Studio:
        plex_search:
          studio: <<studio>>
        optional:
          url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: release
collections:
  DC Extended Universe:
    template: {name: Studio, studio: "DC Extended Universe"}

```
when run, produces:
```
| Scanning DC Extended Universe Collection                                                           |
|                                                                                                    |
| Sync Mode: append                                                                                  |
|                                                                                                    |
| Processing Plex Search: studio(DC Extended Universe)                                               |
| DC Extended Universe Collection | = | Wonder Woman 1984                                            |
| 1 Movie Processed                                                                                  |
|                                                                                                    |
| Detail: summary updated Collection Summary                                                         |
| Detail: sort_title updated Collection Sort Title to +++++++_DC Extended Universe                   |
| Detail: collection_order updated Collection Order to release                                       |
| Details: have been updated                                                                         |
| Detail: asset_directory updated collection poster to [File] /opt/Plex-Meta-Manager/config/assets/DC Extended Universe/poster.jpg |
|                                                                                                    |
| No background to update                                                                            |

```

However, taking a step back, if I don't have any movies in Plex with a studio value of "DC Extended Universe", and no existing collection of that name, the following disaster starts to happen:
```

|====================================================================================================|
|                                     Movies Library Collections                                     |
|====================================================================================================|
|                                                                                                    |
|====================================================================================================|
|                                  DC Extended Universe Collection                                   |
|====================================================================================================|
|                                                                                                    |
| Scanning DC Extended Universe Collection                                                           |
| Plex Error: studio: DC Extended Universe not found                                                 |
| Collection Warning: No valid studio values found in DC Extended Universe                           |
|                                                                                                    |
| Sync Mode: append                                                                                  |
|                                                                                                    |
| DC Extended Universe Collection | + | The 'High Sign'                                              |
| DC Extended Universe Collection | + | 1 Chance 2 Dance                                             |
| DC Extended Universe Collection | + | １リットルの涙                                                      |
| DC Extended Universe Collection | + | 2 Fast 2 Furious                                             |
| DC Extended Universe Collection | + | 2 Guns                                                       |
| DC Extended Universe Collection | + | 2 ou 3 choses que je sais d'elle                             |
| DC Extended Universe Collection | + | 2.0                                                          |
| DC Extended Universe Collection | + | 3 from Hell                                                  |
| DC Extended Universe Collection | + | 3, 2, 1... Frankie Go Boom                                   |
| DC Extended Universe Collection | + | 3:10 to Yuma                                                 |
| DC Extended Universe Collection | + | The 5th Wave                                                 |
```
I have to abort it at some point.  The movies listed are every single movie in Plex.

**Reply by douginoz** [reply]
To reproduce:
Refresh Plex in the browser to ensure that no 'DC Extended Universe' collection exists in my "Movies" collection view.  ALso make sure no "DC Extended Universe" studio exists in any Plex movies, although I assume it's easier to just change the studio value in:
```
  DC Extended Universe:
    template: {name: Studio, studio: "DC Extended Universe"}

to something random that doesn't exist.

```
Run PMM.  Config files attached.

Ubuntu 20.04 
PMM 1.7.1


[douginoz_configs.zip](https://github.com/meisnate12/Plex-Meta-Manager/files/6275457/douginoz_configs.zip)

**Reply by meisnate12** [reply]
so this isnt quite right it should look like this 
```yaml
templates:
    Studio:
        plex_search:
          studio: <<studio>>
        optional:
          - poster
        url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: release
collections:
  DC Extended Universe:
    template: {name: Studio, studio: "DC Extended Universe"}
```

**Reply by douginoz** [reply]
Ok, made that change, but still the same result.  It's currently adding several thousand movies to the DC EU collection...
```

    Studio:
        plex_search:
          studio: <<studio>>
        optional:
          - poster
        url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: release
```
