### DISCUSSION TITLE
collection_mode is undocumented but works

### DISCUSSION THREAD

**Discussion by douginoz** [meisnate12/Plex-Meta-Manager#196] [Ideas]
By default, my new collections appear in my Plex library main screen.  I only want them to appear under 'Collections', so I manually modify each one's advanced configuration field "Collection Mode" to "Hide Collection".
I didn't find anything mentioned about this in the wiki but I found that it works:

```
  Romantic Comedy:
    imdb_list:
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=romance,comedy
      limit: 200
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=romance,comedy&>
      limit: 200
    sort_title: +++_Romantic Comedy
    sync_mode: sync
    summary: "Love is patient; love is kind. It’s also awkward, messy and really funny. These romantic comedies rank as our top movies to help you feel>
    collection_order: alpha
    collection_mode: hide
    filters:
      genre: Comedy

```
Setting 'collection_mode' to "hide" = "hide collection" in the Plex settings.
Note that you have to refresh your Plex screen to see them take effect.
