### DISCUSSION TITLE
Does PMM really not support Season/Episode numbers with more than two digits?

### DISCUSSION THREAD

**Discussion by OttoWerse** [meisnate12/Plex-Meta-Manager#1975] [Q&A]
I am trying to apply episode Artwort using PMM, but no matter what I do, it just seems to be unable to do so. 
First I enabled "create_asset_folders" to know exactly where to put my images. 
I named my image "S2024E099.png" and put it in the PMM created folder "config\assets\Doug DeMuro - Other" 
Now I want it to be applied to the corresponding episode "Doug DeMuro - Other - S2024E099.mp4" in my Plex folder structure under "Plex\YouTube\Doug DeMuro - Other\Season 2024" 
However, running PMM I only get a message "No Item Edits". 

Then I shortened the Season and Episode bit in all file names to "S24E99" (and let Plex re-scan the file, of course). 
Now PMM was immediately able to apply my asset to the episode. 
However, this is a non-solution to my original problem, as I do actually need the extra digits, I cannot just shorten all my filenames. 

So, what else do I need to set or consider before updating episode assets for 4-digit seasons and/or 3-digit episodes can work? 
Or is this just really not supported by PMM at all? If so, why? 

My Config looks like this: 
```
libraries:
  YouTube:
    operations:
      assets_for_all: true
    settings:
      show_missing_assets: false
    collection_files:
    - file: config/youtube.yml
    reapply_overlays: false

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: 
  - config/assets
  create_asset_folders: true
  asset_folders: true
  asset_depth: 0
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
```

**Comment by YozoraXCII** [comment]
PMM does support asets with more than two digits:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/80060e6d-ae71-44a3-b6a8-87892c9e55d3)

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/4733f695-bb5e-468c-bc7a-418257eaa871)

The problem is that `S01E099` is not the same as `S01E99`. My guess is that PMM is matching based on the Plex episode number (`99`) rather than the filename number (`099`)

**Reply by chazlarson** [reply]
That's exactly what it's doing.

PMM Is basing the asset search on the season and episode numbers reported by Plex, nothing to do with the file name.

Given this episode:

![Screenshot 2024-04-15 at 8 47 33 AM](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/89ae0992-9c2f-4a07-91b7-20d046765d21)

found at filename:
```
/mnt/local/Testing/Some-Shows/EastEnders (1985) {tvdb-71753}/Season 39/EastEnders (1985) - 2023-12-28 - 28+12+2023 - [ WEBDL-1080p h264 AAC 2.0 ]-iPLAYER.mp4
```
Note that filename contains no season or episode info at all.

I created this asset in `config/assets`:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/8f92a0bf-52c3-4c3d-a08c-15d473be8e4d)

Note it has a three-digit episode number.

Then ran this config:
```
libraries:
  Some-Shows:
    operations:
      assets_for_all: true

settings:
  asset_directory: config/assets
  asset_folders: true
  prioritize_assets: true
  create_asset_folders: true
  asset_depth: 0
  dimensional_asset_rename: true
  download_url_assets: true
  show_missing_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false

```

With this result:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/60d537ca-f5a4-4f09-aaee-d8394aa604d3)

Or with a four-digit season and three-digit episode:

![Screenshot 2024-04-15 at 10 18 41 AM](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/9f277ff9-2ffa-492b-964f-d8b712ddfc31)

file:
```
/mnt/local/Testing/Some-Shows/@midnight (2013) {tvdb-274099}/Season 2017/@midnight (2013) - 2017-08-04 - Series Finale - [ WEBDL-1080p x264 AAC 2.0 ]-monkee.mkv
```
Again no season or episode in the filename.

Created this asset:
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/15ca02ca-fcc9-456f-a7ba-c1259ec3562e)

Ran the same config as above with this result:
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/e4aca2cb-8d0a-4085-a090-bc19eab33b74)
