### DISCUSSION TITLE
Font color in Overlay: Status

### DISCUSSION THREAD

**Discussion by sabonim38** [meisnate12/Plex-Meta-Manager#1984] [Q&A]
I'm trying to add different color to TV Shows status overlay. I'm a bit new to it, so I have tried by fooling around...

    - pmm: status
      template_variables:
        horizontal_align: center
        vertical_align: bottom
        font_color: '#f97f00'

I have been able to change the font color for ALL status with the above one. But I would like to have different color for airing, returning, cancelled and ended.

I have tried a lot of different things, but I haven't been able to make it work. So far I think I have tried all version, I think think of, so I'm not even sure it's possible:

text_airing:
   -font_color: '#f97f00'

font_color_airing: '#f97f00'

font_color_text_airing:: '#f97f00'

font_color: '#f97f00'
 - text_airing

Anyone have an idea, how to do it?

**Comment by chazlarson** [comment]
```
libraries:
  Some-Shows:
    overlay_files:
    - pmm: status
      template_variables:
        horizontal_align: center
        vertical_align: bottom
        font_color_airing: "#FF0000"
        font_color_returning: "#00FF00"
        font_color_canceled: "#0000FF"
        font_color_ended: "#FFFFFF"
```

<img width="932" alt="image" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/e747b906-cd05-4ea7-87a5-8474e4feccae">
