### DISCUSSION TITLE
HDR10+ does not reliably show up?  How is it recognized.

### DISCUSSION THREAD

**Discussion by adam-rudd** [meisnate12/Plex-Meta-Manager#1987] [General]
I'm working on just a minimal setup.  Indicate just 4K, HDR10, and HDR10+.  

HDR seems to get reliably picked up.  Like this one, it's not anwhere in filename, but is in the metadata, and gets properly tagged 4K HDR.

```
Complete name                            : /mnt/sataD/Movies/Movies _ME-4K/MOVIE_ME-ICQ12.mkv
...
Format profile                           : Main 10@L5@Main
HDR format                               : SMPTE ST 2086, HDR10 compatible
...
```

HDR10+ does not.  Many do not get recognized. It seems totally random which ones do and which ones do not.  Example:

```
...
Complete name                            : /mnt/sataE/Movies/Movies HDR 4K WebDL/MOVIE.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX.mkv
...
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
...
```

```
overlay_files:
    - pmm: resolution
      template_variables:
        use_4k_dvhdrplus: false
        use_4k_plus: true
        use_dvhdrplus: false
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_edition: false
        use_4k_dvhdr: false
        use_4k_dv: false
        use_plus: true
        use_hdr: true
        use_dv: false
```
