### DISCUSSION TITLE
Overlay Files not found

### DISCUSSION THREAD

**Discussion by Adandu** [meisnate12/Plex-Meta-Manager#1998] [Q&A] [answered]
Hello Guys,

Since I moved to Kometa from PMM, the overlay is not working anymore.
I modified the config for overlays, instead of pmm I changed to default

Config for overlay files looks like this:
```
    overlay_files:
    - default: ribbon
    - default: resolution
    - default: video_format
    - default: audio_codec
    - default: ratings
      template_variables:
        rating1: critic
        rating2: audience
        rating3: user
        rating1_image: imdb
        rating2_image: rt_popcorn
        rating3_image: tmdb
    - default: mediastinger
    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
```
After running I get the following errors:
![2024-04-24 07_43_08-__192 168 200 200_masterchief_mnt_sdc_docker_kometa_config_logs_meta log - Notep](https://github.com/Kometa-Team/Kometa/assets/7235497/a346de5e-9c43-4065-98cf-558c1d23c81c)
![2024-04-24 07_06_00-SuperPuTTY - MasterChief](https://github.com/Kometa-Team/Kometa/assets/7235497/57f69584-3d59-4628-bba0-e4d4c548d8d8)

The overlays look like this in Plex:
![2024-04-24 07_11_28-Plex](https://github.com/Kometa-Team/Kometa/assets/7235497/c8926f79-654b-4586-8058-f31e80676629)

I manually copied the Mediastinger.png file in /config/overlays and now Mediastinger overlay works. The rest do not.

I have no idea how to fix this issue. When running PMM everything worked as expeced.
Any help would be much apreciated.
Thank you,
Adandu
