### DISCUSSION TITLE
How to exclude movies/shows that exist in another named collection

### DISCUSSION THREAD

**Discussion by zpz5HAU-tgc3fgw2xwr** [meisnate12/Plex-Meta-Manager#202] [Q&A] [answered]
For my example I have two collections: an Anime collection and an Animation collection. I want to exclude everything that was added to the Anime collection from re-appearing in the Animation collection.

Is there a way to do this?

**Comment by meisnate12** [comment, marked as answer]
You could use a filter

```yaml 
filters:
  collection.not: Anime
```

Or if your initial search is using a plex search you can use `collection.not: Anime` with that search which would be faster then using filters

```yaml
Collections:
  Animation:
    plex_search:
      genre: Animation
      collection.not: Anime
```
