### DISCUSSION TITLE
`has_dolby_vision` returns `ignored`

### DISCUSSION THREAD

**Discussion by SebbeJohansson** [meisnate12/Plex-Meta-Manager#2031] [Q&A]
Hi! I am trying to make a collection that has all 4k movies that also have dolby vision. I cant get it to work.
Here are my two attempts:
```
  4K Dolby Vision: #fiters only movies with 4K and Dolby Vision and places them in a collection 
    plex_search:
      any:
        resolution: 4k
    filters:
      has_dolby_vision: true
    sort_title: "!021_+4K Dolby Vision" #This places the collection in a specific order vs other collections based on the PMM collection section order 
    url_poster: https://theposterdb.com/api/assets/226933
```
```
  4K Dolby Vision: #fiters only movies with 4K and Dolby Vision and places them in a collection 
    plex_all: true
    filters: 
        has_dolby_vision: true
        resolution: 4k
    sort_title: "!021_+4K Dolby Vision" #This places the collection in a specific order vs other collections based on the PMM collection section order 
    collection_order: title.asc 
    url_poster: https://theposterdb.com/api/assets/226933
  ```
Both options gets the tag `ignored` in the output.
![image](https://github.com/Kometa-Team/Kometa/assets/5083273/91778380-45c8-4780-bd0e-16196f970ba6)

Let me know if i should make an issue instead!

**Comment by chazlarson** [comment]
Can you provide the full log showing the issues in context?  Ideally you'd take this to the Discord.

**Comment by SebbeJohansson** [comment]
Here is a new fresh run of the setup:
[meta.log](https://github.com/Kometa-Team/Kometa/files/15231752/meta.log)

Ill join the discord :D

**Comment by SebbeJohansson** [comment]
Sorted this out on the discord! Summary:
- I had misunderstood what `ignored` means. It just means that no items matched. The logs show this pretty clearly.
- I had minimum at default (2). After making sure I had a movie with DV and set `minimum_items` to 1, I now have a working collection.
- `plex_search` is a lot faster than `plex_all: true`, so I would recommend using this.

Here is my working setup:
```
collections:
  4K Dolby Vision: #fiters only movies with 4K and Dolby Vision and places them in a collection 
    plex_search:
      any:
        resolution: 4k
    filters:
      has_dolby_vision: true
    sort_title: "!021_+4K Dolby Vision" #This places the collection in a specific order vs other collections based on the PMM collection section order 
    minimum_items: 1
    url_poster: https://theposterdb.com/api/assets/226933
```

Thanks to Yozora on the discord for helping!
