### DISCUSSION TITLE
update poster from link

### DISCUSSION THREAD

**Discussion by PierreDurrr** [meisnate12/Plex-Meta-Manager#204] [Q&A] [answered]
My movies.yml file is like this :

>   Alien - Saga:
>     template: {name: Collection, collection: 8091, summary: 8091, poster: https://theposterdb.com/api/assets/1213}
>     trakt_list: 
>       - https://trakt.tv/users/benreilly97/lists/alien?sort=released,desc
>     collection_order: alpha
>     collection_mode: hide_items

But the collection which is created has the tmdb poster.
Is it normal that the poster is not updated with the one supplied in poster: https://xxxxxxx ?
Should i use template: {name: **Movie** instead of collection ?

**Comment by meisnate12** [comment, marked as answer]
if you're just using the templates from the sample file then neither Movie nor Collection would do what you want.

This is the collection template and it only takes two variables, `collection` and `movie`, so anything else given to it is just ignored i.e. poster and summary
```yaml
  Collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
```

if you want summary and poster to work in the template you can add it here also if you use `tmdb_collection_details` it will update the poster background and summary of the collection so doing a summary variable is redundant. 

```yaml
  Collection:
    optional:
      - collection
      - movie
      - poster
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    url_poster: <<poster>>
    sync_mode: sync
    collection_order: release
```

```yaml
Alien - Saga:
  template: {name: Collection, collection: 8091, poster: https://theposterdb.com/api/assets/1213}
  trakt_list:
    - https://trakt.tv/users/benreilly97/lists/alien?sort=released,desc
  collection_order: alpha
  collection_mode: hide_items
```

or if you didnt want to edit the template just use `url_poster` in the collection like so


```yaml
Alien - Saga:
  template: {name: Collection, collection: 8091}
  trakt_list:
    - https://trakt.tv/users/benreilly97/lists/alien?sort=released,desc
  url_poster: https://theposterdb.com/api/assets/1213
  collection_order: alpha
  collection_mode: hide_items
```
