### DISCUSSION TITLE
Way to do a collection based on Audio format?

### DISCUSSION THREAD

**Discussion by KrunchMuffin** [meisnate12/Plex-Meta-Manager#213] [Q&A] [answered]
I couldn't find anything concrete, so was wondering if there was a way to say have a collection with all "Dolby Atmos" movies?

**Comment by meisnate12** [comment, marked as answer]
You can use the `audio_track_title` [Filter](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Filters) to look at the title of the audio track for any that have Dolby Atmos

**Reply by AunePVP** [reply]
I can't open it

**Reply by YozoraXCII** [reply]
> 

https://github.com/meisnate12/Plex-Meta-Manager/wiki/Filters

**Reply by AunePVP** [reply]
ok thank you

**Reply by sameleff** [reply]
@AunePVP were you able to get this to work? I'm trying to do a similar thing but am not sure what key names are available via audio_track_title in order to filter them correctly. I tried using the [audio_codec](https://www.metamanager.wiki/en/latest/defaults/overlays/audio_codec.html) options in my filter since they are already used to create the overlay but I was unsuccessful there as well.

@meisnate12 do I need to use regex formulas similar to those in the [audio_codec overlay](https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/overlays/audio_codec.yml) document? I'm not sure how to translate from the overlay template into the collections syntax if so.

**Reply by sameleff** [reply]
For anyone else who finds this post, the below configs worked for me (trick was to copy the regex syntax from the[ audio_codec.yml](https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/overlays/audio_codec.yml) default and apply it in the new config file.

```
collections:
  Immersive Movies:
    plex_all: true
    filters:
      - filepath.regex: '(?i)^(?=.*\btrue[ ._-]?hd(\b|\d))(?=.*\batmos(\b|\d))'
      - audio_track_title.regex: '(?i)^(?=.*\btrue[ ._-]?hd(\b|\d))(?=.*\batmos(\b|\d))'
      - filepath.regex: '(?i)^(?=.*\b(dd[p+])|(dolby digital plus)\b)(?=.*\batmos(\b|\d))'
      - audio_track_title.regex: '(?i)^(?=.*\b(dd[p+])|(dolby digital plus)\b)(?=.*\batmos(\b|\d))'
      - filepath.regex: '(?i)\batmos(\b|\d)'
      - audio_track_title.regex: '(?i)\batmos(\b|\d)'
      - filepath.regex: '(?i)\bdts[ ._-]?x\b'
      - audio_track_title.regex: '(?i)\bdts[ ._-]?x\b'
```
