### DISCUSSION TITLE
How to NOT update ALL config.yml files, if a token expires?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#2171] [Q&A]
Hi,
I have about 20 collection files, which use trakt/plex/tmdb api/tokens/etc.

Everytime, the Trakt or Plex token expires, I need to manually change a lot of *.yml files by hand to set the new valid tokens.
like this:

```
| plex:                                                                                              |
|   url: (redacted)                                                                                  |
|   token: (redacted)                                                                                |
| tautulli:                                                                                          |
|   url: (redacted)                                                                                  |
|   apikey: (redacted)                                                                               |
| tmdb:                                                                                              |
|   apikey: (redacted)                                                                               |
| trakt:                                                                                             |
|   client_id: (redacted)                                                                            |
|   client_secret: (redacted)                                                                        |
|   authorization:                                                                                   |
|     access_token: (redacted)                                                                       |
|     token_type: Bearer                                                                             |
|     expires_in: 7889238                                                                            |
|     refresh_token: (redacted)                                                                      |
|     scope: public                                                                                  |
|     created_at: 1721438061                                                                         |
|   pin:                                                                                             |
|       
```
That is very cumbersome and also complicated.

So I wondered, if there is a more userfriendly way to acually put the credentials into a single file and let all other config yml files read those credentials from it.

I tried a token.yml
```

tokens:
  plex_url: &plex_url "https://123:32400"
  plex_token: &plex_token foo
  plex_timeout: &plex_timeout 120
  plex_clean_bundles: &plex_clean_bundles false
  plex_empty_trash: &plex_empty_trash false
  plex_optimize: &plex_optimize false
  plex_db_cache: &plex_db_cache
  plex_verify_ssl: &plex_verify_ssl

  tautulli_url: &tautulli_url "http://123:8181"
  tautulli_apikey: &tautulli_apikey 123

  tmdb_apikey: &tmdb_apikey 123
  tmdb_language: &tmdb_language de
  tmdb_cache_expiration: &tmdb_cache_expiration 60
  tmdb_region: &tmdb_region

  trakt_client_id: &trakt_client_id 123
  trakt_client_secret: &trakt_client_secret 123
  trakt_access_token: &trakt_access_token 123
  trakt_token_type: &trakt_token_type Bearer
  trakt_expires_in: &trakt_expires_in 7889238
  trakt_refresh_token: &trakt_refresh_token 123
  trakt_scope: &trakt_scope public
  trakt_created_at: &trakt_created_at 1720126501
  trakt_pin: &trakt_pin

```
and import it to the config:
```
imports:
  - tokens.yml

plex:
  url: *plex_url
  token: *plex_token
  timeout: *plex_timeout
  clean_bundles: *plex_clean_bundles
  empty_trash: *plex_empty_trash
  optimize: *plex_optimize
  db_cache: *plex_db_cache
  verify_ssl: *plex_verify_ssl

tautulli:
  url: *tautulli_url
  apikey: *tautulli_apikey

tmdb:
  apikey: *tmdb_apikey
  language: *tmdb_language
  cache_expiration: *tmdb_cache_expiration
  region: *tmdb_region

trakt:
  client_id: *trakt_client_id
  client_secret: *trakt_client_secret
  authorization:
    access_token: *trakt_access_token
    token_type: *trakt_token_type
    expires_in: *trakt_expires_in
    refresh_token: *trakt_refresh_token
    scope: *trakt_scope
    created_at: *trakt_created_at
  pin: *trakt_pin

but that did not work as hoped ;-)

I've searched the net, but no help arrived...

So I'd like to ask here, if there is *any* userfriendly way to not have all config yml files updated by hand if a token expires?

Thank you.

```

**Comment by chazlarson** [comment]
[Config secrets](https://kometa.wiki/en/nightly/kometa/environmental/#kometa-vars)

**Reply by gitttt54** [reply]
Thank you! That worked nicely!

Although, when I had put `PLEX_TOKEN`=1234 in my `.env` file, it did not work and throwed an execption, while all other variables did work fine. I renamed the variable to `MY_PLEX_TOKEN` and then it worked too. Must be a collision with the variablename...dunno, THANKS again!

**Reply by gitttt54** [reply]
regarding to this:
> Although, when I had put `PLEX_TOKEN`=1234 in my `.env` file, it did not work and throwed an execption, while all other variables did work fine. I renamed the variable to `MY_PLEX_TOKEN` and then it worked too. Must be a collision with the variablename...dunno,

that whole .env thing seems kinda buggy to me.
when I enter MY_PLEX_TOKEN in the .env file, the MY_PLEX_TOKEN is not mentioned in the log as all others, say:

 Kometa Secrets Read:                                                                               |
| --kometa-my-tmdb-api-key (KOMETA_MY_TMDB_API_KEY): (redacted)                                      |
| --kometa-my-trakt-client-id (KOMETA_MY_TRAKT_CLIENT_ID): (redacted)                                |
| --kometa-my-trakt-client-secret (KOMETA_MY_TRAKT_CLIENT_SECRET): (redacted)                        |
| --kometa-my-trakt-access-token (KOMETA_MY_TRAKT_ACCESS_TOKEN): (redacted)                          |
| --kometa-my-trakt-token-type (KOMETA_MY_TRAKT_TOKEN_TYPE): (redacted)                              |
| --kometa-my-trakt-expires-in (KOMETA_MY_TRAKT_EXPIRES_IN): (redacted)                              |
| --kometa-my-trakt-refresh-token (KOMETA_MY_TRAKT_REFRESH_TOKEN): (redacted)                        |
| --kometa-my-trakt-scope (KOMETA_MY_TRAKT_SCOPE): (redacted)                                        |
| --kometa-my-trakt-created-at (KOMETA_MY_TRAKT_CREATED_AT): (redacted)                              |
| --kometa-my-trakt-pin (KOMETA_MY_TRAKT_PIN): (redacted)                                            |

its just ignored...
it seems to me, IF the line contains the word PLEX it leads to problems and kometa does not use the plex token at all.

when I rename it to something other, NOT containing the word PLEX, the log show the correct entries AND kometa uses the token as expected.

| --kometa-my-plux-token (KOMETA_MY_PLUX_TOKEN): (redacted)

just wanted to mention....

**Reply by gitttt54** [reply]
also, the first line of the .env file is ignores by kometa. I had my KOMETA_MY_TAUTULLI_API_KEY=12345 completely ignored, so I put a comment ####### in the first line of the .env file and it showed up in the log and was'nt ignored anymore.

**Comment by gitttt54** [comment]
unfortunately...that did only work nicely until I needed to enter a new trakt pin.

I have tried this way (putting my new PIN to the .env file)

```
trakt:
  client_id: <<MY_TRAKT_CLIENT_ID>
  client_secret: <<MY_TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: 4289ea789443545413ebcb474df47fda609510f4682c69
    token_type: Bearer
    expires_in: 7889238
    refresh_token: 85915476cf4c967953456546e638e19f1ca1f0ef677dc14daa52b11fa57
    scope: public
    created_at: 1721438061
  pin: <<MY_TRAKT_PIN>>
```

or putting all to the .env file:

```
trakt:
  client_id: <<MY_TRAKT_CLIENT_ID>
  client_secret: <<MY_TRAKT_CLIENT_SECRET>>
  authorization:
    access_token: <<MY_TRAKT_ACCESS_TOKEN>>
    token_type: <<MY_TRAKT_TOKEN_TYPE>>
    expires_in: <<MY_TRAKT_EXPIRES_IN>>
    refresh_token: <<MY_TRAKT_REFRESH_TOKEN>>
    scope: <<MY_TRAKT_SCOPE>>
    created_at: <<MY_TRAKT_CREATED_AT>>
  pin:
```

but none of any variant did work out to create a new working trakt auth.

I got logs like these:
```
| Connecting to Trakt...                                                                             |
| Trakt Error: (403) Forbidden                                                                       |
| Refreshing Access Token...                                                                         |
| Navigate to: https://trakt.tv/oauth/authorize?response_type=code&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=<<MY_TRAKT_CLIENT_ID> |
| If you get an OAuth error your client_id or client_secret is invalid                               |
| Trakt pin (case insensitive): | Input Failed                                                                                       |
| Trakt Connection Failed
```

Would anyone please tell me HOW one can update the trakt auth while using the .env file?

I did not find any helpful example anywhere.
