### DISCUSSION TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'   ?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#2172] [Q&A]
_Version: 2.0.2 (Docker: master)_ 

this config:
```
libraries:
# https://github.com/meisnate12/Plex-Meta-Manager/discussions/1262#discussioncomment-4635023
  Filme:
    library_name: Filme
    operations:
      delete_collections:
        managed: false
        less: 2
      mass_collection_mode: hide

  Serien:
    library_name: Serien
    operations:
      mass_collection_mode: hide
      delete_collections:
        managed: false
        less: 2



```

gives this error in the log:

```
|======================================= Deleting Collections =======================================|
|                                                                                                    |
| Traceback (most recent call last):                                                                 |
|   File "//kometa.py", line 740, in run_libraries                                                   |
|     library_status[library.name]["Library Operations"] = library.Operations.run_operations()       |
|                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       |
|   File "/modules/operations.py", line 1059, in run_operations                                      |
|     and (less is None or col.childCount < less) \                                                  |
|                          ^^^^^^^^^^^^^^^^^^^^^                                                     |
| TypeError: '<' not supported between instances of 'NoneType' and 'int'                             |
|                                                                                                    |
| '<' not supported between instances of 'NoneType' and 'int'                                        |
|                                                                                                    |

|========================================= Critical Summary =========================================|
|                                                                                                    |
| Count | Message                                                                                    |
|=======|============================================================================================|
|     1 | argument of type 'NoneType' is not iterable                                                |
|                                                                                                    |
|====================================================================================================|


```

is it still not possible to delete _unmanaged collections_ **and** _collections with less than 2 items_ in one single library?

I was under the impression, that something must have been changed, because my old config, which worked great for all the years, now deletes ALL of my collections in "Serien" (not in "Filme" strangely though...) ;-/

```
libraries:
# https://github.com/meisnate12/Plex-Meta-Manager/discussions/1262#discussioncomment-4635023
  Filme (delete collections with less 2 items):
    library_name: Filme
    operations:
      delete_collections:
        less: 2
        # configured: None
        # managed: None
  Filme (hide and delete unmanaged collections):
    library_name: Filme
    operations:
      mass_collection_mode: hide
      delete_collections:
        managed: false
        # configured: None
        # less: 1
  Serien (hide and delete unmanaged collections):
    library_name: Serien
    operations:
      mass_collection_mode: hide
      delete_collections:
        managed: false
        # configured: None
        # less: 1
  Serien (delete collections with less 2 items):
    library_name: Serien
    operations:
      delete_collections:
        less: 2
        # configured: None
        # managed: None

```

thank you
