### DISCUSSION TITLE
No log line matching the '' filter

### DISCUSSION THREAD

**Discussion by Lockie85** [meisnate12/Plex-Meta-Manager#2218] [Q&A]
Hey,

I'm running Kometa via Portainer (Docker) and a Stack (Docker Compose).

Here is my compose:
```
version: '2.1'
services:
  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    environment:
      - PUID=1026 # Update with your user ID
      - PGID=100 # Update with your group ID
      - TZ=Europe/London # Update with your timezone
    volumes:
      - /volume1/configs/kometa:/config:rw # Update with your actual config path
    restart: unless-stopped
```

And here is my config.yml:
```
libraries:
  Films:
    collection_files:
      - file: config/Films.yml
      - default: imdb
      - default: studio
      - default: genre
      - default: actor
    operations:
      mass_critic_rating_update: tmdb
      split_duplicates: true
  TV shows:
    collection_files:
      - file: config/TV shows.yml
      - default: tmdb
      - default: network
    remove_overlays: false
    overlay_files:
      - file: config/Overlays.yml
plex:
  url: https://192.168.1.2:32400
  token: ###############
  timeout: 60
  db_cache: true
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl: true
tmdb:
  apikey: ############################
  language: en
  region: GB
  cache_expiration: 60
```

When I run my Stack the only log I get within my container is:
`No log line matching the '' filter`

![image](https://github.com/user-attachments/assets/755fce19-74bc-4cc7-ab20-fc8cb0ed190e)

Any ideas what is going on?
