### DISCUSSION TITLE
Issue with Overlay Rating by Season

### DISCUSSION THREAD

**Discussion by Lockie85** [meisnate12/Plex-Meta-Manager#2251] [Q&A]
Hi,

Below is my config.yml which generally works fine but I have one issue. I'm trying to display an overlay with the IMDB and TVDB ratings for TV Shows and TV Shows by Season. What I see is a rating for the show on a show level but not on a season level. Instead the overlay has <<audience _rat

Like so:
![image](https://github.com/user-attachments/assets/a2023c3f-a709-470f-909f-591dbbf3d028)

Any idea what might be wrong in my config?

Many Thanks

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/json-schema/config-schema.json
# .------------------------------------------------------------.
# | ____        _ _                                ____   ___  |
# || __ ) _   _| | |_ __ ___   ___   ___  ___  ___|___ \ / _ \ |
# ||  _ \| | | | | | '_ ` _ \ / _ \ / _ \/ __|/ _ \ __) | | | ||
# || |_) | |_| | | | | | | | | (_) | (_) \__ \  __// __/| |_| ||
# ||____/ \__,_|_|_|_| |_| |_|\___/ \___/|___/\___|_____|\___/ |
# '------------------------------------------------------------'
### Highly recommend using Visual Studio Code with indent-rainbow by oderwat extension and YAML by Red Hat extension. VSC will also leverage the above link to enhance Kometa yml edits.
### Must be on Kometa Version 2.0.1-nightly1 or greater
libraries:
# .-------------------------------.
# | __  __            _           |
# ||  \/  | _____   _(_) ___  ___ |
# || |\/| |/ _ \ \ / / |/ _ \/ __||
# || |  | | (_) \ V /| |  __/\__ \|
# ||_|  |_|\___/ \_/ |_|\___||___/|
# '-------------------------------'
  Films:                                           # Must match a library name in your Plex
    report_path: config/missing/Films_report.yml
    remove_overlays: false                          # Set to true if you want to remove overlays
    reapply_overlays: false                         # Before setting this to true, you should know what you are doing and open a #kometa-help beforehand
    # reset_overlays: tmdb                            # if you want to reset the poster to default poster from tmdb
    template_variables:
      sep_style: gray                               # use the gray separators globally for this library
      collection_mode: hide                         # hide the collections
      language: en                                  # could be default(which is en), da, de, fr, pt-br or another lang code that we have translated
      placeholder_imdb_id: tt8579674                # 1917 (2019) placeholder id for the separators
    metadata_files:                                 # These files contain metadata: attributes
    - git: bullmoose20/godzilla                     # Custom metadata file for Godzilla stuff
    collection_files:                               # These files contain collections: and/or dynamic_collections attributes
    # - file: config/metadata/overlay_label.yml       # Creates collection of all items with an Overlay label (Testing only)
    - git: bullmoose20/movies_refresh               # tells plex to refresh media items added within the last 7 days
    - default: separator_award                      # An "index card"
# .--------------------------------------------------------.
# | _     _ _        ___                 _                 |
# || |   (_) |__    / _ \__   _____ _ __| | __ _ _   _ ___ |
# || |   | | '_ \  | | | \ \ / / _ \ '__| |/ _` | | | / __||
# || |___| | |_) | | |_| |\ V /  __/ |  | | (_| | |_| \__ \|
# ||_____|_|_.__/   \___/  \_/ \___|_|  |_|\__,_|\__, |___/|
# |                                              |___/     |
# '--------------------------------------------------------'
    overlay_files:                                  # These files contain overlays: attributes
    ################### CONTENT RATING SECTION ###################
    # - default: content_rating_nz                    # NZ content ratings
    # - default: content_rating_au                    # AU content ratings
      # template_variables:
        # horizontal_align: left
        # vertical_align: bottom
        # horizontal_offset: 60
        # vertical_offset: 60
        # back_color: '#00000000'
        # back_width: 1
        # back_height: 1
        # # url: (redacted)
        # # color: false
    # - default: content_rating_de                    # DE FSK content ratings
    - default: content_rating_uk                    # UK BBFC content ratings
    # - default: content_rating_us_movie              # US MPAA content ratings
      template_variables:
        horizontal_align: left
        vertical_align: top
        vertical_offset: 637
    # - default: commonsense                          # Commonsense content ratings Age 2+, Age 14+, etc.
    ################### CONTENT RATING SECTION END ###############
    # - default: direct_play                          # Show direct play only overlay
    - default: ratings                              # Ratings with custom fonts matched to the style of the rating, font_size, and on the right in 'square' format
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        rating1_font_size: 63

        rating2: critic
        rating2_image: imdb
        rating2_font: config/metadata/overlays/fonts/Impact.ttf
        rating2_font_size: 70

        rating3: audience
        rating3_image: tmdb
        rating3_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        rating3_font_size: 70

        horizontal_position: right

        # rating_source: Anidb
        # font: config/metadata/overlays/fonts/Handel Gothic ITC W01 Heavy.ttf
        # rating_source: IMDb
        # font: config/metadata/overlays/fonts/Impact.ttf
        # rating_source: Letterboxd
        # font: config/metadata/overlays/fonts/HelveticaNowDisplay-ExtBlk.ttf
        # rating_source: Metacritic
        # font: config/metadata/overlays/fonts/Myriad Bold.otf
        # rating_source: TMDb
        # font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        # rating_source: Trakt
        # font: config/metadata/overlays/fonts/Claspo-ND-Medium.ttf
        # rating_source: Rotten
        # font: config/metadata/overlays/fonts/Adlib.ttf
    - default: ribbon                               # Used for ribbon in bottom right
      template_variables:
        style: red
# .------------------------------------------------------.
# | _     _ _       ____       _   _   _                 |
# || |   (_) |__   / ___|  ___| |_| |_(_)_ __   __ _ ___ |
# || |   | | '_ \  \___ \ / _ \ __| __| | '_ \ / _` / __||
# || |___| | |_) |  ___) |  __/ |_| |_| | | | | (_| \__ \|
# ||_____|_|_.__/  |____/ \___|\__|\__|_|_| |_|\__, |___/|
# |                                            |___/     |
# '------------------------------------------------------'
    settings:
      asset_directory: config/assets/Films/
      prioritize_assets: true                       # The asset_directory contains folders per media item with respective posters
# .------------------------------------------------------------------.
# | _     _ _        ___                       _   _                 |
# || |   (_) |__    / _ \ _ __   ___ _ __ __ _| |_(_) ___  _ __  ___ |
# || |   | | '_ \  | | | | '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \/ __||
# || |___| | |_) | | |_| | |_) |  __/ | | (_| | |_| | (_) | | | \__ \|
# ||_____|_|_.__/   \___/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|___/|
# |                      |_|                                         |
# '------------------------------------------------------------------'
    operations:
      split_duplicates: false                       # Splits all duplicate movies/shows found in this library
      assets_for_all: true                          # Search in assets for images for every item in your library
      delete_collections:
        configured: false                           # False - Collection must be an Unconfigured Collection to be deleted (collection is not in the config file of the specific Kometa run).
        managed: false                              # False - Collection must be an Unmanaged Collection to be deleted (the collection does not have the Kometa label)
        less: 99999                                 # Effectively all collections regardless of teh number of items in the collection
      mass_user_rating_update: mdb_tomatoes         # Update user ratings with mdb_tomatoes
      mass_critic_rating_update: imdb               # Update critic ratings with imdb
      mass_audience_rating_update: tmdb             # Update audience ratings with tmdb
      mass_genre_update:
      - tmdb                                        # Update all genres from tmdb
      - imdb                                        # Update all genres from imdb if not from tmdb
      - tvdb                                        # Update all genres from tvdb if not from imdb
      mass_content_rating_update:
      - mdb_commonsense                             # Changes Content Rating to "1", "2" etc. to specify appropriate age
      - omdb                                        # Changes Content Rating from omdb if not found on mdb_commonsense
      mass_studio_update:
      - tmdb                                        # Update all studios from tmdb
      mass_originally_available_update:
      - tmdb                                        # Update all original available date from tmdb
      - tvdb                                        # Update all original available date from tvdb if not from tmdb
      - omdb                                        # Update all original available date from omdb(imdb) if not from tvdb
      mass_imdb_parental_labels: none               # Apply all Parental Labels with a value of None, Mild, Moderate, or Severe to match IMDb parental guide
      # mass_poster_update: tmdb                      # Resets posters to tmdb, plex, locked, unlock which is useful to remove all overlays when running with -r -op
# .-----------------------------------------------.
# | _______     __  ____  _                       |
# ||_   _\ \   / / / ___|| |__   _____      _____ |
# |  | |  \ \ / /  \___ \| '_ \ / _ \ \ /\ / / __||
# |  | |   \ V /    ___) | | | | (_) \ V  V /\__ \|
# |  |_|    \_/    |____/|_| |_|\___/ \_/\_/ |___/|
# '-----------------------------------------------'
  TV shows:                                         # Must match a library name in your Plex
    report_path: config/missing/TV_report.yml
    remove_overlays: false                          # Set to true if you want to remove overlays
    reapply_overlays: true                         # If you are doing a lot of testing and changes like me, keep this to true to always reapply overlays
    # reset_overlays: tmdb                            # if you want to reset the poster to default poster from tmdb
    template_variables:
      sep_style: gray                               # use the gray separators globally for this library
      collection_mode: hide                         # hide the collections
      language: en                                  # could be default(which is en), da, de, fr, pt-br or another lang code that we have translated
      placeholder_imdb_id: tt1190634                # The Boys (2019) placeholder id for the separators
    metadata_files:                                 # These files contain metadata: attributes
    - git: bullmoose20/money_heist                  # Custom metadata file for Money Heist
    collection_files:                               # These files contain collections: and/or dynamic_collections attributes
    # - file: config/metadata/overlay_label.yml       # Creates collection of all items with an Overlay label (Testing only)
    - git: bullmoose20/tv_refresh                   # Tells plex to refresh media items added within the last 7 days
    - default: separator_award                      # An "index card"
# .--------------------------------------------------------.
# | _     _ _        ___                 _                 |
# || |   (_) |__    / _ \__   _____ _ __| | __ _ _   _ ___ |
# || |   | | '_ \  | | | \ \ / / _ \ '__| |/ _` | | | / __||
# || |___| | |_) | | |_| |\ V /  __/ |  | | (_| | |_| \__ \|
# ||_____|_|_.__/   \___/  \_/ \___|_|  |_|\__,_|\__, |___/|
# |                                              |___/     |
# '--------------------------------------------------------'
    overlay_files:
    ################### CONTENT RATING SECTION ###################
    # - default: content_rating_nz                    # NZ content ratings
    # - default: content_rating_nz                    # NZ content ratings
      # template_variables:
        # builder_level: season
    # - default: content_rating_nz                    # NZ content ratings
      # template_variables:
        # builder_level: episode
    # - default: content_rating_au                    # AU content ratings
    # - default: content_rating_au                    # AU content ratings
      # template_variables:
        # builder_level: season
    # - default: content_rating_au                    # AU content ratings
      # template_variables:
        # builder_level: episode
    # - default: content_rating_de                    # DE FSK content ratings
    # - default: content_rating_de                    # DE FSK content ratings
      # template_variables:
        # builder_level: season
    # - default: content_rating_de                    # DE FSK content ratings
      # template_variables:
        # builder_level: episode
    # - default: content_rating_uk                    # UK BBFC content ratings
    # - default: content_rating_uk                    # UK BBFC content ratings
      # template_variables:
        # builder_level: season
    # - default: content_rating_uk                    # UK BBFC content ratings
      # template_variables:
        # builder_level: episode
    - default: content_rating_uk               # UK BBFC content ratings
      template_variables:
        horizontal_align: left
        vertical_align: top
        vertical_offset: 630
    - default: content_rating_uk               # UK BBFC content ratings
      template_variables:
        horizontal_align: left
        vertical_align: top
        vertical_offset: 630
        builder_level: season
    - default: content_rating_uk               # UK BBFC content ratings
      template_variables:
        builder_level: episode
    # - default: commonsense                          # Commonsense content ratings Age 2+, Age 14+, etc.
    # - default: commonsense
      # template_variables:
        # builder_level: season
    # - default: commonsense
      # template_variables:
        # builder_level: episode
    ################### CONTENT RATING SECTION END ###############
    # - default: direct_play
    # - default: direct_play
      # template_variables:
        # builder_level: season
    # - default: direct_play
      # template_variables:
        # builder_level: episode
    - default: ratings                              # Ratings with custom fonts matched to the style of the rating, font_size, and on the right in 'square' format. builder_level: show has 3 ratings max
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        rating1_font_size: 63

        rating2: critic
        rating2_image: imdb
        rating2_font: config/metadata/overlays/fonts/Impact.ttf
        rating2_font_size: 70

        rating3: audience
        rating3_image: tmdb
        rating3_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        rating3_font_size: 70

        horizontal_position: right
    - default: ratings                              # Ratings with custom fonts matched to the style of the rating, font_size, and on the right in 'square' format. builder_level: episode has 2 ratings max
      template_variables:
        # rating1: user
        # rating1_image: rt_tomato
        # rating1_font: config/metadata/overlays/fonts/Adlib.ttf
        # rating1_font_size: 63

        # rating1: critic
        # rating1_image: imdb
        # rating1_font: config/metadata/overlays/fonts/Impact.ttf
        # rating1_font_size: 70

        rating2: audience
        rating2_image: tmdb
        rating2_font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        rating2_font_size: 70

        horizontal_position: right
        builder_level: season
    - default: ribbon                               # Used for ribbon in bottom right
      template_variables:
        style: red
    - default: status                               # Airing, Returning, Ended, Canceled and works with builder_level show
      template_variables:
        horizontal_align: center
        vertical_align: top
        vertical_offset: 0
        horizontal_offset: 0
        back_height: 85
        back_width: 1100
        font: config/metadata/overlays/fonts/Avenir_95_Black.ttf
        font_size: 60
        back_color_airing: '#016920'
        back_color_returning: '#81007F'
        back_color_canceled: '#B52222'
        back_color_ended: '#000847'
# .------------------------------------------------------.
# | _     _ _       ____       _   _   _                 |
# || |   (_) |__   / ___|  ___| |_| |_(_)_ __   __ _ ___ |
# || |   | | '_ \  \___ \ / _ \ __| __| | '_ \ / _` / __||
# || |___| | |_) |  ___) |  __/ |_| |_| | | | | (_| \__ \|
# ||_____|_|_.__/  |____/ \___|\__|\__|_|_| |_|\__, |___/|
# |                                            |___/     |
# '------------------------------------------------------'
    settings:
      asset_directory: config/assets/TV shows/
      prioritize_assets: true                       # The asset_directory contains folders per media item with respective posters
# .------------------------------------------------------------------.
# | _     _ _        ___                       _   _                 |
# || |   (_) |__    / _ \ _ __   ___ _ __ __ _| |_(_) ___  _ __  ___ |
# || |   | | '_ \  | | | | '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \/ __||
# || |___| | |_) | | |_| | |_) |  __/ | | (_| | |_| | (_) | | | \__ \|
# ||_____|_|_.__/   \___/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|___/|
# |                      |_|                                         |
# '------------------------------------------------------------------'
    operations:
      split_duplicates: false                       # Splits all duplicate movies/shows found in this library
      assets_for_all: true                          # Search in assets for images for every item in your library
      delete_collections:
        configured: false                           # False - Collection must be an Unconfigured Collection to be deleted (collection is not in the config file of the specific Kometa run).
        managed: false                              # False - Collection must be an Unmanaged Collection to be deleted (the collection does not have the Kometa label)
        less: 99999                                 # Effectively all collections regardless of teh number of items in the collection
      mass_user_rating_update: mdb_tomatoes         # Update user ratings with mdb_tomatoes
      mass_critic_rating_update: imdb               # Update critic ratings with imdb
      mass_audience_rating_update: tmdb             # Update audience ratings with tmdb
      mass_genre_update:
      - tmdb                                        # Update all genres from tmdb
      - imdb                                        # Update all genres from imdb if not from tmdb
      - tvdb                                        # Update all genres from tvdb if not from imdb
      mass_content_rating_update:
      - mdb_commonsense                             # Changes Content Rating to "1", "2" etc. to specify appropriate age
      - omdb                                        # Changes Content Rating from omdb if not found on mdb_commonsense
      mass_studio_update:
      - tmdb                                        # Update all studios from tmdb
      mass_originally_available_update:
      - tmdb                                        # Update all original available date from tmdb
      - tvdb                                        # Update all original available date from tvdb if not from tmdb
      - omdb                                        # Update all original available date from omdb(imdb) if not from tvdb
      mass_episode_critic_rating_update: imdb       # Update critic ratings with imdb for episodes
      mass_episode_audience_rating_update: tmdb     # Update audience ratings with tmdb for episodes
      mass_imdb_parental_labels: none               # Apply all Parental Labels with a value of None, Mild, Moderate, or Severe to match IMDb parental guide
      # mass_poster_update: tmdb                      # Resets posters to tmdb, plex, locked, unlock which is useful to remove all overlays when running with -r -op
# .---------------------------------.
# | ____  _             _ _     _   |
# ||  _ \| | __ _ _   _| (_)___| |_ |
# || |_) | |/ _` | | | | | / __| __||
# ||  __/| | (_| | |_| | | \__ \ |_ |
# ||_|   |_|\__,_|\__, |_|_|___/\__||
# |               |___/             |
# '---------------------------------'
playlist_files:
- default: playlist
  template_variables:
    libraries: Films, TV Shows
# .--------------------------------------------------------------------.
# |  ____ _       _           _   ____       _   _   _                 |
# | / ___| | ___ | |__   __ _| | / ___|  ___| |_| |_(_)_ __   __ _ ___ |
# || |  _| |/ _ \| '_ \ / _` | | \___ \ / _ \ __| __| | '_ \ / _` / __||
# || |_| | | (_) | |_) | (_| | |  ___) |  __/ |_| |_| | | | | (_| \__ \|
# | \____|_|\___/|_.__/ \__,_|_| |____/ \___|\__|\__|_|_| |_|\__, |___/|
# |                                                          |___/     |
# '--------------------------------------------------------------------'
settings:                                           # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 1
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: sync
  default_collection_order:
  minimum_items: 1
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 7
  missing_only_released: true
  show_unconfigured: true
  show_unmanaged: true
  show_filtered: true
  show_options: true
  show_missing: false
  only_filter_missing: false
  show_missing_assets: false
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_report: true
  custom_repo:
  verify_ssl: true
  playlist_exclude_users:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg                    # Default is jpg. webp or png are also available
  overlay_artwork_quality: 75                      # Default is 75 if left blank, otherwise, for jpg or webp, going above 95 not recommended as excessive file sizes could be created and then not able to be uploaded to plex

```
