### DISCUSSION TITLE
Collection attribute 'plex_search' OR statement

### DISCUSSION THREAD

**Discussion by zpz5HAU-tgc3fgw2xwr** [meisnate12/Plex-Meta-Manager#227] [Q&A] [answered]
This is the collection I'm trying to modify right now:
```
"Cartoon Network":
    plex_search:
      network: Cartoon Network
      studio.begins: Cartoon Network
```
This currently results in a search for Network: Cartoon Network **AND** Studio.begins: Cartoon Network.

I need to create a search for Network: Cartoon Network **OR** Studio.begins: Cartoon Network.

**Comment by meisnate12** [comment, marked as answer]
try this
```yaml
"Cartoon Network":
    network: Cartoon Network
    studio.begins: Cartoon Network
```

**Reply by zpz5HAU-tgc3fgw2xwr** [reply]
Didn't realize I could do that... would you recommend this method over plex_search?

**Reply by meisnate12** [reply]
you can do one line plex_search without plex_search. your essentially just doing this basically
```yaml
"Cartoon Network":
    plex_search:
      network: Cartoon Network
    plex_search:
      studio.begins: Cartoon Network
```

you cant have multiple keys of the same name thats why you can't do a full second plex_seach but you can do a single line one with it.

All in all they run the exact same just formated differently
