### DISCUSSION TITLE
How to avoid "moving" items in collections?

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#2363] [Q&A]
Hi all,

coming from [here](https://github.com/Kometa-Team/Kometa/discussions/1046).
I use kometa via docker in a unraid system.

I now have this config for trakt-liked-lists and its works ok on small liked lists (about 10-50 items)

```
templates:
  template4TraktLikedLists:
    trakt_list_details: <<value>>
    sort_title: +++06_4_<<collection_name>>
    collection_order: custom

dynamic_collections:
  Trakt Liked Lists:          # This name is the mapping name
    template: template4TraktLikedLists
    type: trakt_liked_lists
    data: me
```

unfortunately, when a liked list is very long, say over 500-1000 items, my plex server tends to freeze and I got hundrets of those messages in my plex logs:

> Waited over 10 seconds for a busy database; giving up.

or even

> Saving activity history aborted with DB exception: std::exception

As soon as I kill the kometa docker, the plex server works fine again.

The issue seems to be with _trillions_ of those entries in the kometa log, which seems to overcharge the plex server:

```
| Moving Gefährliche Schönheit - Die Kurtisane von Venedig (1998) after Im Zwielicht (1998)          |
| Moving Der Gejagte (1998) after Gefährliche Schönheit - Die Kurtisane von Venedig (1998)           |
| Moving Der Pferdeflüsterer (1998) after Der Gejagte (1998)                                         |
| Moving Gia - Der Preis der Schönheit (1998) after Der Pferdeflüsterer (1998)                       |
| Moving Buffalo '66 (1998) after Gia - Der Preis der Schönheit (1998)                               |
| Moving Oscar und Lucinda (1997) after Buffalo '66 (1998)                                           |
| Moving Der Boxer (1997) after Oscar und Lucinda (1997)                                             |
| Moving Kundun (1998) after Der Boxer (1997)                                                        |
| Moving Wag the Dog - Wenn der Schwanz mit dem Hund wedelt (1998) after Kundun (1998)               |
| Moving Jackie Brown (1997) after Wag the Dog - Wenn der Schwanz mit dem Hund wedelt (1998)         |
| Moving Besser geht's nicht (1997) after Jackie Brown (1997)                                        |
| Moving Apostel! (1998) after Besser geht's nicht (1997)                                            |
| Moving Harry außer sich (1998) after Apostel! (1998)                                               |
| Moving Amistad - Das Sklavenschiff (1997) after Harry außer sich (1998)                            |
| Moving Good Will Hunting: Der gute Will Hunting (1997) after Amistad - Das Sklavenschiff (1997)    |
| Moving Die unsichtbare Falle (1998) after Good Will Hunting: Der gute Will Hunting (1997)          |
```

So, how do I solve this issue?

**I want the liked lists sorted as they come from trakt.tv, so I guess its "custom".**

but why does kometa sort those lists then (whilst moving each item) ? and how can I make those process lightwighter?

Thank you very much for any ideas/hints!

**Comment by chazlarson** [comment]
They're being moved because with `collection_order: custom` you are telling Kometa to put them into a particular arbitrary order.

If you want the items in the collection in a particular arbitrary order, then Kometa has to move them into that order.

**Reply by gitttt54** [reply]
Thank you, but I don't want the collection in a particular arbitrary order, I want the order from the trakt user who did the list.

How would I tell Kometa to stop moving the items and taking the list as it is?

**Reply by chazlarson** [reply]
It's a "particular arbitrary order" in that it is not an order that Kometa can just hand to Plex like `release`, `alpha`, or some other things in [this list](https://kometa.wiki/en/nightly/files/builders/plex/#sort-options).

**Reply by gitttt54** [reply]
Ah, I guess, I now understand what you said, thank you. 
So there is no way to not have Kometa move the items beside setting a defined order like "`release`, `alpha`, or some other things in [this list](https://kometa.wiki/en/nightly/files/builders/plex/#sort-options).".

Which results in either destroy the trakt order which is set by the trakt user, by overwriting his/her order, or having kometa killing my server while endlessly ordering every item on every collection run again and again....

hmmm....I have no idea what would be a better solution right now ;-(

**Reply by chazlarson** [reply]
I just ran some tests, if it's useful.

```
templates:
  template4TraktLikedLists:
    trakt_list_details: <<value>>
    sort_title: +++06_4_<<collection_name>>
#     collection_order: custom                    ## moving occurs
#     collection_order: release                   ## NO moving occurs
#     collection_order: alpha                     ## NO moving occurs
#     collection_order: added.asc                 ## moving occurs
#     collection_order: added.desc
#     collection_order: audience_rating.asc       ## moving occurs
#     collection_order: audience_rating.desc
#     collection_order: bitrate.asc               ## moving occurs
#     collection_order: bitrate.desc
#     collection_order: content_rating.asc        ## NO moving occurs
#     collection_order: content_rating.desc
#     collection_order: critic_rating.asc         ## moving occurs
#     collection_order: critic_rating.desc
#     collection_order: duration.asc              ## moving occurs
#     collection_order: duration.desc
#     collection_order: originally_available.asc  ## NO moving occurs
#     collection_order: originally_available.desc
#     collection_order: plays.asc                 ## moving occurs
#     collection_order: plays.desc
#     collection_order: progress.asc              ## moving occurs
#     collection_order: progress.desc
#     collection_order: release.asc               ## NO moving occurs
#     collection_order: release.desc
#     collection_order: resolution.asc            ## moving occurs
#     collection_order: resolution.desc
#     collection_order: title.asc                 ## moving occurs
#     collection_order: title.desc
#     collection_order: user_rating.asc           ## moving occurs
#     collection_order: user_rating.desc
#     collection_order: viewed.asc                ## moving occurs
#     collection_order: viewed.desc
#     collection_order: year.asc                  ## NO moving occurs
#     collection_order: year.desc
#     collection_order: random                    ## moving occurs

dynamic_collections:
  Trakt Liked Lists:          # This name is the mapping name
    template: template4TraktLikedLists
    type: trakt_liked_lists
    data: me
```

Like lots of things related to Kometa, there are tradeoffs.  Perhaps you can schedule things to happen less frequently.

If you truly have **trillions** of these moves happening, you probably need to take a look at the value added by doing this.
