### DISCUSSION TITLE
Overlay transparency adjustment for resolution & audio_codec

### DISCUSSION THREAD

**Discussion by miaLDN** [meisnate12/Plex-Meta-Manager#2442] [General]
Is there a way to adjust the transparency of the “dovetailed” overlays?  I’d like to increase the transparency (reduce the alpha channel to a lower value than the default `0x99`), so that more of the poster image shows through.

I understand how the resolution/audio_codec overlays are constructed.

In the default files `0x99` may be a constant when the combined (dovetail) image is being generated?  Or is there a way to override, or do I need to make my own templates etc?

``` yml
09)
    overlay_files:
    - default: audio_codec                                # FLAC, DTS-X, TrueHD, etc. style: standard/compact. compact is default
#      template_variables:
#        back_color: "#0000006f"    #Dovetail transparency goes wrong     # #RRGGBBAA - AA is transparency; 00 [transparent] to FF [opaque] {default 99}
    - default: resolution                                 # 4K HDR, 1080P FHD, etc.
#      template_variables:
#        back_color: "#0000006f"     #Dovetail transparency goes wrong    # #RRGGBBAA - AA is transparency; 00 [transparent] to FF [opaque] {default 99}
```
