### DISCUSSION TITLE
How to set collections so that they are always tagged last in Plex metadata?

### DISCUSSION THREAD

**Discussion by klouden0** [meisnate12/Plex-Meta-Manager#2528] [Q&A]
Sorry if this has been asked already, I am fairly new to kometa and I've been having trouble finding a solution.

In my Kometa config file i have the following set:
```
libraries:
  Movies:
    collection_files:
    - default: basic
    - default: imdb
    - default: season
    - file: config/Movies.yml
    remove_overlays: false
#    overlay_files:
#    - default: resolution
....
later in the file
....
settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
```

In my Movies.yml I have a bunch of different collection subtypes. Essentially what I want is for the "Decade Genre" based collections to always be tagged last in Plex; however, even if I delete the collection and rerun the config they are added first:
![image](https://github.com/user-attachments/assets/bf6521bc-e964-40a2-9f6b-23be2aeaaf93)

My Movies.yml contains the following templates:
```
    Decade:
        plex_search:
          genre: <<genre>>
          decade: <<year>>
#        url_poster: <<poster>>
        sort_title: zzz_<<collection_name>>
        collection_order: custom

```
and under collections I've specified:
```
  70's Horror:
    template: {name: Decade, year: 1970, genre: Horror}
  70's SciFi:
    template: {name: Decade, year: 1970, genre: Science Fiction}`
```
    
It doesn't seem to matter if I put the decade based collections at the top of the Movies.yml or the bottom. Whenever I delete the collections and reapply the configuration, it readds the decade based collections as the first tag in the Plex metadata.

Is there a way to set it so that they are always last. I am hoping this is just something simple I am overlooking.

Thanks.
