### DISCUSSION TITLE
Smart collections based on other smart collections?

### DISCUSSION THREAD

**Discussion by bigdork** [meisnate12/Plex-Meta-Manager#256] [Q&A]
Prior to smart collections, you can create collections based on "static" collections.
For example, let's say I have a "Kids Animation" collection based on a whole host of variables. I'd like a variant of this collection "Good Kids Animation" that filters the "Kids Animation" collection to only have those rated 7/10 or higher. With "static" collections, it's simple:
```
  Good Kids Animation:
    plex_search:
      collection: Kids Animation
      audience_rating.greater: 6.99
```

How to keep this functionality if I were to make "Kids Animation" a smart collection?

**Comment by meisnate12** [comment]
`smart_filter` can take `collection` as an attribute but that only works if the original collection is a normal collection. If it is a smart collection you would just create the original smart collection again with additional filters.

**Reply by bigdork** [reply]
It currently is not, but I'm trying to plan out migration to smart collections. With all my movies in one library, for organization I have collected Kids movies into one of two collections, Kids Animation and Kids Movies. In my config, I create them first and use `collection.not` with most of my other collections to exclude them in one go. I've done this kind of thing elsewhere with `collection:` too, like "Best of the 70's" based on the"1970s," things like that. `collection` and `collection.not` means I can do a lot of work with a single line...

It boils down to the fact I have a massive library and use collections to "chunk" it out into meaningful groups for people to browse with. Running the script takes hours and hours, so I've used `collection` and `collection.not` extensively to "optimize" runtime - essentially do a bunch of work at once and then build smaller sub-collections off that. 

I really want smart collections, so it seems I'll have to just re-think pretty much everything (templates and collections) to make it work.  Maybe with smart collections runtime won't be as big a concern. I'm just now playing with it so I'll see. I understand this is kind-of an edge use case and smart collections are not "real" collections, so it's not a huge deal. I'm not going to make the ask of you, I'll put the time in.

**Reply by meisnate12** [reply]
how are you collecting the items for  Kids Animation and Kids Movies whats their config look like?

You basically have to include their exclusion criteria for each other smart collection. It'll be easy for me to help you convert it over I really don't mind helping

**Reply by bigdork** [reply]
It's not that big of a deal, honestly. This could probably use a little rewrite anyway, now that I'm looking at this it doesn't look all that complicated. I do a similar setup for "Mature Animation" and "Anime," which are also excluded from most other collections. 

Below, I've simplified a bit (for clarity's sake, I do use templates), but here's a list with some examples including a couple "sub-collections" using `collection:` or `collection.not:`. 

Open to suggestions, but again you've got better things to burn braincells on. :D

```
collections:
  Kids Animation:
    plex_search:
      genre: Family, Children
      genre.and: Animation
      genre.not: Anime
      content_rating: Approved, G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
  Kids Movies:
    plex_search:
      genre: Family, Children
      genre.not: Anime, Animation
      content_rating: Approved, G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
  Mature Animation:
    plex_search:
      collection.not: Kids Animation, Kids Movies
      genre: Animation
      genre.not: Anime
  Anime:
    plex_search:
      collection.not: Kids Animation, Kids Movies, Mature Animation
      genre: Anime
  Good Kids Animation:
    plex_search:
      collection: Kids Animation
      audience_rating.greater: 6.99
  SomeOtherCollection:
    plex_search:
      collection.not: Anime, Kids Animation, Kids Movies, Mature Animation
      other_search_paramaters...
  Vintage SomeOtherCollection:
    plex_search:
      collection: SomeOtherCollection
      year.less: 2000
```

**Reply by meisnate12** [reply]
```yaml
collections:
  Kids Animation:
    smart_filter:
      all:
        any:
          - genre: Family, Children
          - content_rating: Approved, G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre: Animation
        genre.not: Anime
  Kids Movies:
    smart_filter:
      all:
        any:
          - genre: Family, Children
          - content_rating: Approved, G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre.not: Anime, Animation
  Mature Animation:
    smart_filter:
      all:
        any:
          all:
            - genre.not: Family, Children
            - content_rating.not: Approved, G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre: Animation
        genre.not: Anime
```

so I got through that and then realized that it was getting more difficult and hard an idea you could label them yourself and ignore said label like this 

```yaml
collections:
  Kids Animation:
    smart_filter:
      all:
        any:
          - genre: Family, Children
          - content_rating: Approved, G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre: Animation
        genre.not: Anime
    item_label: Kids Animation
  Kids Movies:
    smart_filter:
      all:
        any:
          - genre: Family, Children
          - content_rating: Approved, G, E, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre.not: Anime, Animation
    item_label: Kids Movies
  Mature Animation:
    smart_filter:
      all:
        label.not: Kids Animation, Kids Movies
        genre: Animation
        genre.not: Anime
    item_label: Mature Animation
  Anime:
    smart_filter:
      all:
        label.not: Kids Animation, Kids Movies, Mature Animation
        genre: Anime
    item_label: Anime
  Good Kids Animation:
    smart_filter:
      all:
        label: Kids Animation
        audience_rating.gte: 7
  SomeOtherCollection:
    smart_filter:
      all:
        label.not: Anime, Kids Animation, Kids Movies, Mature Animation
        other_search_paramaters...
    item_label: SomeOtherCollection
  Vintage SomeOtherCollection:
    plex_search:
      label: SomeOtherCollection # or just mimic other_search_paramaters... and add year if you don't want more labels
      year.lt: 2000
```

**Reply by bigdork** [reply]
Ah, I had not considered labels! Perfect - thank you sir! Are the labels added/removed with `sync_mode: sync` as well?

**Reply by meisnate12** [reply]
so have to burst the bubble unfortunately the above will not work atm as I have to figure out a way to access the items of a smart collection

**Reply by bigdork** [reply]
No worries. Haven't had time to dig into this yet anyway. I can still do smart collections with minimized repetitiveness/clutter with some new templates. :D

**Reply by meisnate12** [reply]
and ill try and get `item_labels` working lol

**Reply by bigdork** [reply]
OK, strangeness with smart collections in general... Maybe I need a better understanding of Plex filters or they don't function like I think?

So, um, what? (for clarity, references to "Smart" is a PMM-created Smart Collection, "Filter" is a Plex-filter-created Smart Collection.)
![kidscollections](https://user-images.githubusercontent.com/58086116/118993118-3eaecf80-b953-11eb-8754-1a81d5501c9a.png)

For Kids Animation, my thought of how a filter should work is:
>    Genre = Children **or** Family **and** Animation, but **not** Anime 
>   **and** any Content Rating = E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
>   - Ex: A movie missing both genres "Children/Family," rated "G," and genre "Animation" should _not_ match.
>   - Ex: A movie with genre "Children," rated "PG-13," and genre "Animation" should _not_ match.
>   - Ex: A movie with genre "Family", rated "G," and genre "Animation" _should_ match.
>   - Ex: A movie with genre "Children", rated "G," and genre "Anime" should _not_ match.
>   - Ex: A movie with genre "Family", rated "G," and missing genre "Animation" should _not_ match.

For Kids Movies, similar but slightly different:
>   Genre = Children **or** Family but **not** Animation **or** Anime
>   **and** any Content Rating = E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
>   - Ex: A movie missing both genres "Children/Family," rated "G," and missing genre "Animation" should _not_ match.
>   - Ex: A movie with genre "Children," rated "PG-13," and genre "Animation" should _not_ match.
>   - Ex: A movie with genre "Family", rated "G," and genre "Animation" should _not_ match.
>   - Ex: A movie with genre "Children", rated "G," and genre "Anime" should _not_ match.
>   - Ex: A movie with genre "Family", rated "G," and missing genre "Animation" _should_ match.

PMM's "traditional" Plex search seems to handle these properly:
```
| Processing Plex Search: genre(Family OR Children) 
|                         AND genre.and(Animation) 
|                         AND genre.not(Anime)
|                         AND content_rating(E OR G OR PG OR TV-G OR TV-PG OR TV-Y OR TV-Y7 OR TV-Y7-FV)

| Processing Plex Search: genre(Children OR Family)
|                         AND genre.not(Animation OR Anime)
|                         AND content_rating(E OR G OR PG OR TV-G OR TV-PG OR TV-Y OR TV-Y7 OR TV-Y7-FV)
```
Plex filters handle this by allowing multiple "any" rule groups under in an "all" group, but PMM errors for multiple `any:`s. That said, the Plex filters I built for comparison contain far less movies, but I don't understand why? 

Filters for Kids Animation PMM Smart and Plex Filter:
![kidsanim-smart](https://user-images.githubusercontent.com/58086116/118992772-ef689f00-b952-11eb-9a16-ea5f3b498b5d.png)
![kidsanim-filter](https://user-images.githubusercontent.com/58086116/118992781-f1caf900-b952-11eb-88cc-15d4d4622615.png)
And for Kids Movies:
![kidsmov-smart](https://user-images.githubusercontent.com/58086116/118992844-ff807e80-b952-11eb-8a68-7541744058b8.png)
![kidsmov-filter](https://user-images.githubusercontent.com/58086116/118992852-014a4200-b953-11eb-8272-df929199bb62.png)

So, in summary:
1. Plex filters are ... off? Or, my understanding of them is...
 - Ex: "101 Dalmations" is not picked up by the "Kids Animation" Plex Filter, even though it has Content Rating=G, Genre=Family, and Genre=Animation. Should be picked up by the collections in PMM (it is) PMM Smart (it is) and the Plex filter (it isn't?). 
 - Ex: "3 Ninjas" is not picked up by the "Kids Movies" Plex filter, even though it has Content Rating=PG, Genre=Family, and does not include either genre Animation/Anime. Should be picked up by collections in PMM (it is) PMM Smart (it is) and the Plex filter (it isn't?). 
2. I would think PMM Smart collections need a way to do multiple `any:`s like Plex filters, although the Plex filter doesn't work as I expect, so maybe no? For example:
```
    all:
        any:
          genre: Children, Family
        any:
          content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre: Animation
        genre.not: Anime
```
3. PMM Smart Collection for "Kids Movies" includes animated movies for some reason, but I see no anime, so it's ignoring part of the `genre.not:`?

Configs below:
```
  Kids Animation Smart:
    test: true
    sort_title: +2 Kids Animation
    content_rating: Collection
    smart_filter:
      all:
        any:
          genre: Children, Family
#        any:
          content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre: Animation
        genre.not: Anime
      sort_by: title.asc
    file_poster: config/asset/Kids Animation.png
    summary: "A collection of all animated movies safe for kids, with a rating of PG or below.\n(Sorted alphabetically, refreshed automatically.)"
  Kids Movies Smart:
    test: true
    sort_title: +2 Kids Movies
    content_rating: Collection
    smart_filter:
      all:
        any:
          genre: Children, Family
 #       any:
          content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre.not: Animation, Anime
      sort_by: title.asc
    file_poster: config/asset/Kids Movies.png
    summary: "A collection of all non-animated movies safe for kids with a rating of PG or below.\n (Sorted alphabetically, refreshed automatically.)"
  Kids Animation:
    test: true
    sort_title: +2 Kids Animation
    content_rating: Collection
    collection_order: alpha
    file_poster: config/asset/Kids Animation.png
    plex_search:
      genre: Family, Children
      genre.and: Animation
      genre.not: Anime
      content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
    summary: "A collection of all animated movies safe for kids, with a rating of PG or below.\n(Sorted alphabetically, refreshed daily.)"
  Kids Movies:
    test: true
    sort_title: +2 Kids Movies
    content_rating: Collection
    collection_order: alpha
    file_poster: config/asset/Kids Movies.png
    plex_search:
      genre: Children, Family
      genre.not: Animation, Anime
      content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
    summary: "A collection of all non-animated movies safe for kids with a rating of PG or below.\n (Sorted alphabetically, refreshed daily.)"
```

**Reply by meisnate12** [reply]
so first of all your `filters` are using fantasy not family so im sure thats throwing your numbers way off.

second so yes YAML files cannot have two of the same keys at the same level so i cant have multiple `any`. What i did to get around this is to put all the `any`'s in a list with each list item as a different `any` example below:

```yaml
 Kids Animation Smart:
    test: true
    sort_title: +2 Kids Animation
    content_rating: Collection
    smart_filter:
      all:
        any:
          - genre: Children, Family
          - content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre: Animation
        genre.not: Anime
      sort_by: title.asc
    file_poster: config/asset/Kids Animation.png
    summary: "A collection of all animated movies safe for kids, with a rating of PG or below.\n(Sorted alphabetically, refreshed automatically.)"
```

**Reply by bigdork** [reply]
> so first of all your `filters` are using fantasy not family so im sure thats throwing your numbers way off.

Oh, FFS. :(

**Reply by meisnate12** [reply]
Btw item_label should now work for smart collections

**Reply by bigdork** [reply]
Updated my ridiculously stupid typo in the "Filter" collections, as well as updated my PMM Smart collections as suggested, deleted the 4 PMM-created collections and re-ran - We are good to go!
![Screen Shot 2021-05-20 at 1 43 11 PM](https://user-images.githubusercontent.com/58086116/119024835-83e1fa00-b971-11eb-93f0-77783d32fba4.png)

Side note - "Smart Collections" are **EXPONENTIALLY** faster to create than "Traditional" ones! For large collections, this is a no-brainer and **very** welcome. Now, to figure out the most efficient way to base collections on collections!
```
  Kids Animation Smart:
    test: true
    sort_title: +2 Kids Animation
    content_rating: Collection
    smart_filter:
      all:
        any:
          - genre: Children, Family
          - content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre: Animation
        genre.not: Anime
      sort_by: title.asc
    file_poster: config/asset/Kids Animation.png
    summary: "A collection of all animated movies safe for kids, with a rating of PG or below.\n(Sorted alphabetically, refreshed automatically.)"
  Kids Movies Smart:
    test: true
    sort_title: +2 Kids Movies
    content_rating: Collection
    smart_filter:
      all:
        any:
          - genre: Children, Family
          - content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
        genre.not: Animation, Anime
      sort_by: title.asc
    file_poster: config/asset/Kids Movies.png
    summary: "A collection of all non-animated movies safe for kids with a rating of PG or below.\n (Sorted alphabetically, refreshed automatically.)"
  Kids Animation:
    test: true
    sort_title: +2 Kids Animation
    content_rating: Collection
    collection_order: alpha
    file_poster: config/asset/Kids Animation.png
    plex_search:
      genre: Family, Children
      genre.and: Animation
      genre.not: Anime
      content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
    summary: "A collection of all animated movies safe for kids, with a rating of PG or below.\n(Sorted alphabetically, refreshed daily.)"
  Kids Movies:
    test: true
    sort_title: +2 Kids Movies
    content_rating: Collection
    collection_order: alpha
    file_poster: config/asset/Kids Movies.png
    plex_search:
      genre: Children, Family
      genre.not: Animation, Anime
      content_rating: E, G, PG, TV-G, TV-PG, TV-Y, TV-Y7, TV-Y7-FV
    summary: "A collection of all non-animated movies safe for kids with a rating of PG or below.\n (Sorted alphabetically, refreshed daily.)"
```
