### DISCUSSION TITLE
Suggestion: Multithread the convert?

### DISCUSSION THREAD

**Discussion by efaden** [meisnate12/Plex-Meta-Manager#258] [Ideas]
It seems like it is taking a really long time to cache all of my movies and shows.  I am guessing it is doing an HTTP call PER movie/show.  I am curious if you have thought about threading it or spawning multiple HTTP requests to make the cache building go faster?  Just a thought.  It seems like I am adding one item to the cache each 3 to 5 seconds.

**Comment by meisnate12** [comment]
i feel like threading would overload plex with requests plus once you finally complete your cache things should be much much quicker

**Reply by efaden** [reply]
Is it the requests to plex that takes time or is it the requests to imdb/tmdb/etc?  If it's plex you may be right, that may kill plex.  I'm guessing there isn't a way to query it faster.   At 5 seconds per and 1000 movies that's over an hour.   Can you bundle the requests, or something else to speed it up?

**Reply by meisnate12** [reply]
to be honest idk why yours takes so long I have 2k movies and from a blank cache it only takes a few minutes to fully cache

**Reply by efaden** [reply]
Hmmm.  Any thoughts on where to look?  I get about one of these every 5 seconds.  Seemed slow to me also.

Cache  |  +  | plex://movie/ID          | TMDb ID: ### | NAME |

**Reply by efaden** [reply]
FYI, tried running in docker and locally.  Same slowness.  This is my config.yml

```
libraries:
      Movies:
            metadata_path:
                - file: config/Movies.yml
            #- git: meisnate12/MovieCharts         # https://github.com/meisnate12/Plex-Meta-Manager-Configs
      # - git: meisnate12/Studios
      # - git: meisnate12/IMDBGenres
      # - git: meisnate12/People
      TV Shows:
            metadata_path:
                - file: config/TV Shows.yml
            #- git: meisnate12/ShowCharts
      # - git: meisnate12/Networks

settings:
      cache: true
      cache_expiration: 60
      asset_directory: config/assets
      asset_folders: true
      assets_for_all: false
      sync_mode: sync
      show_unmanaged: true
      show_filtered: false
      show_missing: true
      save_missing: true
      run_again_delay: 2

plex:                                           # Can be individually specified per library as well
      token: <APIKEY>
      url: http://localhost:32400
      timeout: 60
      clean_bundles: false
      empty_trash: false
      optimize: false

tmdb:
      apikey: <KEY>
      language: en

tautulli:                                       # Can be individually specified per library as well
      url: http://localhost:8181
      apikey: <KEY>

omdb:
      apikey: KEY

trakt:
      client_id: CLIENT ID
      client_secret: SECRET
      authorization:
    # everything below is autofilled by the script
            access_token: 
            token_type: 
            expires_in: 
            refresh_token: 
            scope: 
            created_at: 
```
