### DISCUSSION TITLE
"The 'Movies' library config contains collections definitions"

### DISCUSSION THREAD

**Discussion by Abcmsaj** [meisnate12/Plex-Meta-Manager#2603] [Q&A] [answered]
Sorry - didn't want to raise this as an issue in case it's something I'm doing wrong. But since updating to v2.2.0, I've had this error. Downgrading to v2.1.0 fixes it with my current config. I had:

```yaml
libraries: 
  Movies:

    collections:
      remove_overlays: false   # Set this to true to remove all overlays
      #reapply_overlays: true
    collection_files:
    - file: config/movie-collections.yml
    - pmm: franchise
      template_variables:
        use_separator: false
    - pmm: content_rating_cs
      template_variables:
        use_separator: false
    - pmm: imdb
    - pmm: genre
      template_variables:
        use_separator: false
    - pmm: oscars

    overlay_files:
    - pmm: resolution     # resolution for movies

    - pmm: ratings     # rating for movies
      template_variables:
        rating1: critic     # critic score from RT
        rating1_image: rt_tomato
        rating2: audience     # audience score from RT
        rating2_image: rt_popcorn
        rating3: user     # user score from IMDB
        rating3_image: letterboxd
        horizontal_position: right

    - pmm: commonsense
      template_variables:
        horizontal_align: left
        vertical_align: top
        vertical_offset: 150

    operations:
      mass_critic_rating_update: mdb_tomatoes
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: mdb_letterboxd
      mass_content_rating_update: mdb_commonsense
      #delete_collections:
```

initially for my config. After checking the docs, it looks like `pmm` might not be used anymore in favour of `default` so I changed it to:

```yaml
libraries:
  Movies:

    collections:
      remove_overlays: false   # Set this to true to remove all overlays
      #reapply_overlays: true
    collection_files:
    - file: config/movie-collections.yml
    - default: franchise
      template_variables:
        use_separator: false
    - default: content_rating_cs
      template_variables:
        use_separator: false
    - default: imdb
    - default: genre
      template_variables:
        use_separator: false
    - default: oscars

    overlay_files:
    - default: resolution     # resolution for movies

    - default: ratings     # rating for movies
      template_variables:
        rating1: critic     # critic score from RT
        rating1_image: rt_tomato
        rating2: audience     # audience score from RT
        rating2_image: rt_popcorn
        rating3: user     # user score from IMDB
        rating3_image: letterboxd
        horizontal_position: right

    - default: commonsense
      template_variables:
        horizontal_align: left
        vertical_align: top
        vertical_offset: 150

    operations:
      mass_critic_rating_update: mdb_tomatoes
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: mdb_letterboxd
      mass_content_rating_update: mdb_commonsense
      #delete_collections:
```

but each time Kometa runs, it errors immediately with the error: `1 | The 'Movies' library config contains collections definitions. These belong in external YAML files, not in the config.yml.`

From what I can see, I am referencing an external yaml file, but the collection config is not included inside my config.yaml, is it? Any help appreciated... thanks

**Comment by YozoraXCII** [comment, marked as answer]
`    collections:`

this line does not belong in a config.yml, I don't know why you have it there.

`collections:` is used in a Collection File (such as in your `- file: config/movie-collections.yml`), it does not belong in `config.yml`

you also have these within your collections line:

```
      remove_overlays: false   # Set this to true to remove all overlays
      #reapply_overlays: true
```

the correct logic would be:
```
libraries:
  Movies:
    remove_overlays: false   # Set this to true to remove all overlays
    #reapply_overlays: true
    collection_files:
    - file: config/movie-collections.yml
    - default: franchise
      template_variables:
        use_separator: false
# rest of your config.yml
```
