### DISCUSSION TITLE
Int has No Attribute Key on Plex Genre Search....

### DISCUSSION THREAD

**Discussion by efaden** [meisnate12/Plex-Meta-Manager#262] [Q&A]
Title says it all.  Not really sure why I am getting this error.  I am trying to search plex by genre and add that to a few other lists.  I am getting an error "int has no attribute key".   Thoughts?  If I disable the plex genre search it works fine.

Config
```
templates:
  PlexSearch_Genre:
    plex_search:
      genre: <<genre>>
    url_poster: <<poster>>
    sort_title: +++++++_<<collection_name>>
    smart_label: title.asc

  Kid's Movies:
    template: {name: PlexSearch_Genre, genre: Family, poster: https://theposterdb.com/api/assets/53059}
    trakt_list:
      - https://trakt.tv/users/hdlists/lists/children-s-animated-movies-from-1950-to-today
    imdb_list:
        url: https://www.imdb.com/search/title/?genres=family
        limit: 100
    summary: Children's Movies
```

Error
```

| Scanning Kid's Movies Collection                                                                   |
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Processing Trakt List: https://trakt.tv/users/hdlists/lists/children-s-animated-movies-from-1950-to-today |
|                                                                                                    |
| Processing IMDb List: 100 Items at https://www.imdb.com/search/title/?genres=family                |
| Processed 100 IMDb IDs                                                                             |
|                                                                                                    |
| Processing Plex Search: genre(Family)                                                              |
| Unknown Error: 'int' object has no attribute 'key'
```

With Debug On
``` 
| Data: {'genre': ['Family']}                                                                        |
| Processing Plex Search: genre(Family)                                                              |
| Search: {'genre': ['Family']}                                                                      |
| Traceback (most recent call last):                                                                 |
|   File "plex_meta_manager.py", line 372, in run_collection                                         |
|     builder.collect_rating_keys(movie_map, show_map)                                               |
|   File "/opt/Plex-Meta-Manager/modules/builder.py", line 1294, in collect_rating_keys              |
|     if "plex" in method:                                add_rating_keys(self.library.get_items(method, value)) |
|   File "/opt/Plex-Meta-Manager/modules/builder.py", line 1267, in add_rating_keys                  |
|     self.rating_keys.extend([key for key in keys if key not in self.rating_keys])                  |
|   File "/opt/Plex-Meta-Manager/modules/builder.py", line 1267, in <listcomp>                       |
|     self.rating_keys.extend([key for key in keys if key not in self.rating_keys])                  |
|   File "/usr/local/lib/python3.8/dist-packages/plexapi/base.py", line 418, in __eq__               |
|     return other not in [None, []] and self.key == other.key                                       |
| AttributeError: 'int' object has no attribute 'key'                                                |
|                                                                                                    |
| Unknown Error: 'int' object has no attribute 'key'
```
