### DISCUSSION TITLE
Setting Sharing Labels

### DISCUSSION THREAD

**Discussion by j-ktz** [meisnate12/Plex-Meta-Manager#403] [Q&A]
I'm trying to use PMM to search for any movies with "horror" as the genre, or if they're in the "Horror" collection, and if so, label that movie with "horror" label so I can exclude this for kids when I share libraries. I'm looking at the Wiki, but not sure how to accomplish this. I don't need to create a collection, just add a label to items IN a collection or items with a specific genre.

**Comment by meisnate12** [comment]
```yaml
collections:
  label horror:
    build_collection: false
    plex_search:
      any:
        genre: horror
        collection: Horror
    item_label: horror
```
