### DISCUSSION TITLE
Remove Smart Label from Movies

### DISCUSSION THREAD

**Discussion by ghost** [meisnate12/Plex-Meta-Manager#415] [Q&A]
Hi,

I made a smart collection using smart labels, but now I no longer need this collection and want to remove it.

How do I remove the Label from all the Movies that were part of this collection (besides manually), so that the collection should then be empty (and then be deleted).

Thanks

**Comment by raleeper** [comment]
I had the same problem. The best I could come up with was to change the smart collection definition so that it selected exactly one movie. Something like:
```
    plex_search:
      all:
        title: Nosferatu
    smart_label: release.asc
    sync_mode: sync
```
Run Plex Media Manager to sync the collection. That will leave you with just one movie to manually clean up. I tried using search criteria that found nothing, but that caused an error and didn't update the collection.
