### DISCUSSION TITLE
smart collection creation based on imdb and plex

### DISCUSSION THREAD

**Discussion by Nexius2** [meisnate12/Plex-Meta-Manager#453] [Q&A]
Hello, is it possible to create a collection that gathers an imdb list and another plex smart collection?

something like

  Christmas Movies:
    template: {name: Holiday, holiday: Noël}
    imdb_list: https://www.imdb.com/list/ls000096828/
    plex_collection:  "Smart Christmas Collection"

thanks

**Comment by meisnate12** [comment]
not directly by linking the smart collection but you could use the same parameters in a plex search to do the same.

**Comment by Nexius2** [comment]
that's great !
I'm not sure about the syntax but I would say something like this?

  Christmas Movies:
    template: {name: Holiday, holiday: Noël}
    imdb_list: https://www.imdb.com/list/ls000096828/
    url_background: https://theposterdb.com/api/assets/48894/view?
    plex_search:
      title: 
        - santa 
        - christmas
        - sapin
        - noel
        - claus

**Reply by meisnate12** [reply]
yea it should work as long as the spacing is right

```yaml
collections:
  Christmas Movies:
    template: {name: Holiday, holiday: Noël}
    imdb_list: https://www.imdb.com/list/ls000096828/
    url_background: https://theposterdb.com/api/assets/48894/view?
    plex_search:
      title:
        - santa
        - Christmas
        - sapin
        - noel
        - claus
```
