### DISCUSSION TITLE
clear all tags

### DISCUSSION THREAD

**Discussion by Sir-Gavin** [meisnate12/Plex-Meta-Manager#480] [General]
hi guys is there a way to clear all tags and sharing in plex as ive messed-up

**Comment by meisnate12** [comment]
ok i just pushed this update to the develop branch to allow blank lists so run this collection after you update.

```yaml
collections:
  Clear All Tags:
    build_collection: false
    plex_all: true
    item_label.sync: 
```

`item_label.sync` is supposed to be blank to to represent syncing to no tags
