### DISCUSSION TITLE
Unknown Error: 'int' object has no attribute 'tmdbId'

### DISCUSSION THREAD

**Discussion by InsideOutElephant** [meisnate12/Plex-Meta-Manager#483] [Q&A] [answered]
Most collections raise this error when adding missing items to radarr:
Unknown Error: 'int' object has no attribute 'tmdbId'

CONFIG

```
templates:
  IMDb Genre:
    default:
      title: feature
      limit: 100
    imdb_list:
      - url: https://www.imdb.com/search/title/?title_type=<<title>>&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>
        limit: <<limit>>
      - url: https://www.imdb.com/search/title/?title_type=<<title>>&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>&sort=user_rating,desc
        limit: <<limit>>
    sort_title: +3_<<collection_name>>
    sync_mode: sync
    smart_label: random
collections:
  Action:
    template: { name: IMDb Genre, genre: action }
    summary: Action film is a genre wherein physical action takes precedence in the storytelling. The film will often have continuous motion and action including physical stunts, chases, fights, battles, and races. The story usually revolves around a hero that has a goal, but is facing incredible odds to obtain it.
  Adventure:
    template: { name: IMDb Genre, genre: adventure }
    summary: Adventure film is a genre that revolves around the conquests and explorations of a protagonist. The purpose of the conquest can be to retrieve a person or treasure, but often the main focus is simply the pursuit of the unknown. These films generally take place in exotic locations and play on historical myths. Adventure films incorporate suspenseful puzzles and intricate obstacles that the protagonist must overcome in order to achieve the end goal.
  
```

ERROR STACK (Below is specifically from adventure collection, however it is the same callstack as the other collection)
```
Traceback (most recent call last):
File "//plex_meta_manager.py", line 592, in run_collection|
  radarr_add, sonarr_add = builder.run_missing()|
File "/modules/builder.py", line 1751, in run_missing|
  added_to_radarr += self.library.Radarr.add_tmdb(missing_tmdb_ids, **self.radarr_details)|
File "/modules/radarr.py", line 96, in add_tmdb|
   logger.info(f"Already in Radarr | {movie.tmdbId:<6} | {movie.title}")|
AttributeError: 'int' object has no attribute 'tmdbId'
```

Sometimes the error is raised after adding some of the missing items, sometimes the error is raised before any missing items have been added.
