### DISCUSSION TITLE
Getting a template to accept multiple values formatted as list

### DISCUSSION THREAD

**Discussion by benfishbus** [meisnate12/Plex-Meta-Manager#489] [Q&A]
I have successfully used multiple comma-separated values in a template variable, but can't get a list of values to work the same way. My template includes a string-type collection filter (title.isnot) that can only accept multiple values in list form. Portions of yml file are below. I may ultimately wind up going a completely different way to build this collection, but I'd like to know whether multi-value lists should be usable in templates.

```
templates:
  Holiday:
    sync_mode: sync
    show_filtered: true
    tmdb_keyword: <<kw>>
    optional:
      filters:
        title.isnot: <<exclusions>>
    item_label: <<holiday>>
    item_radarr_tag: <<holiday>>

collections:
  Christmas:
    template:
      name: Holiday
      holiday: Christmas
      kw: 207317
      exclusions:
        - The Apartment
        - Ben Is Back
        - ...
```
