### DISCUSSION TITLE
imdb list not working

### DISCUSSION THREAD

**Discussion by Sir-Gavin** [meisnate12/Plex-Meta-Manager#493] [General]
i have the 

Martial Arts:
    template: {name: Genre, poster: https://theposterdb.com/api/assets/51773}
    imdb_list:
      - https://www.imdb.com/list/ls000099643/
      - https://www.imdb.com/list/ls068611186/
      - https://www.imdb.com/list/ls068378513/
      - https://www.imdb.com/list/ls090404120/
    summary: Martial Arts film is a sub-genre of action films that feature numerous martial arts combat between characters. These combats are usually the films' primary appeal and entertainment value, and often are a method of storytelling and character expression and development. Martial Arts are frequently featured in training scenes and other sequences in addition to fights. Martial Arts films commonly include other types of action, such as hand-to-hand combat, stuntwork, chases, and gunfights.  
  

in my movies config but it dont work any ideas

**Comment by meisnate12** [comment]
youd have to provide me with some info about how it didn't work maybe a log file

**Reply by Sir-Gavin** [reply]
sure what would you need im using Glasti1 Movie config
when its done running i dont have the Martial arts collection or anything which would use IMDB LINKS

**Reply by meisnate12** [reply]
in your config folder theres a log folder can you give me your meta.log

**Reply by Sir-Gavin** [reply]
it is running again at the moment does that matter to the logs

**Reply by Sir-Gavin** [reply]
ok

**Reply by meisnate12** [reply]
yes give me the meta.log.1 then

**Reply by Sir-Gavin** [reply]
which one i have .log then 1-9

**Reply by Sir-Gavin** [reply]
ok

**Reply by meisnate12** [reply]
thats just the 10 latest runs of pmm it keeps 10 at a time if your currently running pmm its actively logging to meta.log and that why i wanted meta.log.1 because it should be your most recent run before that one

**Comment by Sir-Gavin** [comment]
[meta.log.zip](https://github.com/meisnate12/Plex-Meta-Manager/files/7682079/meta.log.zip)

**Reply by meisnate12** [reply]
genre needs to be in the optional attribute of the Genre template and then it should work

**Reply by meisnate12** [reply]
```yaml
templates:
    Genre:
        plex_search:
          genre: <<genre>>
        url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: alpha
```
change the above section and add the optional attribute like below
```yaml
templates:
    Genre:
        optional:
         - genre
        plex_search:
          genre: <<genre>>
        url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: alpha
```
or you could just remove the plex_seach 

```yaml
templates:
    Genre:
        url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: alpha
```

or you could use a different file
