### DISCUSSION TITLE
Assets Directory

### DISCUSSION THREAD

**Discussion by joeflood89** [meisnate12/Plex-Meta-Manager#530] [General]
Hey,I'm getting the error asset warning: no poster or background found in an assets folder for ' ' 
I get this for all of my movies when trying to update posters but the collection poster updates without issue so it is seeng my assets folder. Any help would be appreciated.

**Comment by meisnate12** [comment]
are you following the naming scheme on the [Image Assets Page](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Image-Asset-Directory)?

* For **Movies** replace `ASSET_NAME` with the exact name of the folder the video file is stored in.
  * i.e. if you have `Movies/Star Wars (1977)/Star Wars (1977) [1080p].mp4` then your asset directory would look at either `assets/Star Wars (1977)/poster.png` or `assets/Star Wars (1977).png` for the poster. 
* For **Shows**, **Seasons**, and **Episodes** replace `ASSET_NAME` with the exact name of the folder for the show as a whole.
  * i.e. if you have `Shows/Game of Thrones/Season 1/Game of Thrones - S01E01.mp4` then your asset directory would look at either `assets/Game of Thrones/poster.png` or `assets/Game of Thrones.png` for the poster.

**Reply by joeflood89** [reply]
Hey thanks for the reply. 

So I've got config/assets/movies/Thor and Thor then holds poster.png for the collection and sub folders for each Thor movie which also contains poster.jpg or png for movie posters.

The world of script and commands is completely new to me so I am quite the beginner 🤣

**Reply by meisnate12** [reply]
so theres a change important to this coming in 1.14.0 I'm writing the wiki now can you wait till i finish and release that and we can pick this back up once I've detailed the change

also your problem might be your not scanning for `item_assets`

**Reply by joeflood89** [reply]
Yeah picking it up there would be great. I'll just pop in a couple pics of my config and you might have a quick scan to see if anything is missing if you wouldn't mind? Thanks again!

[image](https://user-images.githubusercontent.com/96377656/146887137-38d9f1af-6240-4f68-a90a-5a59b4caf7fe.jpeg)

![image](https://user-images.githubusercontent.com/96377656/146887180-e4419a5a-c81b-49ea-b228-6aaec8e7ae8f.jpeg)

![image](https://user-images.githubusercontent.com/96377656/146887217-375860f3-ff88-4631-9608-e5d1635e42b8.jpeg)

![image](https://user-images.githubusercontent.com/96377656/146887255-7349a5fe-92dc-46a8-897d-3e86a3cf6aeb.jpeg)

**Reply by joeflood89** [reply]
It doesn't work for any of my libraries, not just movie. That's just what I've been focusing on.

**Reply by JohnDoranNY** [reply]
I am having the same exact issue, except I am running flatfile  (ie: config/assets/ExactMovieFolderName.png)

config:

  cache: true
  cache_expiration: 60
  asset_directory: config/Assets
  asset_folders: false
  asset_depth: 2
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true

I've tried several settings...  it processes collection images but never movie images.. not one out of 2K available.  I can never get it to create directories either.  I am running the most current versions of Plex,PMM and python.  There are no errors in the logs.  I tried first for a day from a remote machine, then install pmm on plex server machine but with the same exact problems.  It worked for me in prior version of PMM but not since update to current version.  I've read the wiki a dozen times for assets but nothing I've tried seems to work.  Even tried running powershell as admin incase of write security access.  What am I doing wrong?

**Reply by chazlarson** [reply]
Assets are only applied to collections unless `assets_for_all: true` is present under the library operations, which tells PMM to check for individual items assets.

Assumptions:
`movies.yml` will create a collection called "My Cool Stuff" which does NOT have artwork defined.
"Star Wars" is in the library, with the movie file at:
```
/mnt/movies/Star Wars (1977) {imdb-tt0076759} {tmdb-11}/Star Wars (1977).mkv
```
With folders:
```
libraries:
  Movies:
    metadata_path:
      - file: config/movies.yml
settings:
  asset_directory: config/assets
  asset_folders: true
```
That will look for and apply `/config/assets/My Cool Stuff/poster.png` to the collection **only**.

Without folders:
```
libraries:
  Movies:
    metadata_path:
      - file: config/movies.yml
settings:
  asset_directory: config/assets
  asset_folders: false
```
That will look for and apply `/config/assets/My Cool Stuff.png` to the collection **only**.

Adding item assets:

With folders:
```
libraries:
  Movies:
    metadata_path:
      - file: config/movies.yml
    operations:
      assets_for_all: true
settings:
  asset_directory: config/assets
  asset_folders: true
```
That will look for and apply `/config/assets/My Cool Stuff/poster.png` to the collection, and `/config/assets/Star Wars (1977) {imdb-tt0076759} {tmdb-11}/poster.png` to the movie.

Without folders:
```
libraries:
  Movies:
    metadata_path:
      - file: config/movies.yml
    operations:
      assets_for_all: true
settings:
  asset_directory: config/assets
  asset_folders: false
```
That will look for and apply `/config/assets/My Cool Stuff.png` to the collection, and `/config/assets/Star Wars (1977) {imdb-tt0076759} {tmdb-11}.png` to the movie.

**Reply by JohnDoranNY** [reply]
I've done this repeatedly.. even now based on your sample (removed all other operations)

I have in config:

libraries:
############################# 2D Movies ############################# 
  Movies:
#################################################################### 
    metadata_path:
      - file: config/Charts/Movies.yml
    missing_path: config/Missing/Movies 2D.yml
    report_path: config/Reports/Movies 2D.yml
    operations:
      assets_for_all: true
#################################################################### 
settings:
#################################################################### 
  cache: true
  cache_expiration: 60
  asset_directory: config/assets  
  asset_folders: false
  asset_depth: 2
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: sync
  default_collection_order: release
  minimum_items: 1
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  show_unmanaged: false
  show_unconfigured: false
  show_filtered: false
  show_options: false
  show_missing: false
  only_filter_missing: false
  show_missing_assets: false
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users:
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: false
  check_nightly: false
  custom_repo:

With this configuration it adds some collections, zero movies (which are named exactly the same as the movie folder name, with ext), and never creates asset folders


Also I cannot get it to delete zero item collections even with "delete_collections_with_less: 1" under operations but that's a separate issue.

**Comment by chazlarson** [comment]
Can you format that as code?  With the indentation stripped there's no way to know what the issue might be.

The collection thing may be that the collections you are seeking to delete are "smart collections", which don't have item counts.

Perhaps you could provide a full log showing this happening?  That log would contain a redacted copy of the config.

**Reply by JohnDoranNY** [reply]
I think I got it working now... importing but not creating folders... and not sure what changed that it works sorta now

**Comment by JohnDoranNY** [comment]
```
libraries:
############################# 2D Movies ############################# 
  Movies:
#################################################################### 
    metadata_path:
      - file: config/Charts/Movies.yml
    missing_path: config/Missing/Movies 2D.yml
    report_path: config/Reports/Movies 2D.yml
    operations:
      assets_for_all: true
#################################################################### 
settings:
#################################################################### 
  cache: true
  cache_expiration: 60
  asset_directory: config/Assets
  asset_folders: false
  asset_depth: 2
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: sync
  default_collection_order: release
  minimum_items: 1
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  show_unmanaged: false
  show_unconfigured: false
  show_filtered: false
  show_options: false
  show_missing: false
  only_filter_missing: false
  show_missing_assets: false
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users:
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: false
  check_nightly: false
  custom_repo:

```
