### DISCUSSION TITLE
Collection of episodes with rating greater than x

### DISCUSSION THREAD

**Discussion by Hesketh** [meisnate12/Plex-Meta-Manager#536] [Q&A] [answered]
Hi, I've been trying to setup plex meta manager so that I can build a collection of all Simpsons episodes that have a minimum user/critic/audience rating.
Sadly when I try to use the user/critic score I don't get any results.
When I use audience score I get every episode, which I imagine it means we are using the TV Shows score.

Is it possible to filter by the episodes rating?

My config just for context:

```
 collections:
   The Simpsons:
     collection_level: episode
     plex_search:
       type: episodes
       all:
         title.ends: "Simpsons"
         audience_rating.gte: 7
     summary: A collection of the highest rated simpsons epsodes.
```

**Comment by meisnate12** [comment, marked as answer]
so its having a hard time filtering episodes by rating my suggestion would be to do this
```yaml
 collections:
   Top 100 Simpsons Episodes:
     collection_level: episode
     plex_search:
       type: episodes
       sort_by: audience_rating.desc
       limit: 100
       all:
         title.ends: "Simpsons"
     summary: A collection of the highest rated simpsons epsodes.
```
