### DISCUSSION TITLE
Unplayed collection

### DISCUSSION THREAD

**Discussion by mchal** [meisnate12/Plex-Meta-Manager#628] [Q&A]
Hey
I'm trying to setup some random collection that includes unplayed movies only, but got an error.

Example of the config I'm using:
```
templates:
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
    smart_label: random
    smart_filter:
      all:
        unplayed: true
collections:
  Popular Movies:
    template: { name: Chart, num: 2 }
    tmdb_popular: 40
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,tv_movie,documentary,short
      limit: 40
    summary: Popular Movies across the internet
```
End when I run the script got the error:
`Collection Error: tmdb_popular builder not allowed when using smart_filter`

Any reason for that or how can I bypass this? 
I can create "unplayed is true" manually in plex, but can't do it through YAML file to create this filter automatically.

I'm using current version: v1.15.0

Thank you in advance

**Comment by kevbentz** [comment]
Have you tried plex_search instead of smart_filter?

**Reply by mchal** [reply]
Thank you for the reply.

I've just tried, but it doesn't work as I was hoping for (I was expecting it will try to add 20 movies to the collection, not 1000).

Config:
```
templates:
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
    smart_label: random
    plex_search:
      all:
        unplayed: true
      sort_by: random
collections:
  Plex Popular:
    template: { name: Chart, num: 1 }
    tautulli_popular:
      list_days: 30
      list_size: 20
      list_buffer: 20
    tautulli_watched:
      list_days: 30
      list_size: 20
      list_buffer: 20
    summary: Movies Popular on Plex
```

output (slightly edited):
```
| === Running Plex Popular Collection ===
| Sync Mode: sync
| Processing Tautulli Most Popular: 20 Movies
| Processing Tautulli Most Watched: 20 Movies
|
| Plex Movie Search
| Sort By: random
| Filter: 
|   Match all of the following: 
|     Unplayed is true
|
| === Adding to Plex Popular Collection ===
|
|     1/1000 | Plex Popular Collection | + | Random Movie (1999)
|     2/1000 | Plex Popular Collection | + | Another Movie (2009)
...
| 1000/1000 |  Plex Popular Collection | + | Last Movie (2010)
```


but there is a high chance I'm doing something wrong - I'm new to PMM

**Comment by meisnate12** [comment]
your changing the chart template instead of making a new collection 

```yaml
templates:
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
    smart_label: random
collections:
  Popular Movies:
    template: { name: Chart, num: 2 }
    tmdb_popular: 40
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,tv_movie,documentary,short
      limit: 40
    summary: Popular Movies across the internet
  Unplayed Collection:
    smart_filter:
      sort_by: random
      all:
        unplayed: true
```
