### DISCUSSION TITLE
What items does trakt_watchlist support? Missing items in generated "Watchlist" from trakt

### DISCUSSION THREAD

**Discussion by gitttt54** [meisnate12/Plex-Meta-Manager#643] [Q&A] [answered]
Hello,

I have added the following items to my Trakt.tv Watchlist:
-a full series [(example)](https://trakt.tv/shows/21-jump-street)
-a season only [(example)](https://trakt.tv/shows/tatort/seasons/2022)
-an episode only [(example)](https://trakt.tv/shows/csi-crime-scene-investigation/seasons/13/episodes/13)

Now, when I start the script, it only adds the full series to the generated watchlist collection.

Is this intended behaviour?

I would expect to have all items included in the plex collection. Not only the full series. 
(I add unwatched seasons or unwatched/interesting eposodes to my trakt.tv watchlist. Thats why I expect those "loose" items to show up too)

My (shamelessly copied) config:

```
collections:
  Watchlist TV:
    trakt_watchlist:
      - me
    sort_title: ++3Watchlist
    smart_label: release.desc
    sync_mode: sync
    label: admin
    visible_home: true
    visible_shared: false
    visible_library: false
    url_poster: https://i.imgur.com/wzk0Z14.png
```

Maybe I missed something to define in my config?
