### DISCUSSION TITLE
Dummy collection/blank collection

### DISCUSSION THREAD

**Discussion by ButtaJones** [meisnate12/Plex-Meta-Manager#645] [Q&A]
I've been trying to add a dummy collect. A blank collection with nothing in it. Is this possible? This is what I tried. Maybe I'm trying to hard.

```
  A:
    collection_mode: hide
    sort_title: +08_a
    plex_search:
      any:
        title: khjslahjg
      validate: false
    url_poster: https://raw.githubusercontent.com/zluckytraveler/Plex-Meta-Manager-Configs/master/zluckytraveler/Posters/Networks/Standard/ABC.jpg
```
Script spits out:
```
| A                    |  0  |  0  |  0  | PMM Failure                                               |
| Plex Error: No Items found in Plex
```

Also. Would it be possible to leave the collection name blank insead of "A"?

Any ideas?

**Comment by ButtaJones** [comment]
Figured it out with Tautulli builder. Would be nice to do with Plex or Smart builder and no matches. This still shows "1 movie" under the collection.

```
  ' ':
    collection_mode: hide
    sort_title: +08_a
    tautulli_popular:
      list_days: 1
      list_size: 1
    url_poster: https://your.link.to/pic.png
```
