### DISCUSSION TITLE
Mass updates to metadata (specifically content ratings)

### DISCUSSION THREAD

**Discussion by burkasaurusrex** [meisnate12/Plex-Meta-Manager#696] [Q&A]
Is there a way to update certain metadata from the results of a Plex search? e.g. is there a way to update the content ratings of everything currently labeled as "TV-14" to "PG-13"?

I don't think it's possible because you'd need a `item_content_rating` or something, but just thought I'd check here before opening a feature request.

Was thinking something like this:

```yaml
###
### Content Rating
###
templates:
    Content Rating Filter:
        plex_all: true
        filters:
            content_rating: <<collection_name>>
        build_collection: false
collections:
    ##
    ## TV Ratings
    ##
    TV-G:
        template: {name: Content Rating Filter}
        item_content_rating: "G"
    TV-PG:
        template: {name: Content Rating Filter}
        item_content_rating: "PG"
    TV-14:
        template: {name: Content Rating Filter}
        item_content_rating: "PG-13"
    TV-MA:
        template: {name: Content Rating Filter}
        item_content_rating: "R"
```
