### DISCUSSION TITLE
Nesting or combining Plex Builders

### DISCUSSION THREAD

**Discussion by TechJedi51** [meisnate12/Plex-Meta-Manager#703] [Q&A]
I am trying to add **any** movies in a subfolder called "Nordic" **and** a few by title, language and IMDB ID. If I run the plex_all, it works by itself and the plex_search & imdb_id work by themselves. But it seems to apply the filter to both plex_all and plex_search if I nest it like below. Any suggestions?

```
collections:
  Nordic Film Collection:
    sort_title: +++++Nordic Collection
    summary: A collection of films from Norway, Sweden and Finland. Many of the films are presented in their original language with subtitles available.
    plex_all: true
    filters:
      filepath:
        - Nordic
    plex_search:
      any:
        title.is:
          - "Frozen"
          - "Frozen II"
          - "1939"
          - "Breaking the Waves"
        audio_language: no, sv, fi 
    imdb_id: tt0096163 # The Vanishing

```
I tried breaking the searched criteria into a different file, I get the following error:
```
| Loading Metadata File: config/Feature Films Append.yml                                             |
| Config Warning: Skipping duplicate collection: Nordic Film Collection                              |
| Config Warning: Skipping duplicate collection: Christmas Movies                                    |
| Config Warning: Skipping duplicate collection: Godzilla Collection                                 |
| YAML Error: metadata or collections attribute is required                                          |
```
