### DISCUSSION TITLE
How to change properties in TMDB collections?

### DISCUSSION THREAD

**Discussion by andromidasj** [meisnate12/Plex-Meta-Manager#711] [Q&A]
I have an operation running in the script which searches for TMDB collections in my library. How do I change the name of a specific collection within the operations script?

Example:
```
   operations:
      tmdb_collections:
        remove_suffix: Collection
```

For "The Trolls Collection", this returns a collection called "The Trolls". How can I rename just this collection to be called "Trolls" instead?

What I tried:
```
        dictionary_variables:
          change_collection_name:
            489724: Trolls
        template:
          optional:
            - change_collection_name
          tmdb_collection_details: <<collection_id>>
          collection_name: <<change_collection_name>>
          collection_order: release
```

This doesn't work, I think because I just came up with ```collection_name``` and it looks like it's not recognized by the script. In the Wiki example though, ```url_poster``` is a valid argument. I couldn't find any library of accepted variable names, so I'm not sure how to change the name of a collection on a case-by-case basis other than just excluding the id and creating a custom collection in the Movies.yml file. Is this the only way to do it?
