### DISCUSSION TITLE
Collections Tab is full of content, but filter>collections is empty

### DISCUSSION THREAD

**Discussion by enricosan** [meisnate12/Plex-Meta-Manager#716] [Q&A]
Collections Tab is full of content, but filter>collections is empty. Hoping to use the filter tab to browse. Any ideas what I'm missing?

```
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: false
  sync_mode: sync
  show_unmanaged: true
  show_filtered: true
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: false
  create_asset_folders: false
  delete_below_minimum: false
  minimum_items: 1
  asset_depth: 0
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  default_collection_order:
  item_refresh_delay: 0
  delete_not_scheduled: false
  only_filter_missing: false
  show_options: false
  show_missing_assets: true
  tvdb_language: default
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  verify_ssl: true
  custom_repo:
```
