### DISCUSSION TITLE
How do I hide watched items in a collection?

### DISCUSSION THREAD

**Discussion by kevbentz** [meisnate12/Plex-Meta-Manager#741] [Q&A]
What do I need to add to the collection template so that it hides items that have been played/watched?

**Comment by meisnate12** [comment]
you could use filters add 
```yaml
filters:
  plays.lt: 1
  ```

**Reply by kevbentz** [reply]
That didn't work, at least with my collection.

My template:
```
  collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
```

My collection:
```
  Recommended Movies:
    template: {name: collection}
    sort_title: +01_Recommended Movies
    sync_mode: sync
    smart_label: random
    filters:
      plays.lt: 1
    trakt_recommended_weekly: 100

```
With the lines "filters:" and "plays.lt: 1" not commented out, it doesn't have enough items to make a collection (2).  With the lines commented out it creates a collection with 79 items in it, 63 of which have already been played.
