### DISCUSSION TITLE
Collection by content rating (german)

### DISCUSSION THREAD

**Discussion by dantz10** [meisnate12/Plex-Meta-Manager#761] [Q&A]
Hi,

I'm trying to get a collection going by using content rating for my kids:

```
templates:
    Rating:
        plex_all: true
        filters:
            content_rating: <<content>>
        sort_title: 2222_<<collection_name>>
        collection_order: alpha
        collection_mode: hide
            
collections:
    Für Kinder geeignet:
        template: {name: Rating, content: ["de/0", "de%2F0", "de/6", "de%2F6"]}
        summary: Movies that are suitable for Kids
```

But I get nothing since it's not matching anything, validation is correct (when I just put in "6" it says that's not ok giving me the above options).

What am I doing wrong?

Kind regards
Daniel

**Comment by YozoraXCII** [comment]
Hi,

Your indentation looks off, can you test the below:

```
templates:
  Rating:
    plex_all: true
    filters:
      content_rating: <<content>>
    sort_title: 2222_<<collection_name>>
    collection_order: alpha
    collection_mode: hide
collections:
  Für Kinder geeignet:
    template: {name: Rating, content: ["de/0", "de%2F0", "de/6", "de%2F6"]}
    summary: Movies that are suitable for Kids
```
