### DISCUSSION TITLE
Templates for Individual Item metadata?

### DISCUSSION THREAD

**Discussion by justinxfisher** [meisnate12/Plex-Meta-Manager#861] [Ideas]
First, I may just have missed this somewhere as it's difficult to search the wiki for "movie", "metadata" and "template", but is there a way to make a template for movie/tv (non-collection) metadata? For example, this works:

```
  "Aladdin -- 1992":
    year: 1992
    url_poster: https://theposterdb.com/api/assets/217207
    title: Aladdin
    sort_title: Aladdin_01
  "Aladdin -- 2019":
    year: 2019
    url_poster: https://theposterdb.com/api/assets/44740
    title: Aladdin
    sort_title: Aladdin_02
```

...but this doesn't:

```
templates:
 individual:                           # template: { name: individual, yr: , at: , st: , posterdb: }
   optional:
   - yr
   - tt
   - st
   - at
   - posterdb
   year: <<yr>>
   url_poster: https://theposterdb.com/api/assets/<<posterdb>>
   title: <<tt>>
   sort_title: <<st>>
   alt_title: <<at>>
metadata:
  "Aladdin -- 1992":
    template: { name: individual, at: Aladdin, st: Aladdin_01, yr: 1992, posterdb: 217207 }
  "Aladdin -- 2019":
    template: { name: individual, at: Aladdin, st: Aladdin_02, yr: 2019, posterdb: 44740 }
```

To be honest, I had just sort of assumed it would work and was surprised when I started getting errors while running it.

**Comment by meisnate12** [comment]
it doesn't work because it doesn't really save you anything you still have to declare all those attributes 

like this is valid 
```yaml
metadata:
  "Aladdin -- 1992": 
    alt_title: Aladdin
    sort_title: Aladdin_01
    year: 1992
    url_poster: https://theposterdb.com/api/assets/217207
  "Aladdin -- 2019":
    alt_title: Aladdin
    sort_title: Aladdin_02
    year: 2019
    url_poster: https://theposterdb.com/api/assets/44740
```
and if you just want it shorter this is also valid (the URLs need to be inside of `"`s because it had the character `:` in the URL.)

```yaml
metadata:
  "Aladdin -- 1992": { alt_title: Aladdin, sort_title: Aladdin_01, year: 1992, url_poster: "https://theposterdb.com/api/assets/217207" }
  "Aladdin -- 2019": { alt_title: Aladdin, sort_title: Aladdin_02, year: 2019, url_poster: "https://theposterdb.com/api/assets/44740" }
```
