### DISCUSSION TITLE
Dynamic collection more than 50 items?

### DISCUSSION THREAD

**Discussion by fredamn76** [meisnate12/Plex-Meta-Manager#925] [Q&A]
Hi. I'm trying to use dymanic collections for movie genres. However its limits to 50 movies. How can i add more than 50 movies (maybe 500) to a dynamic collection?

My current yml code below.

https://pastebin.com/EW0gUTDh

**Comment by snorrelo** [comment]
The default template for genre collections has a 50 items limit: 
https://metamanager.wiki/en/latest/metadata/dynamic.html#genre

The example in the link above shows how you can override the default with something like:

```yaml
templates:
  genre collection:
    smart_filter:
      limit: 500
      all:
        genre: <<value>>
dynamic_collections:
  Genres:     
    type: genre
    template: genre collection
```
