### DISCUSSION TITLE
Here's my docker-compose.yml in case anyone else wants to run in docker-compose

### DISCUSSION THREAD

**Discussion by fefeh1** [meisnate12/Plex-Meta-Manager#96] [Show and tell]
```
version: "3"
services:
  plex-meta-manager:
    command:
      - -t01:15
    container_name: plex-meta-manager
    restart: unless-stopped
    volumes:
      - <PATH_TO_CONFIG>:/config:rw
    entrypoint:
      - python3
      - plex_meta_manager.py
    image: meisnate12/plex-meta-manager

```
