### DISCUSSION TITLE
trakt_list requires Trakt to be configured

### DISCUSSION THREAD

**Discussion by techcubs** [meisnate12/Plex-Meta-Manager#964] [Q&A]
Hi, every time I run the command , i get the error: trakt_list requires Trakt to be configured 

i am running this in docker-compose.
```
  plex_meta_manager_movies:
    image: meisnate12/plex-meta-manager
    container_name: plex_meta_manager_movies
    logging:
      options:
        max-size: 10m
    restart: always
    volumes:
      - $DOCKERDIR/appdata/plex_meta_manager_movies:/config:rw
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
```
I have added the trakt Client ID and Secret but I cannot get it to prompt me for a pin and save credentials.

I run: 
`docker compose up -d`

then run 
`docker exec-it  plex_meta_manager_movies bash `

once inside the container i run:
`python plex_meta_manager.py -r`

The script runs, I get collections and overlays in plex but I get errors whenever trakt is needed.

| Connecting to Trakt...                                                                             |
| Navigate to: https://trakt.tv/oauth/authorize?response_type=code&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=readcted |
| If you get an OAuth error your client_id or client_secret is invalid                               |
| Trakt pin (case insensitive): | Input Failed                                                                                       |
| Trakt Connection Failed
