### DISCUSSION TITLE
Auto-collection for movies with commentary track?

### DISCUSSION THREAD

**Discussion by otravers** [meisnate12/Plex-Meta-Manager#98] [Ideas]
Hi,

I'd like to have a movie collection for all movies that have a commentary track. I've been chasing for a way to automate this for a while but the Plex UI doesn't even support searches by audio track. 

I looked in the Plex database and that's in extra_data column of the media_streams table, if that helps.

I'm not sure that's technically possible for your script to handle which is why I started this discussion rather than open an issue with a feature request.

**Comment by meisnate12** [comment]
this is possible what exactly are you looking for? 
Do you want to search for a specific Audio Track Title (The one specified inside the MKV)?

i would probably add this as a filter so you could do 

```yaml
collections:
  Movies with Commentary:
    plex: all
    filters:
      audio_track_title: Commentary
```

if that's what you're asking for go ahead and open an issue

**Reply by otravers** [reply]
I'm not sure it's the audio track's "title" or "description", but yes the idea is to filter based on the embedded audio tracks in a video container, like seen (but not searchable) in the Plex UI movie details:
![image](https://user-images.githubusercontent.com/3731532/110704939-6e638d80-81d4-11eb-9546-64d4e4e36a48.png)

**Reply by meisnate12** [reply]
Yea that's the title. The match for all filters are exact matches so it won't be able to to match unless you specify the exact audio track title

**Reply by otravers** [reply]
Bummer, that won't work then because most of the time it's one or several entire sentences, not just the word "commentary".

**Reply by meisnate12** [reply]
ok i think ive got it working try as described above it should match partial strings and ignore case the update is live in the develop branch

**Reply by otravers** [reply]
Thank you! I'm running into errors that I suspect are due to operator error on my end. I'll troubleshoot it and get back to you when I figure these issues out.

**Reply by meisnate12** [reply]
hows the testing coming along?

**Reply by otravers** [reply]
I'm getting "Unknown filter category: year". I found an open issue in your Github that sounds similar.

For Movies.yml I just copied your template.

My config.yml


```yaml
libraries:
  Movies:
    library_type: movie
tmdb:
  apikey: xyz
  language: en
plex:
  url: https://plex.domain.tld
  token: xyz
  timeout: 60
sonarr:
  url: https://sonarr.domain.tld
  token: xyz
  version: v3
  quality_profile: HD-1080p
  root_folder_path: /tv
  add: true
  search: false
  season_folder: true
  tag: pmm
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2
collections:
  Movies with Commentary:
    plex: all
    filters:
      audio_track_title: Commentary
  IMDb Top 250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=25
    sort_title: +100
    sync_mode: sync
    add_to_arr: true
    show_filtered: true
```
