### DISCUSSION TITLE
Multiple Plex Libraries for Movies

### DISCUSSION THREAD

**Discussion by rzilla75** [meisnate12/Plex-Meta-Manager#989] [General]
I am in love with this app!

I have multiple libraries in Plex for Movies:
Movies
Movies: Documentaries
Movies: Stand Up Comedy
etc.

So far I have just been using PMM to add items to the Movies library in Plex. Now I am trying to figure out how to add "  Top New Documentaries" and have it work with my Plex Movies: Documentaries library. Not sure how or where to specify that specific library for the collection. Right now its still defaulting to my Movies library. Here is a snip of my Movies.yml:

collections:
  Top New Documentaries:
    radarr_folder: /movie_documentary
    mdblist_list: https://mdblist.com/lists/rzilla75/top-documentaries-2022/
    sort_title: zzz_<<collection name>>
    sync_mode: sync
    visible_home: true
    visible_shared: true
    radarr_tag: pmm-Docs
    collection_order: custom

 Not sure if I need to add something to my config.yml or my movies.yml.

Thanks!

**Comment by chazlarson** [comment]
That's done in the config.yml:
```
libraries:
  Movies:
    metadata_path:
      - file: config/Movies.yml  << collections defined in here are created in the Movies library
  "Movies: Documentaries":
    metadata_path:
      - file: config/SOMETHING.yml  << collections defined in here are created in the Documentaries library
...
```
You can use the same metadata file with multiple libraries.
