### DISCUSSION TITLE
How create a TV collection with all episodes for an actor NOT in a TV series

### DISCUSSION THREAD

**Discussion by markmarz** [meisnate12/Plex-Meta-Manager#993] [Q&A]
For example, good old Warren Oates, who did a whole lot of TV work, was a regular cast member in only a few series: most notably, 'Stoney Burke', and then 'The Blue and the Gray' and 'East of Eden'. 

I'd like to create a collection that excludes episodes in those series. I've tried creating a collection with just the above series in it, then using has_collection.not as a filter, but so far I haven't figured out how to code that correctly. So it may be that I have the right idea but I'm screwing up the implementation.

Or maybe there's a better way that doesn't involve creating a series collection in the first place.

Oh, it'd probably be best for me to give the code that returns ALL episodes, including where he's a regular cast member:

```
root@omv:~/pmm/TV_skip# cat warren_oates_imdb.yml

collections:

  Warren Oates imdb:
    url_poster: https://i.imgur.com/GNsu2fcm.jpg
    collection_level: episode
    collection_order: release
    sort_title: Warren Oates imdb
    imdb_list: https://www.imdb.com/search/title/?title_type=tv_episode&role=nm0643105
    summary: "Warren Mercer Oates (July 5, 1928 – April 3, 1982) was an American actor best known for his performances in several films directed by Sam Peckinpah, including The Wild Bunch (1969) and Bring Me the Head of Alfredo Garcia (1974). Another of his most acclaimed performances was as officer Sam Wood in In the Heat of the Night (1967). Oates starred in numerous films during the early 1970s that have since achieved cult status, such as The Hired Hand (1971), Two-Lane Blacktop (1971), and Race with the Devil (1975). Oates also portrayed John Dillinger in the biopic Dillinger (1973) and as the supporting character U.S. Army Sergeant Hulka in the military comedy Stripes (1981). Another notable appearance was in the classic New Zealand film Sleeping Dogs (1977), in which he played the commander of the American forces in the country.

https://en.wikipedia.org/wiki/Warren_Oates"

root@omv:~/pmm/TV_skip#
```

Thanks!

**Comment by meisnate12** [comment]
Youll want to use filters for this 
```yaml
collections:
  Warren Oates imdb:
    url_poster: https://i.imgur.com/GNsu2fcm.jpg
    collection_level: episode
    collection_order: release
    sort_title: Warren Oates imdb
    imdb_list: https://www.imdb.com/search/title/?title_type=tv_episode&role=nm0643105
    filters:
      actor.not: Warren Oates
```
