### ISSUE TITLE
IMDB lists: "Failed to parse URL" error

### ISSUE THREAD

**Issue by ghost** [meisnate12/Plex-Meta-Manager#1722]
### Version Number

1.19.1-nightly22

### What branch are you on?

nightly

### Describe the Bug

Any collection that uses imdb for its source is failing due a "Failed to parse URL" error.

The source urls are valid and show the intended lists on IMDB.

### Relevant Collection/Overlay/Playlist Definition

```yml
## 1_suggested.yml

templates:
  plex:
    sort_title: "+1_<<num>>_<<collection_name>>"
    sync_mode: sync
    collection_mode: hide
    visible_home: false
    visible_shared: false
    visible_library: false
    delete_not_scheduled: false
    cache_builders: 4

  trakt:
    sort_title: "+1_<<num>>_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
    visible_home: false
    visible_shared: false
    visible_library: false
    delete_not_scheduled: false
    cache_builders: 4

  imdb_popular:
    sort_title: "+1_<<num>>_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
    visible_home: false
    visible_shared: false
    visible_library: false
    delete_not_scheduled: false
    cache_builders: 4
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=<<title_type>>&languages=<<languages>>&sort=moviemeter,asc
      limit: 200

  imdb_top:
    sort_title: "+1_<<num>>_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
    visible_home: false
    visible_shared: false
    visible_library: false
    delete_not_scheduled: false
    cache_builders: 4
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=<<title_type>>&user_rating=<<user_rating>>&num_votes=<<votes>>,&languages=<<languages>>&sort=user_rating,desc&count=250
      limit: 300

collections:
  "Random Movies":
    summary: "Random selection of movies"
    url_poster: https://images2.imgbox.com/41/29/aa0NPuyr_o.png
    visible_library: true 
    schedule: daily
    template: {
                    name: plex,
                    num: 0
                    }
    smart_filter:
      all:
        critic_rating.gte: 4
      sort_by: random
      limit: 250
      
  "Recently Released Movies":
    summary: "Recently added movies"
    url_poster: https://images2.imgbox.com/12/39/VFlLhmvX_o.png
    visible_library: true 
    template: {
                    name: plex,
                    num: 1
                    }
    smart_filter:
      any:
        audio_language: English, english
      sort_by: release.desc
      limit: 200
      
  "Recently Added Movies":
    summary: "Recently added movies"
    url_poster: https://images2.imgbox.com/40/fb/9zzJnUVQ_o.png
    visible_home: true
    visible_shared: true
    visible_library: true 
    template: {
                    name: plex,
                    num: 1
                    }
    smart_filter:
      any:
        audio_language: English, english
      sort_by: added.desc
      limit: 200

  "Trending Movies":
    summary: "Movies trending across the internet"
    url_poster: https://images2.imgbox.com/5e/f5/lRkPiQHy_o.png
    schedule: daily
    template: {
                    name: trakt,
                    num: 2
                    }
    trakt_chart:
      chart: trending
      time_period: daily
      languages: en
      countries: us, gb, ie, ca, au, nz
      limit: 50

  "Popular Movies":
    summary: "Popular movies across the internet"
    url_poster: https://images2.imgbox.com/2e/34/oxXyim7m_o.png
    visible_library: true 
    schedule: daily
    template: {
                    name: imdb_popular,
                    num: 3,
                    title_type: "feature",
                    languages: "en",
                    }
    limit: 100

  "Top Rated Movies":
    summary: "Top rated movies across the internet"
    url_poster: https://images2.imgbox.com/4d/9b/Xb3ambH9_o.png
    schedule: daily
    template: {
                    name: imdb_top,
                    num: 4,
                    title_type: "feature,tv_movie",
                    user_rating: "5.0,10.0",
                    votes: "10000,",
                    languages: "en"
                    }
    limit: 200

  "Most Watched Daily":
    summary: "Movies trending across the internet"
    url_poster: https://images2.imgbox.com/54/48/RpwMMx1Y_o.png
    schedule: daily
    template: {
                    name: trakt,
                    num: 5
                    }
    trakt_chart:
      chart: watched
      time_period: daily
      languages: en
      countries: us, gb, ie, ca, au, nz
      limit: 50

  "Most Watched Weekly":
    summary: "Movies trending across the internet"
    url_poster: https://images2.imgbox.com/cc/37/PfqsdJzM_o.png
    schedule: daily
    template: {
                    name: trakt,
                    num: 6
                    }
    trakt_chart:
      chart: watched
      time_period: weekly
      languages: en
      countries: us, gb, ie, ca, au, nz
      limit: 50

  "Most Watched Monthly":
    summary: "Movies trending across the internet"
    url_poster: https://images2.imgbox.com/c7/3c/7fM4BrER_o.png
    schedule: weekly(sunday)
    template: {
                    name: trakt,
                    num: 7
                    }
    trakt_chart:
      chart: watched
      time_period: monthly
      languages: en
      countries: us, gb, ie, ca, au, nz
      limit: 75

  "Most Watched Yearly":
    summary: "Movies trending across the internet"
    url_poster: https://images2.imgbox.com/17/88/LYG1r4xG_o.png
    schedule: weekly(sunday)
    template: {
                    name: trakt,
                    num: 8
                    }
    trakt_chart:
      chart: watched
      time_period: yearly
      languages: en
      countries: us, gb, ie, ca, au, nz
      limit: 100
```

### Logs

https://gist.github.com/0x5f3/1bd39f5ad2ad1b706410bd7a54549abf

**Comment by chazlarson** [comment]
IMDB has made some server-side changes that prevent PMM parsing the pages.  There is no solution at present.

**Comment by ghost** [comment]
So I see. Looks like they've moved the data to an embedded JSON within some JavaScript.

**Comment by YozoraXCII** [comment]
> So I see. Looks like they've moved the data to an embedded JSON within some JavaScript.

We are working on a solution, which isn't as simple because of the JavaScript you mention

**Comment by nwithan8** [comment]
> IMDB has made some server-side changes that prevent PMM parsing the pages. There is no solution at present.

Glad to know you're aware of it, bummer that it happened in the first place.

**Comment by sanswit** [comment]
What is the over/under on when we should pivot away from IMDB?

**Comment by chazlarson** [comment]
This only affects IMDB search pages, not imdb lists.  

Feel free to pivot away whenever you decide you've waited too long, or jump in and implement a solution.

**Comment by sanswit** [comment]
Thanks Chaz! This is helpful context about the search vs lists pages.

**Comment by kris-anderson** [comment]
Is this related to the Oscars collection not being created and populated?

**Comment by chazlarson** [comment]
Yes; that's an instance of this.

**Comment by dsfsdbvxc** [comment]
Stumpled across this while searching for a fix, following

**Comment by rutskiuk** [comment]
I was utterly convinced it was user error on my part, quite relieved that the url parse error was the cause of Academy Awards collections not being created. Will wait with keen anticipation.

**Comment by kllngtme** [comment]
It's anything with a search field as the list. I've just since converted to using only lists for now..

**Comment by chrisjohnson00** [comment]
> It's anything with a search field as the list. I've just since converted to using only lists for now..

What does this mean?

I'm doing this:

```
collections:
  This is Halloween:
    smart_label: originally_available.desc
    sync_mode: sync
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature&keywords=Halloween&languages=en
      limit: 100
    summary: The most popular Halloween movies
    radarr_add_missing: false
    radarr_search: false
    radarr_monitor: false
    sort_title: halloween
```

How would I do it differently?

**Comment by chazlarson** [comment]
```
     url: https://www.imdb.com/search/title/?title_type=feature&keywords=Halloween&languages=en
                               ^^^^^^
```
Use something other than a search URL.

Those currently do not work at all due to changes on the IMDB side.

You may need to replace this with an MDBlist or a Trakt list or something else if you can't find an IMDB list that meets your needs.

**Comment by Asgeorge712** [comment]
@chrisjohnson00 - there is NO direct way to create a list from your search terms.  You just have to try to find an existing list that is as close to your search as possible.  Or create your own list.... But the great thing about searches is that they update their results each time you run PMM, so no list will be as good as your search.. :/

**Comment by YozoraXCII** [comment]
IMDb search builders should be working again in nightly

You may need to read the nightly wiki for any changes

**Comment by Brandoskey** [comment]
> IMDb search builders should be working again in nightly
> 
> You may need to read the nightly wiki for any changes

I switched my tag to nightly for the dockerhub version and this doesn't appear to be the case, same errors pop up.

**Comment by BelminH** [comment]
I'm getting this error after running the nightly build locally: 

```
 1 | IMDb Error: https://www.imdb.com/search/title/?title_type=feature,tv_movie&genres=action&languages=en&sort=moviemeter,asc must begin with either:https://www.imdb.com/list/ls (For Lists) |
 ```

**Comment by Asgeorge712** [comment]
I get the same new error:
[2023-12-09 09:01:06,457] [plex_meta_manager.py:812]  [ERROR]    | IMDb Error: https://www.imdb.com/search/title/?title_type=feature must begin with either:https://www.imdb.com/list/ls (For Lists) |
                                                                 | https://www.imdb.com/search/**keyword**/ (For Keyword Searches)                                    
                                                                 | https://www.imdb.com/filmosearch/ (For Filmography Searches)           

Which suggests the old URL for search no longer works.
For example, an old URL like:  https://www.imdb.com/search/title/?companies=co0074039  (Disney movies)
would be required to start with https://www.imdb.com/search/**keyword**/xxxxx  but "companies" doesn't seem to be an option in keyword searches.

Another example, old URL: https://www.imdb.com/search/title/?sort=user_rating,desc&groups=top_250&count=250
but "groups" isn't an option either.

The old URLs still work on the iMDB website, but now PMM won't run them.

I hope I'm mistaken, please correct me if I've missed something.

**Comment by ghost** [comment]
> I get the same new error: [2023-12-09 09:01:06,457] [plex_meta_manager.py:812] [ERROR] | IMDb Error: https://www.imdb.com/search/title/?title_type=feature must begin with either:https://www.imdb.com/list/ls (For Lists) | | https://www.imdb.com/search/**keyword**/ (For Keyword Searches) | https://www.imdb.com/filmosearch/ (For Filmography Searches)
> 
> Which suggests the old URL for search no longer works. For example, an old URL like: https://www.imdb.com/search/title/?companies=co0074039 (Disney movies) would be required to start with https://www.imdb.com/search/**keyword**/xxxxx but "companies" doesn't seem to be an option in keyword searches.
> 
> Another example, old URL: https://www.imdb.com/search/title/?sort=user_rating,desc&groups=top_250&count=250 but "groups" isn't an option either.
> 
> The old URLs still work on the iMDB website, but now PMM won't run them.
> 
> I hope I'm mistaken, please correct me if I've missed something.

Using the raw urls wont work; there's new config options for IMDB builders: https://metamanager.wiki/en/nightly/builders/imdb/#imdb-search

**Comment by mena-p** [comment]
> Using the raw urls wont work; there's new config options for IMDB builders: https://metamanager.wiki/en/nightly/builders/imdb/#imdb-search

The limit parameter doesn't seem to be working. I'm running this:

```
collections:
    imdb_search:
      type: movie
      sort_by: popularity.asc
      limit: 50
    collection_order: custom
    sync_mode: sync
```

And get this error: 

Collection error: imdb_search limit attribute not supported
