### ISSUE TITLE
Metadata updates to title do not populate when title is used for match

### ISSUE THREAD

**Issue by Kevin2kkelly** [meisnate12/Plex-Meta-Manager#1761]
### Version Number

1.19.1

### What branch are you on?

nightly

### Describe the Bug

Using `title` as the primary attribute within `match` to perform metadata updates will not allow metadata updates to `title` itself. Any other metadata updates specified, such as `sort_title` will still populate however.

### Relevant Collection/Overlay/Playlist Definition

```yml
metadata:
  Nomadland:
    match:
      edition: Test1
    sort_title: NomadlandTEST1
    title: NomadlandTEST1

  581734:
    match:
      edition: Test2
    sort_title: NomadlandTEST2
    title: NomadlandTEST2

  Nomadland3:
    match:
      title: Nomadland
      edition: Test3
    sort_title: NomadlandTEST3
    title: NomadlandTEST3
```

### Logs

https://gist.github.com/Kevin2kkelly/231c73494c5d69f19c07596d2eb2014b
