### ISSUE TITLE
pmm is caching expired content from mbdlist 

### ISSUE THREAD

**Issue by ghost** [meisnate12/Plex-Meta-Manager#1828]
### Version Number

1.20.0-nightly8 (Docker)

### What branch are you on?

nightly

### Describe the Bug

mdblist.com caches content on CloudFlare for 24 hours, but when pmm receives expired content, it is still caching the response rather than requesting the fresh cache. Setting "mdblist:cache_expiration:1" still results in stale data, only completely disabling pmm's cache results in the fresh data.

I've noticed this behavior on lists that are updated daily on mdblist.com.

### Relevant Collection/Overlay/Playlist Definition

```yml
## 0_debug.yml
templates:
  mdblist:
    cache_builders: 6
    collection_mode: hide
    collection_order: custom
    delete_not_scheduled: false
    sort_title: "+1_<<num>>_<<collection_name>>"
    sync_mode: sync
    visible_home: false
    visible_library: false
    visible_shared: false
    mdblist_list:
      sort_by: <<mdblist_sort>>
      url: https://mdblist.com/lists/<<mdblist_user>>/<<mdblist_list>>/
    optional:
      - mdblist_extra_1
      - mdblist_extra_2
      - mdblist_extra_3
      - mdblist_extra_4
      - mdblist_extra_5

collections:
  "Trending Movies":
    summary: "Movies trending across the internet"
    file_poster: config/assets/1_suggested/suggested_trending.png
    schedule: daily
    template: {
                    name: mdblist,
                    num: 2,
                    mdblist_user: "archivist",
                    mdblist_list: "movie-trending",
                    mdblist_sort: "rank.desc"
                }
    limit: 100
```
