### ISSUE TITLE
IMDB builder imdb_search error: KeyError: 'data'

### ISSUE THREAD

**Issue by ghost** [meisnate12/Plex-Meta-Manager#1871]
### Version Number

1.20.0-nightly29 (Docker)

### What branch are you on?

nightly

### Describe the Bug

The following error happens when trying to use imdb_search:

```
|============================ Running Top Rated of the 1990s Collection =============================|
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Builder: imdb_search: {'limit': 500, 'language': ['en'], 'release.after': '1990-01-01', 'release.before': '1999-12-31', 'sort_by': 'rating.desc', 'type': ['tv_series', 'tv_mini_series', 'tv_special'], 'votes.gte': 100} |
|                                                                                                    |
| Processing IMDb Search:                                                                            |
|     limit: 500                                                                                     |
|     language: ['en']                                                                               |
|     release.after: 1990-01-01                                                                      |
|     release.before: 1999-12-31                                                                     |
|     sort_by: rating.desc                                                                           |
|     type: ['tv_series', 'tv_mini_series', 'tv_special']                                            |
|     votes.gte: 100                                                                                 |
| Starting new HTTPS connection (1): api.graphql.imdb.com:443                                        |
| https://api.graphql.imdb.com:443 "POST / HTTP/1.1" 200 100                                         |
| Traceback (most recent call last):                                                                 |
|   File "//plex_meta_manager.py", line 775, in run_collection                                       |
|     builder.filter_and_save_items(builder.gather_ids(method, value))                               |
|                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
|   File "/modules/builder.py", line 2209, in gather_ids                                             |
|     ids = self.config.IMDb.get_imdb_ids(method, value, self.language)                              |
|           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              |
|   File "/modules/imdb.py", line 572, in get_imdb_ids                                               |
|     return [(_i, "imdb") for _i in self._search(data)]                                             |
|                                    ^^^^^^^^^^^^^^^^^^                                              |
|   File "/modules/imdb.py", line 416, in _search                                                    |
|     total = response_json["data"]["advancedTitleSearch"]["total"]                                  |
|             ~~~~~~~~~~~~~^^^^^^^^                                                                  |
| KeyError: 'data'                                                                                   |
|                                                                                                    |
| Unknown Error: 'data'                                                                              |
|                                                                                                    |
|====================================================================================================|
```

### Relevant Collection/Overlay/Playlist Definition

```yml
## 0_debug.yml

templates:
  decade_top:
    collection_mode: hide
    collection_order: custom
    delete_not_scheduled: false
    limit: 250
    sort_title: "+3_<<num>>_<<collection_name>>"
    sync_mode: sync
    visible_home: false
    visible_library: false
    visible_shared: false
    imdb_search:
      language: <<language>>
      limit: 500
      release.after: <<release.after>>
      release.before: <<release.before>>
      sort_by: rating.desc
      type: <<type>>
      votes.gte: <<votes.gte>>

collections:
  "Top Rated of the 1990s":
    summary: "Top rated TV shows of the 1990s"
    file_poster: config/assets/3_decades_top/decades_top_1990s.png
    template: {
                    name: decade_top,
                    num: "T",
                    type: "tv_series,tv_mini_series,tv_special",
                    release.after: 1990-01-01,
                    release.before: 1999-12-31,
                    votes.gte: 100,
                    language: "en"
                    }
```
