### ISSUE TITLE
[Defaults]: content rating overly NC-17 != R18

### ISSUE THREAD

**Issue by miaLDN** [meisnate12/Plex-Meta-Manager#2256]
### Link to File

defaults/overlays/content_rating_uk.yml

### Version Number

Version: 2.1.0 (Python 3.12.7) (Git: master)

### What branch are you on?

master

### Content Rating UK
MPAA NC-17 certificate should *not* map to UK R18 certificate.  UK BBFC R18 is for DVDs & Blu-Rays to be sold in specially licensed adult shops!

Currently:

- `NC-17` maps to `R18`.

It should be:

- `NC-17`  mapping to `18` which is the closest certificate for general release movies in cinemas.

<https://www.bbfc.co.uk/rating/r18>

This is the config that needs to be changed (showing what is currently in master branch below for `defaults/overlays/content_rating_uk.yml`):
``` yaml
  18:
    template:
      - name: standard
      - {name: cr_uk, rating: "gb/18, gb/18+, MA-17, TVMA, TV-MA, R, 16, 17, 18, R - 17+ (violence & profanity), no/18"}

  r18:
    template:
      - name: standard
      - {name: cr_uk, rating: "R18, gb/R18, gb/X, X, NC-17, R+ - Mild Nudity, Rx - Hentai"}
```

NB: there is no UK BBFC rating called 'X' currently.  Historically there was (1951-1982) where it was a cinema rating initially for minimum age 16, which was raised to 18 in 1970.   Assumption that `gb/X` in the YAML file refers to this rating, since this historic certificate rating; if so, then `gb/X` should map to `18` also.

### Content Rating AU

`defaults/overlays/content_rating_au.yml`:

Currently `gb/R18` maps to `r`.

`gb/R18`  should map to `x`.  (also `R18` if it's a GB certification.)

### Content Rating US Movie

Needs consideration about `gb/R18` etc. being potentially down-graded to `nc-17`.  Reminder `gb/R18` is adult film industry as described above, i.e. an 'XXX'

`defaults/overlays/content_rating_us_movie.yml`:
``` yaml
  nc-17:
    template:
      - name: standard
      - {name: cr_us, rating: "NC-17, gb/R18, gb/X, R18, X, Rx - Hentai"}
```
