### ISSUE TITLE
Collection builders - Movies listed as missing from a TV library

### ISSUE THREAD

**Issue by EnSt0rm** [meisnate12/Plex-Meta-Manager#2351]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Some of my collection definitions contain lists that cross between TV and Movies. Using Star Wars as an example that has many movies and TV shows.
When I'm looking at Movie libraries, there doesn't seem to be an issue, Kometa knows to not list the TV shows from the collection definition as missing from a movies library; however when scanning a TV library, it still lists movies as missing, even though movies aren't meant to appear in a TV collection. Not sure if this occurs with all builders, but I've definitely noticed it with tvdb builder.

Can this be fixed so that when working in a TV library to build collections, it doesn't list movies as missing, as by definition, movies shouldn't be appearing in a TV library?

[Missing movies in TV Library - tvdb builder.txt](https://github.com/user-attachments/files/18015891/Missing.movies.in.TV.Library.-.tvdb.builder.txt)

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:
  Star Wars:
      template:
        name: tvdb
        url: https://thetvdb.com/lists/16520
      filters:
        filepath.not:
          - D+77
          - D+80
          - OTD83
          - Despecialized
  
###########################

templates:
  tvdb:  
    default:
      collection_order: custom
    optional:
      - summary
    tvdb_list_details: <<url>>
    collection_order: <<collection_order>>
    sync_mode: sync
    move_prefix: The, A, An
    sort_title: <<collection_sort>>
    summary: <<summary>>
```
