### ISSUE TITLE
Season level show rating overlay positioning

### ISSUE THREAD

**Issue by miaLDN** [meisnate12/Plex-Meta-Manager#2440]
### Version Number

Version: 2.1.0 (Python 3.12.8) (Git: master)

### What branch are you on?

master

### Describe the Bug

`builder_level: season` positions rating overlay in a different position to default show level.

Intent is to position the rating in the lower-left corner with a small margin, and no backbox (set to transparent).  This provides minimum intrusion into the poster.

This works for movies and shows; it does not work for season-level in shows.  This example here has the `builder_level: season` with a `horizontal_offset: 0`, rather than 15 which is intended.  I've tried specifying a negative value to counter-act the offset, but the overlay doesn't work at all then.

✅The show-level with `horizontal_offset: 15` the show rating is correctly offset by 15 pixels from the left-edge.
❌In this case with `horizontal_offset: 0` the season rating image is offset by 53 pixels from the left-edge.
❌In the case with `horizontal_offset: 15` the season rating image is offset by 68 (53 + 15) pixels from the left-edge.
❌In the case with `horizontal_offset: -38` the season rating image is doesn't appear.

![show](https://github.com/user-attachments/assets/d455e8fa-f774-463f-beb8-cb69dfc8507f)![season](https://github.com/user-attachments/assets/4424b478-c1e4-4d4c-829a-404af029e7c2)

### Relevant Collection/Overlay/Playlist Definition

```yml
yml
  Documentaries:
    overlay_files:
    - default: content_rating_us_show
      template_variables:
        use_nr: false
        horizontal_offset: 15
        horizontal_align: left
        vertical_offset: 15
        vertical_align: bottom
        back_align: left
        back_width: 215
        back_height: 95
        back_radius: 30
        back_color: '#00000000'
    - default: content_rating_us_show
      template_variables:
        builder_level: season
        use_nr: false
        horizontal_offset: 0   # should be 15
        horizontal_align: left
        vertical_offset: 15
        vertical_align: bottom
        back_width: 215
        back_height: 95
        back_radius: 30
        back_color: '#00000000'
```
```


### Logs

_No response_
