### ISSUE TITLE
Plex Advanced Filters (Kometa Builder smart filter) `dovi` not recognized

### ISSUE THREAD

**Issue by miaLDN** [meisnate12/Plex-Meta-Manager#2601]
### Version Number

Version: 2.2.0-build5 (Python 3.12.9) (Git: nightly)

### What branch are you on?

nightly

### Describe the Bug

`dovi` not accepted as a Plex smart filter search attribute

# Trivial fix add to plex.py

**Add `"dovi"` to:**

``` py
boolean_attributes = [
    "dovi", "hdr", "unmatched", "duplicate", "unplayed", "progress", "trash", "unplayed_episodes", "episode_unplayed",
    "episode_duplicate", "episode_progress", "episode_unmatched", "show_unmatched", "artist_unmatched", "album_unmatched", "track_trash"
]
```

# Plex Media Server 1.41.6.9606

[PMS Change log](https://forums.plex.tv/t/plex-media-server/30447/668)

> NEW:
>
> Added DOVI filter to video libraries (PM-2122)

![Image](https://github.com/user-attachments/assets/240efc5b-1f63-4954-89ad-42d34bf1c0c0)

## Error: dovi is not a valid smart_filter attribute

``` txt
[2025-04-08 04:22:31,504] [builder.py:2513]           [INFO]     | Validating Method: smart_filter                                                                    |
[2025-04-08 04:22:31,504] [builder.py:2519]           [DEBUG]    | Value: {'all': {'resolution': '4k', 'dovi': True}, 'sort_by': 'audience_rating.desc'}              |
[2025-04-08 04:22:31,673] [kometa.py:965]             [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "Kometa-nightly\kometa.py", line 829, in run_collection                  |
                                                                 |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "Kometa-nightly\modules\builder.py", line 926, in __init__               |
                                                                 |     self.smart_type_key, self.smart_filter_details, self.smart_url = self.build_filter("smart_filter", self.data[methods["smart_filter"]], display=True, default_sort="random") |
                                                                 |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "Kometa-nightly\modules\builder.py", line 2697, in build_filter          |
                                                                 |     built_filter, filter_text = _filter(base_dict, is_all=base_all)                                |
                                                                 |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
                                                                 |   File "Kometa-nightly\modules\builder.py", line 2667, in _filter               |
                                                                 |     raise Failed(error)                                                                            |
                                                                 | modules.util.Failed: Collection Error: dovi is not a valid smart_filter attribute                  |
                                                                 |                                                                                                    |
[2025-04-08 04:22:31,683] [kometa.py:966]             [ERROR]    | Collection Error: dovi is not a valid smart_filter attribute                                       |
```

#### my_collections_movies.yml

``` yml
collections:
  4K Dolby Vision Movies:
    cache_builders: 1
    schedule: daily
    minimum_items: 1
    sync_mode: sync
    smart_filter:
      all:
        resolution: 4k
        dovi: true
      sort_by: audience_rating.desc
    summary: >-
      Movies with resolution 4K and have Dolby Vision (DoVi)

      Sorted by 𝙰𝚞𝚍𝚒𝚎𝚗𝚌𝚎 𝚁𝚊𝚝𝚒𝚗𝚐⬇️ (highest first)
    sort_title: "!021_0_4K Dolby Vision Movies"


  4K HDR Movies:
    cache_builders: 1
    schedule: daily
    minimum_items: 1
    sync_mode: sync
    smart_filter:
      all:
        resolution: 4k
      any:
        hdr: true
        dovi: true
      sort_by: audience_rating.desc
    summary: >-
      Movies with resolution 4K and have high-dynamic-range (HDR)

      Sorted by 𝙰𝚞𝚍𝚒𝚎𝚗𝚌𝚎 𝚁𝚊𝚝𝚒𝚗𝚐⬇️ (highest first)
    sort_title: "!021_0_4K HDR Movies"  # Kometa generates sort titles '!021_0', '!021_1', '!021_2', and appends the collection name


  1080p Dolby Vision Movies:
    cache_builders: 1
    schedule: daily
    minimum_items: 1
    sync_mode: sync
    smart_filter:
      all:
        resolution: 1080p
        dovi: true
      sort_by: audience_rating.desc
    summary: >-
      Movies with resolution 1080p and have Dolby Vision (DoVi)

      Sorted by 𝙰𝚞𝚍𝚒𝚎𝚗𝚌𝚎 𝚁𝚊𝚝𝚒𝚗𝚐⬇️ (highest first)
    sort_title: "!021_2_1080p Dolby Vision Movies"
```

#### my_collections_tv_show.yml

``` yml
collections:
  4K Dolby Vision TV Shows:
    cache_builders: 1
    schedule: daily
    minimum_items: 1
    sync_mode: sync
    smart_filter:
      all:
        resolution: 4k
        dovi: true
      sort_by: audience_rating.desc
    summary: >
      TV Shows with resolution 4K and have Dolby Vision (DoVi)
  
      Sorted by 𝙰𝚞𝚍𝚒𝚎𝚗𝚌𝚎 𝚁𝚊𝚝𝚒𝚗𝚐⬇️ (highest first)
    sort_title: "!021_0_4K Dolby Vision TV Shows"


  4K HDR TV Shows:
    cache_builders: 1
    schedule: daily
    minimum_items: 1
    sync_mode: sync
    smart_filter:
      all:
        resolution: 4k
      any:
        hdr: true
        dovi: true
      sort_by: audience_rating.desc
    summary: >
      TV Shows with resolution 4K and have high-dynamic-range (HDR)

      Sorted by 𝙰𝚞𝚍𝚒𝚎𝚗𝚌𝚎 𝚁𝚊𝚝𝚒𝚗𝚐⬇️ (highest first)
    sort_title: "!021_0_4K HDR TV Shows"

  1080p Dolby Vision TV Shows:
    cache_builders: 1
    schedule: daily
    minimum_items: 1
    sync_mode: sync
    smart_filter:
      all:
        resolution: 1080p
        dovi: true
      sort_by: audience_rating.desc
    summary: >
      TV Shows with resolution 1080p and have Dolby Vision (DoVi)
  
      Sorted by 𝙰𝚞𝚍𝚒𝚎𝚗𝚌𝚎 𝚁𝚊𝚝𝚒𝚗𝚐⬇️ (highest first)
    sort_title: "!021_2_1080p Dolby Vision TV Shows"
```

### Logs

``` txt
[2025-04-08 04:22:31,504] [builder.py:2513]           [INFO]     | Validating Method: smart_filter                                                                    |
[2025-04-08 04:22:31,504] [builder.py:2519]           [DEBUG]    | Value: {'all': {'resolution': '4k', 'dovi': True}, 'sort_by': 'audience_rating.desc'}              |
[2025-04-08 04:22:31,673] [kometa.py:965]             [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "Kometa-nightly\kometa.py", line 829, in run_collection                  |
                                                                 |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "Kometa-nightly\modules\builder.py", line 926, in __init__               |
                                                                 |     self.smart_type_key, self.smart_filter_details, self.smart_url = self.build_filter("smart_filter", self.data[methods["smart_filter"]], display=True, default_sort="random") |
                                                                 |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "Kometa-nightly\modules\builder.py", line 2697, in build_filter          |
                                                                 |     built_filter, filter_text = _filter(base_dict, is_all=base_all)                                |
                                                                 |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
                                                                 |   File "Kometa-nightly\modules\builder.py", line 2667, in _filter               |
                                                                 |     raise Failed(error)                                                                            |
                                                                 | modules.util.Failed: Collection Error: dovi is not a valid smart_filter attribute                  |
                                                                 |                                                                                                    |
[2025-04-08 04:22:31,683] [kometa.py:966]             [ERROR]    | Collection Error: dovi is not a valid smart_filter attribute                                       |
```
