### ISSUE TITLE
Bug: Unknown Error: add_multiple_movies() got an unexpected keyword argument 'per_request'

### ISSUE THREAD

**Issue by alexander-paterson** [meisnate12/Plex-Meta-Manager#406]
**Describe the Bug**
I have the item_label option on my config, but it doesn't seem to be being applied to items in the collection. If I look at the log, there appears to be an error message at the bottom of the collection section.

`Unknown Error: add_multiple_movies() got an unexpected keyword argument 'per_request'`

**Relevant Collection Config**
```
  Scooby-Doo Animated Collection:
    label: "Kids"
    item_label: "Kids"
    tmdb_movie:
      - https://www.themoviedb.org/movie/721656-happy-halloween-scooby-doo
      - https://www.themoviedb.org/movie/682254-scooby-doo-in-king-arthur-s-court
      - https://www.themoviedb.org/movie/24615-aloha-scooby-doo
      - https://www.themoviedb.org/movie/37211-scooby-doo-and-the-reluctant-werewolf
      - https://www.themoviedb.org/movie/45752-scooby-doo-camp-scare
      - https://www.themoviedb.org/movie/258893-scooby-doo-wrestlemania-mystery
      - https://www.themoviedb.org/movie/32916-scooby-doo-abracadabra-doo
      - https://www.themoviedb.org/movie/284995-scooby-doo-frankencreepy
      - https://www.themoviedb.org/movie/13354-chill-out-scooby-doo
      - https://www.themoviedb.org/movie/13355-scooby-doo-pirates-ahoy
      - https://www.themoviedb.org/movie/20558-scooby-doo-in-where-s-my-mummy
      - https://www.themoviedb.org/movie/427564-scooby-doo-shaggy-s-showdown
      - https://www.themoviedb.org/movie/15601-scooby-doo-and-the-cyber-chase
      - https://www.themoviedb.org/movie/203696-scooby-doo-stage-fright
      - https://www.themoviedb.org/movie/13151-scooby-doo-on-zombie-island
      - https://www.themoviedb.org/movie/392536-lego-scooby-doo-haunted-hollywood
      - https://www.themoviedb.org/movie/287757-scooby-doo-meets-batman
      - https://www.themoviedb.org/movie/119321-big-top-scooby-doo
      - https://www.themoviedb.org/movie/615774-scooby-doo-return-to-zombie-island
      - https://www.themoviedb.org/movie/21956-scooby-doo-and-the-monster-of-mexico
      - https://www.themoviedb.org/movie/17681-scooby-doo-and-the-witch-s-ghost
      - https://www.themoviedb.org/movie/12903-scooby-doo-and-the-goblin-king
      - https://www.themoviedb.org/movie/16390-scooby-doo-and-the-samurai-sword
      - https://www.themoviedb.org/movie/67900-scooby-doo-legend-of-the-phantosaur
      - https://www.themoviedb.org/movie/13350-scooby-doo-and-the-ghoul-school
      - https://www.themoviedb.org/movie/12902-scooby-doo-and-the-loch-ness-monster
      - https://www.themoviedb.org/movie/484862-scooby-doo-batman-the-brave-and-the-bold
      - https://www.themoviedb.org/movie/20410-scooby-doo-and-the-alien-invaders
      - https://www.themoviedb.org/movie/302960-scooby-doo-moon-monster-madness
      - https://www.themoviedb.org/movie/533592-scooby-doo-and-the-gourmet-ghost
      - https://www.themoviedb.org/movie/81900-scooby-doo-music-of-the-vampire
      - https://www.themoviedb.org/movie/210769-scooby-doo-adventures-the-mystery-map
      - https://www.themoviedb.org/movie/13351-scooby-doo-in-arabian-nights
      - https://www.themoviedb.org/movie/30074-scooby-doo-and-the-legend-of-the-vampire
      - https://www.themoviedb.org/movie/316272-scooby-doo-and-the-pirates
      - https://www.themoviedb.org/movie/24787-scooby-doo-meets-the-boo-brothers
      - https://www.themoviedb.org/movie/151535-scooby-doo-mask-of-the-blue-falcon
      - https://www.themoviedb.org/movie/260825-scooby-doo-winter-wonderdog
      - https://www.themoviedb.org/movie/560066-scooby-doo-and-the-curse-of-the-13th-ghost
    file_poster: config/assets/Scooby-Doo/Scooby-Doo! Animated Collection.webp
```

**Plex Meta Manager Info**
1.12.2

**Link to logs (required)**
https://gist.github.com/alexander-paterson/a11194b85eaa8d58c14ced919dc58a57
