### ISSUE TITLE
[Feature]: scrape Plex token from Preferences.xml and set Plex server as env variable

### ISSUE THREAD

**Issue by edrock200** [meisnate12/Plex-Meta-Manager#888]
### Is your feature request related to a problem? Please elaborate.

For those of us with multiple Plex servers and docker, would be nice to set the Plex connect string as an env variable and have pmm scrape the token from Preferences.xml (assuming the path is mapped.) Sometimes my token changes and I don't notice for a while. This would also allow for one config file for multiple instances of Plex.

### Describe the solution you'd like

Add config options such as:
Scrape-token=true/false
Preferences-path=/path/to/Plex/Preferences.xml

And an env variable of:
Plex-URL=http://Plex-URL:32400

Pmm could then parse the Token= value from Preferences.xml and sub that and the URL into the config prior to running 

### Additional Information

Thanks for making this awesome utility!!

**Comment by andrewmcd7** [comment]
I would find this useful.

**Comment by meisnate12** [comment]
you can already use multiple servers in on config file you can specify the plex server per library.

```yaml
libraries:
  TV Shows:         # this will use the global plex value since none are specified 
    metadata_path:
      - file: config/TV Shows.yml
  TV Shows On Second Plex:         # this will use the plex value given since it's specified 
    library_name: TV Shows
    plex:
      url: http://192.168.1.98:32400
      token: ####################
    metadata_path:
      - file: config/TV Shows.yml
plex:
  url: http://192.168.1.12:32400
  token: ####################
  ```

and i dont see whats the point of having a separate file just to maintain the token either way you need to update a file with the new token
